### ISSUE TITLE
Missing plugins js when precompiling

### ISSUE THREAD

**Issue by vjnunez** [galetahub/ckeditor#127]
Hi, i installed 3.7.0 on dev and it all worked fine all out the box. But when switching to production and precompiling assets, im missing a lot of javascript files (especially for plugins).

Example errors (on browser):

GET http://www.domain.com/assets/ckeditor/plugins/link/dialogs/link.js?t=C3HA5RM 404 (Not Found)
Uncaught Error: [CKEDITOR.dialog.openDialog] Dialog "link" failed when loading definition.
GET http://www.domain.com/assets/ckeditor/skins/kama/dialog.css?t=C3HA5RM 404 (Not Found)

So i checked the compiled files under public/assets/ckeditor and indeed theres no "image" folder inside public/assets/ckeditor/plugins. The same happens with the rest of plugins.

Any ideas?

Thanks in advance!

**Comment by JoseAlejandroCode** [comment]
> Hi, i don't know why, but rails don't load ckeditor initializer, when run rake assets:precompile:
> 
> ```ruby
>    initializer "ckeditor.assets_precompile", :group => :assets do |app|
>       app.config.assets.precompile += Ckeditor.assets
>    end
> ```
> 
> Maybe it is a rails bug. For quick fix, add this line into application.rb:
> 
> ```ruby
>    config.assets.precompile += Ckeditor.assets
> ```
thank you help me solve it
