### ISSUE TITLE
"CKEDITOR is not defined" problem

### ISSUE THREAD

**Issue by aslam** [galetahub/ckeditor#17]
I am using Rails 3.0.7 too. ruby 1.9.2p0 (2010-08-18 revision 29036) [i686-linux]. I've followed the steps in the README to the point and have included the ckeditor.js file as needed. The file loads but the editor is not shown throwing "CKEDITOR is not defined" error. 

Further, I am using simple_form for my form builder and am using it like this:
<%= simple_form_for(@police_intimation) do |f| %>
  <div class="inputs">
    ...
    <%= f.ckeditor :content, :label => false, :input_html => { :toolbar => 'Full' } %>
    ...
  </div>
<% end %>

This produces this on the form:

<script type="text/javascript">
//<![CDATA[
if (CKEDITOR.instances['police_intimation_content']) {CKEDITOR.remove(CKEDITOR.instances['police_intimation_content']);}CKEDITOR.replace('police_intimation_content', { class: 'text optional',language: 'en',toolbar: 'Full' });
//]]>
</script>

Which throws up "CKEDITOR is not defined" error. I am not sure what is going wrong here.

**Comment by the-teacher** [comment]
BTW. Sometimes is better to wait few seconds if CKeditor not loaded yet

```coffee
    try
      CkeditorOnPage.editors_setup()
    catch e
      setTimeout ->
        CkeditorOnPage.editors_setup()
      , 2000
```
