### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by chrishawk** [galetahub/ckeditor#173]
Hi,

I'm using rails 3.2, the current version of ckeditor gem - 3.7.3

The text area does not appear and in the console I can see javascript throwing the following error - 

Uncaught TypeError: Cannot read property 'length' of undefined ckeditor.js:96
j.add.init.o.on.s ckeditor.js:96
a.event.on.m ckeditor.js:7
a.event.fire ckeditor.js:7
a.editor.fire ckeditor.js:8
a.themes.add.build ckeditor.js:151
u ckeditor.js:27
a.resourceManager.load ckeditor.js:25
a.scriptLoader.load.t ckeditor.js:24
a.scriptLoader.load ckeditor.js:24
a.resourceManager.load ckeditor.js:25
u ckeditor.js:27
s ckeditor.js:27
a.scriptLoader.load.t ckeditor.js:24
a.scriptLoader.load.u ckeditor.js:24
a.scriptLoader.load.v ckeditor.js:24
a.scriptLoader.load.A.$.onload ckeditor.js:24

**Comment by CPE-19** [comment]
Hi,

I got the same error.

I have display text area within dialog box call from the button from toolbar
