### ISSUE TITLE
undefined method `assets' for Ckeditor:Module

### ISSUE THREAD

**Issue by groteck** [galetahub/ckeditor#178]
When I start sever on production enviroment run this error :
    undefined method `assets' for Ckeditor:Module

Rails console on production enviroment run this other error:
    undefined method `setup' for Ckeditor:Module

This is my project git@github.com:groteck/lpl.git.

On development enviroment, I don't have problems.

**Comment by gainskills** [comment]
@groteck , could you please kindly share how you get the issue resolved?
Thanks,
