### ISSUE TITLE
install video plugin

### ISSUE THREAD

**Issue by JohnSmall** [galetahub/ckeditor#198]
How do I install the CKEditor video plugin?

I'm guessing that I'll have to put it in the gem file. Is that correct?

Anyone else had experience adding plugins?

**Comment by cweilemann** [comment]
@galetahub Sorry to post to a 5 year old topic, but I'm trying to do this right now and I just want to clarify...

When I download the video plugin from the site you referenced, I get a folder containing a JS file and multiple subfolders. Should I put the root folder "video" containing the JS file and multiple subfolders under `ckeditor/plugins`, or just the contents of the "video" folder?
