### ISSUE TITLE
CSS issue with latest ckeditor and active_admin

### ISSUE THREAD

**Issue by arwed** [galetahub/ckeditor#211]
I have ckeditor in an active_admin project. Before the latest version it looked like this:

![ckeditor1](https://f.cloud.github.com/assets/1575479/47009/7b08a20a-58ac-11e2-9430-46e6b8807901.jpg)

Now, after updating to the latest ckeditor version in my active_admin project, I get this:

![ckeditor](https://f.cloud.github.com/assets/1575479/46994/5afb6bb0-58ab-11e2-9001-1d7076ef11e9.jpg)

**Comment by kyledecot** [comment]
As this doesn't seem to be related to the gem but rather active_admin I'm going to close this.
