### ISSUE TITLE
simple_form integration not respecting options

### ISSUE THREAD

**Issue by zoeesilcock** [galetahub/ckeditor#230]
I'm trying to send options via the simple_form helper but I can't seem to get it right.

**The readme suggest:**

``` erb
<%= f.input :body, :as => :ckeditor, :input_html => { :ckeditor => { :height => 300 } } %>
```

**I also tried:**

``` erb
<%= f.input :body, :as => :ckeditor, :input_html => { :height => 300 } %>
```

What am I doing wrong?

**Comment by ldestrooper** [comment]
I'm having the same issue, input_html parameters are not getting applied.

Doing some research it seems to be a defer js loading problem.
The javascript containing the parameters needs to be run before the ckeditor, not after it.

But i have no idea on how to fix it and keep my js deferred :-/

**Comment by mesabuca** [comment]
`    <%= f.input :content, as: :ckeditor, input_html: { ckeditor: { height:'600px' } } %>
`It fixed my problem guys I hope it work on your project too
