### ISSUE TITLE
Can't get "mini" toolbar.

### ISSUE THREAD

**Issue by itsNikolay** [galetahub/ckeditor#239]
When I apply the following code, Ckeditor inserts a "Full" toolbar instead of "mini" one.

``` ruby
  .field
    = f.label :annontation
    = f.cktext_area :annontation,
      ckeditor: { language: I18n.default_locale, toolbar: 'mini',
      width: 800, height: 200 }
  .field
    = f.label :content
    = f.cktext_area :content,
      ckeditor: { language: I18n.default_locale, toolbar: 'Full',
      width: 800, height: 800 }
```

**Comment by MirkoCindric** [comment]
Still and issue in rails 4 with simple_form

**Comment by sungwoncho** [comment]
I was able to resolve this by copying and pasting `config.js` file from the gem to `assets/javascripts/ckeditor/config.js`. I am using Rails 4.2.1 with simple_form 3.1.0.
