### ISSUE TITLE
calling .ckeditor

### ISSUE THREAD

**Issue by jarrettgreen** [galetahub/ckeditor#241]
On a comment field, we don't show ckeditor until the user clicks the field. This USED to work. But no longer is. 

``` coffeescript

$('.comment-textarea').click ->
  $this = $(this)
  if CKEDITOR.instances['comment_text']
    CKEDITOR.instances['comment_text'].destroy()
  $this.ckeditor()
```

right now it throws 
_Uncaught TypeError: Object [object Object] has no method 'ckeditor'_

if I change $this. to CKEDITOR.replate($this), it throws
_Uncaught TypeError: Cannot call method 'toLowerCase' of undefined_

**This broke after upgrading to 4.0.2 from '3.7.3'**

Thoughts?

**Comment by kyledecot** [comment]
This probably has something to do w/ a change in the CKEditor API not the gem itself. Are you able to replicate this without the gem?
