### ISSUE TITLE
Browsing pictures - only uploaded by current_user

### ISSUE THREAD

**Issue by panSarin** [galetahub/ckeditor#246]
Hello, I want to specify that current user during browsing server for picture, see only pictures uploaded by himself . 

in ckeditor / lib / ckeditor / helpers / controllers.rb
i see

```
    def ckeditor_pictures_scope(options = {})
      ckeditor_filebrowser_scope(options)
    end

    def ckeditor_attachment_files_scope(options = {})
      ckeditor_filebrowser_scope(options)
    end  

    def ckeditor_filebrowser_scope(options = {})
      { :order => [:id, :desc] }.merge(options)
    end
```

and i see that this helpers are used in ckeditor / app / controllers / ckeditor / pictures_controller.rb 

```
   def index
     @pictures = Ckeditor.picture_model.find_all(ckeditor_pictures_scope)
     respond_with(@pictures) 
   end
```

so basicly this is what i want, but how should i pass options ? overwrite this controller ? or fork ckeditor and change it for my needs? or there is some easier and smoother way ?

**Comment by ceritium** [comment]
@2called-chaos I did and works well

**Comment by omarwaleed** [comment]
@2called-chaos thanks man it works

**Comment by a-very-old-sock** [comment]
With the removal of assetable_type/assetable_id for version 4.2.2 / Rails 5 per #692 and #683, `assetable: ckeditor_current_user` no longer works.
