### ISSUE TITLE
Ckeditor doesn't show validation errors

### ISSUE THREAD

**Issue by rdudacz** [galetahub/ckeditor#251]
Hello,

I am using Client Side Validation gem (https://github.com/bcardarella/client_side_validations), but the validation errors are not displayed on textarea on which is applied ckeditor.

Example of using ckeditor:
= f.cktext_area :descr

How could be possible to fix this issue?

Thanks

**Comment by kyledecot** [comment]
When using the basic `form_for` showing validation errors is up to you. If you were however to use something like `simple_for` then this might work the way you expect.
