### ISSUE TITLE
Users can delete assets owned by other users

### ISSUE THREAD

**Issue by xdmx** [galetahub/ckeditor#259]
Hi, I'm integrating ckeditor on a small side project. Going through the code I've found out that there is a possible security problem when a user deletes an asset.

At the moment it loads them with: Ckeditor.*_file_model.get!(params[:id])

But this doesn't scope that record to the current user (or better assetable type/record), so someone could delete assets from another users, and this is obviously not good (each user has separated assets, scoped in the index through ckeditor_filebrowser_scope)

I think that a possible fix could be using a scope like in the index model which can be customized when needed

**Comment by kyledecot** [comment]
Closing as this is a question related on how to implement CanCan and/or Pundit.
