### ISSUE TITLE
placeholder in "galetahub / rails-ckeditor"  not supported

### ISSUE THREAD

**Issue by kashiftufail** [galetahub/ckeditor#264]
i'm using rails 3.2.12 and "galetahub / rails-ckeditor" for my text areas. But i tried to put placeholder text in text areas like below

      <%=  = f.cktext_area :contact_info ,:class=> 'input-xxlarge' ,:ckeditor => {:uiColor => "#007FFF", :toolbar => "mini"},:placeholder => "Put your name email, phone, address or other contact info here"%>

but it is not working.

Can any one please help

Thanks

**Comment by kyledecot** [comment]
Seems like this is related to CKEditor itself and not the gem. It looks like you'll need to include the configHelper plugin

http://stackoverflow.com/questions/10153018/how-to-display-the-placeholder-attribute-in-html5-textarea-when-ckeditor-is-acti
