### ISSUE TITLE
Heroku and assets:precompile process on deploy

### ISSUE THREAD

**Issue by sasharevzin** [galetahub/ckeditor#270]
I host my rails apps on Heroku and wanted to know if it possible to say rails/heroku do not compile ckeditor because it takes 252.51s.

so any small change takes forever :(

thank you all :)

**Comment by timsco** [comment]
I tried a few things, but I think that using Memcachier for the assets.cache_store finally did the trick (for now):
https://lumi.do/p/0wxerfyp1b3jt/speed-up-heroku-deploys
```ruby
config.assets.cache_store = :dalli_store

**Comment by fabn** [comment]
I don't know if I should open a separate issue, there is a thing I don't understand. If I limit languages and plugins with 

```ruby
Ckeditor.setup do |config|
  # To reduce the asset precompilation time, you can limit plugins and/or languages to those you need:
  config.assets_languages = %w(en)
  config.assets_plugins = ['some', 'plugin']
end
```

Do I still need to include this line in my `config/initializers/assets.rb`

```ruby
Rails.application.config.assets.precompile += %w( ckeditor/* )
```

Moreover the above directory seems broken, if I put `config.assets_plugins = []` and compile the assets locally plugins are still compiled. Maybe I'm doing something wrong.

**Comment by nlib** [comment]
Here is how it worked for me:

Create a new temporary branch
````
git checkout -b temp
````

Remove ckeditor here:
````
Gemfile
application.js
config/ckeditor.rb (delete this file)
````

Bundle and commit. Now push to heroku:
````
git push heroku temp:master
````

Now push again:
````
git checkout master
git push heroku master:master -f
````

You should be good to go from now on.

**Comment by teonimesic** [comment]
@timsco solution worked for me! It also sped things up. Hurray!
