### ISSUE TITLE
No File Browser button in Add image/Add file window.

### ISSUE THREAD

**Issue by leemour** [galetahub/ckeditor#283]
I installed ckeditor according to instructions, generated models for Carrierwave, migrated, but the File Browser button isn't displayed when I choose to Add image to textarea. In the modal window it's style is `display: none` and `href='javascript:void(0)'`.

I'm using Rails 3.2.13, with last version of Ckeditor gem. Installed Imagemagick and Minimagick gem. Separate file uploads with Carrierwave work just fine.
What can cause the problem?

**Comment by kalashnikovisme** [comment]
may be solution for this problem is here http://stackoverflow.com/questions/21928348/rails-4-ckeditor-file-upload
