### ISSUE TITLE
ActiveAdmin + Rails 4 => Overzealous expansion of ckeditor

### ISSUE THREAD

**Issue by mwlang** [galetahub/ckeditor#286]
The ckeditor when used with Active Admin rails4 branch and Rails 4.0.0 (final) is overzealous in its expansion, incorporating the label "body" in the attached image.

![ckeditor_overzealous](https://f.cloud.github.com/assets/18387/738801/6404d8cc-e34d-11e2-8b37-35254aeac2d5.png)

The toolbar itself seems to be correctly stopped and position, but the edit area is too big.  How to fix?

**Comment by railsfactory-madhusudhan** [comment]
thanks Jame and giathi. Both worked fine. But giathi's solution is perfect!!!

**Comment by paulmwatson** [comment]
Thanks @giathinh910, that worked perfectly.

**Comment by Giathi-Daniel** [comment]
I would like to contribute to future projects. Where can I find you giathi
