### ISSUE TITLE
Migration problen

### ISSUE THREAD

**Issue by gogainda** [galetahub/ckeditor#292]
I am using seed_dumper for generation seed.rb file. I added picture to text area and made a seed.rb file

```
Ckeditor::Picture.create([
  { :id => 1, :data_file_name => "15-mg_1571.jpg", :data_content_type => "image/jpeg", :data_file_size => 61512, :assetable_id => nil, :assetable_type => "f", :type => "Ckeditor::Picture", :width => 995, :height => 663, :created_at => "2013-07-10 19:42:57", :updated_at => "2013-07-10 19:42:57" }
], :without_protection => true )
```

Then I dropped db, migrated and tried to run db:seed
There was a error 'Cannot find the geometry of a file with a blank name'
Stacktrace is here https://gist.github.com/gogainda/5969860

**Comment by kyledecot** [comment]
@gogainda were you able to get this resolved?
