### ISSUE TITLE
Is there a ckeditor version working with Rails 4 production?

### ISSUE THREAD

**Issue by bsylvain** [galetahub/ckeditor#307]
I tried th classic gem "ckeditor"  version and  this one : 

gem "ckeditor", :git => "https://github.com/adamico/ckeditor.git", 
    :branch => "rails-4-compatibility"

I can go around the bug of textarea not recognized with adamico version. Howerver when pushed in production it does not work, ckeditor want to load the assets without the digest : 

```
(No route matches [GET] "/assets/ckeditor/config.js")
```

I use thoses settings in application.rb : 

```
config.assets.enabled = true
config.assets.precompile += Ckeditor.assets
config.autoload_paths += %W(#{config.root}/app/models/ckeditor)
```

How can i make ckeditor works in rails 4? Is it possible?

**Comment by mohnstrudel** [comment]
Wow, it's 2017 and I've got still same issues with making CKEditor work in Production (VDS).

**Comment by peter-hank** [comment]
If you need a handy solution, install https://rubygems.org/gems/non-stupid-digest-assets (haha).

And then create `config/initializers/non_digest_assets.rb` with the following content:
```ruby
NonStupidDigestAssets.whitelist += [/ckeditor\/.*/]
```

Recompile the assets and it should work. No need to set `config.assets.compile = true`.

**Comment by sammyjopeters** [comment]
4 years later, @danielboggs' suggestion (with @markbao's additions) got this working for me.

Sorry @peter-hank - I couldnt get `non-stupid-digest-assets` to work.

**Comment by Landoghini** [comment]
I've followed @danielboggs and @markbao suggestions and Im still unable to get it to work with heroku.

**Comment by joaovian06** [comment]
Is there any update on this issue?
