### ISSUE TITLE
Uploads and capistrano.

### ISSUE THREAD

**Issue by bsylvain** [galetahub/ckeditor#311]
CKeditor images are uploaded to public/ckeditor_asset

How can i change this directory to public/system or how can i set capistrano to create a symlink to shared?

**Comment by feliperaul** [comment]
I know this was asked like 5 years ago, but since it's still open...

On your config/deploy.rb file, add something like this:

```
set :linked_dirs, fetch(:linked_dirs, []).push(
  'log',
  'tmp/pids',
  'tmp/cache',
  'tmp/sockets',
  'vendor/bundle',
  'public/uploads',
  'public/ckeditor_asset',
  'public/sitemap',
  'public/xml',
  'public/packs',
  'node_modules',
  'storage'
)
```
