### ISSUE TITLE
Rails 4 production can't find files

### ISSUE THREAD

**Issue by connor-t** [galetahub/ckeditor#333]
This isn't working in production ( ubuntu vps ), development works fine but I get the errors shown below in production

Failed to load resource: the server responded with a status of 404 (Not Found) http://198.211.118.102/assets/admin/ckeditor/config.js?t=D6IE
Failed to load resource: the server responded with a status of 404 (Not Found) http://198.211.118.102/assets/admin/ckeditor/skins/moono/editor.css?t=D6IE
Failed to load resource: the server responded with a status of 404 (Not Found) http://198.211.118.102/assets/admin/ckeditor/lang/en.js?t=D6IE
Failed to load resource: the server responded with a status of 404 (Not Found) http://198.211.118.102/assets/admin/ckeditor/styles.js?t=D6IE
Uncaught [CKEDITOR.resourceManager.load] Resource name "default" was not found at "http://198.211.118.102/assets/admin/ckeditor/styles.js?t=D6IE".

**Comment by vajradog** [comment]
I had the same problem. adding the following file in application.rb seems to solve it
```
class Application < Rails::Application
    config.assets.precompile += Ckeditor.assets
    config.assets.precompile += %w( ckeditor/* )
    config.autoload_paths += %W(#{config.root}/app/models/ckeditor)
end
```

**Comment by nmoore2** [comment]
The last step in my process was to run: 

```
rake assets:clobber
rake tmp:clear
rake assets:precompile
```

Source: https://github.com/galetahub/ckeditor/issues/707
