### ISSUE TITLE
rails 4.0.2 customer config.js  production no loading assets/config.js 

### ISSUE THREAD

**Issue by peterwillcn** [galetahub/ckeditor#374]
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (config.js, line 0)
https://www.xxx.org/assets/ckeditor/config.js?t=DBAA

if(typeof(CKEDITOR) != 'undefined')
{
    CKEDITOR.editorConfig = function( config )
    {
        //config.uiColor = "#AADC6E";
        config.pasteFromWordCleanupFile = 'plugins/pastefromword/filter/custom.js';
        config.extraPlugins = 'insertResolved'; 
        config.toolbar =
        //config.toolbar_MyToolbar =
        [
        { name: 'document', items : [ 'Maximize','NewPage','Preview','insertResolved','Save' ] },
        { name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
        { name: 'editing', items : [ 'Find','Replace','-','SelectAll' ] },
                { name: 'tools', items : [ 'Source' ] },
        //{ name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ] },
        //  '/',
        { name: 'styles', items : [ 'Styles','Format' ] },
        { name: 'basicstyles', items : [ 'Bold','Italic','Underline', 'Strike','-','RemoveFormat' ] },
        { name: 'paragraph', items : [ 'NumberedList','BulletedList', 'HorizontalRule','-','Outdent','Indent','-','Blockquote' ] }
        //{ name: 'links', items : [ 'Link','Unlink','Anchor' ] }
    ];
    }
} else{
  console.log("ckeditor not loaded")
}

**Comment by budu** [comment]
+1

**Comment by sungwoncho** [comment]
Same issue here.
