### ISSUE TITLE
Bug assets

### ISSUE THREAD

**Issue by Sega100500** [galetahub/ckeditor#387]
Ruby on Rails 3.2.16

Same code after update to gem 4.0.9 raise errors:

"NetworkError: 404 Not Found - http://site:3000/assets/assets/ckeditor/config.js?t=E0LB"
"NetworkError: 404 Not Found - http://site:3000/assets/assets/ckeditor/skins/moono/editor_gecko.css?t=E0LB"
"NetworkError: 404 Not Found - http://site:3000/assets/assets/ckeditor/lang/ru.js?t=E0LB"
"TypeError: this[a] is undefined"

On CKeditor gem 4.0.8 ALL WORKS FINE

**Comment by at-longhpv** [comment]
I got this error with ckeditor (4.2.2) and Rails 5.0.1
