### ISSUE TITLE
File upload not working with Rails 4.1.0-beta1

### ISSUE THREAD

**Issue by chandresh** [galetahub/ckeditor#410]
I have an application developed using Rails 4.1.0-beta1 in which uploading files is not working. Here is the error I see in the logs:

```
ActionController::RoutingError (No route matches [POST] "/ckeditor/EDITOR.config.filebrowserImageUploadUrl")
```

Not sure why it is appending the configuration variable! Also, when I look at the source of the file upload popup, I see this:

```
(function() { new qq.FileUploaderInput({"multiple":true,"element":"fileupload","action":"EDITOR.config.filebrowserImageUploadUrl","allowedExtensions":  ["jpg","jpeg","png","gif","tiff"]}); }).call(this);
```

I think the value of EDITOR.config.filebrowserImageUploadUrl should be placed there. This might be an issue related to rails 4.1. Any help would be appreciated.

**Comment by hoaianr** [comment]
Thanks @beance 
gem 'activesupport-json_encoder', github: 'rails/activesupport-json_encoder' worked fine for me
