### ISSUE TITLE
IFrame problems on IE11

### ISSUE THREAD

**Issue by toptierlabs** [galetahub/ckeditor#413]
I am using the image uploader plugin. It works perfect on Chrome, Safari, Firefox and IE8-10, but it fails on IE11. 

The problem is an access denied on getFrameDocument function.

getFrameDocument: function () {
            var i = this.$;
            try  {
                i.contentWindow.document;
            } catch (j) {
                i.src = i.src;
                if(c && b.version < 7) {
                    window.showModalDialog('javascript:document.write("<script>window.setTimeout(function(){window.close();},50);</script>")');
                }
            }
            return i && new g(i.contentWindow.document);
        },

The first call to i.contentWindow.document throws an exception but i.src = i.src doesnt fix it, throwing access is denied error.
This is the content of my iframe (weird) :

<iframe title="File" class="cke_dialog_ui_input_file" id="cke_47_fileInput" src="javascript:void(0)" frameborder="0" allowtransparency="0">
<html><head>
        <link href="NewErrorPageTemplate.css" rel="stylesheet" type="text/css">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>This page can’t be displayed</title>

        <script language="javascript" src="errorPageStrings.js" type="text/javascript">
        </script>
        <script language="javascript" src="httpErrorPagesScripts.js" type="text/javascript">
        </script>
    </head>

    <body onload="javascript:getInfo();">
        <div class="mainContent" id="contentContainer">
            <div class="title" id="mainTitle">This page can’t be displayed</div>
            <div class="taskSection" id="taskSection">
                <ul class="tasks" id="cantDisplayTasks">
                    <li id="task1-1">Make sure the web address <span class="webpageURL" id="webpage">//ieframe.dll/dnserrordiagoff.htm# </span>is correct.</li>
                    <li id="task1-2">Look for the page with your search engine.</li>
                    <li id="task1-3">Refresh the page in a few minutes.</li>
                </ul>
                <ul class="tasks" id="notConnectedTasks" style="display: none;">
                    <li id="task2-1">Check that all network cables are plugged in.</li>
                    <li id="task2-2">Verify that airplane mode is turned off.</li>
                    <li id="task2-3">Make sure your wireless switch is turned on.</li>
                    <li id="task2-4">See if you can connect to mobile broadband.</li>
                    <li id="task2-5">Restart your router.</li>
                </ul>
            </div>
        </div>
    
</body></html>
</iframe>

Any help?
I am using version 3.6.3 and updating is not an option.

**Comment by kyledecot** [comment]
This sounds like it's related to CKEditor itself and not this gem specifically so I'm going to close this issue but I encourage you to post this on StackOverflow if you haven't done so already.
