### ISSUE TITLE
4.0.8 broke my 'Browse Server' view

### ISSUE THREAD

**Issue by etlund** [galetahub/ckeditor#427]
Since the 4.0.8 update to add pagination, the "Browse Server" window from the images dialog is no longer showing pics I've already uploaded. Backing down to  4.0.7 and everything works fine.

This is on a Rails 3.2.17 app.

**Comment by igorkasyanchuk** [comment]
Please try this PR if it works for you with my fix
https://github.com/galetahub/ckeditor/pull/607

**Comment by Sega100500** [comment]
@igorkasyanchuk 
Already work fine in 4.1.3
Just update ckeditor gem to current version

**Comment by igorkasyanchuk** [comment]
@Sega100500 actually I've it, and it doesn't, but maybe my issue is just different, I was doing search and found this issue.
Ruby 2.2
Rails 4.2.4
CKEditor 
GEM = "4.1.3".freeze
EDITOR = "4.5.2".freeze
