### ISSUE TITLE
"Browse Server" images list only last 24 images without pagination

### ISSUE THREAD

**Issue by Sega100500** [galetahub/ckeditor#428]
"Browse Server" images list only last 24 images without pagination

When "Load" multiple images - show ALL loaded
But when again open "Browse Server" - shows only last 24 images

It seems that only the first page with images is displayed. No pagination displayed. Why so?
 I try it on RoR 3.2.17, ckeditor 4.1.1, paperclip 4.1.1

**Comment by igorkasyanchuk** [comment]
Please try this PR if it works for you with my fix
https://github.com/galetahub/ckeditor/pull/607
