### ISSUE TITLE
Not showing all icons on rails 4 app production

### ISSUE THREAD

**Issue by rinterliche** [galetahub/ckeditor#429]
I followed the tutorial about using non digest assets in order to correctly precompile and run the CKEditor on my rails 4 app.
It works almost 100%, the snag is in the icong.png processed, seems that it's incomplete and part of the icons are out of the sprite, as seeing bellow.
![screen shot 2014-03-31 at 2 02 16 pm](https://cloud.githubusercontent.com/assets/1128633/2570214/4f917bb4-b8f6-11e3-8ea6-f532095e83db.png)

**Comment by nekogami** [comment]
Did you find a solution ? I'm having the same issue here.
