### ISSUE TITLE
Issue on file validation with paperclip?

### ISSUE THREAD

**Issue by lfglopes** [galetahub/ckeditor#431]
I've recently updated my gem to the latest version and I'm using it with paperclip 4.x.

I've setup an upload tab on the 'new image dialog'. But when I upload a file with an invalid extension it [renders nothing](https://github.com/galetahub/ckeditor/blob/master/app/controllers/ckeditor/application_controller.rb#L24), making the fileinput disapear with out any kind of feedback. 

Am I missing something here? If not I'm thinking in working on a PR to address this

**Comment by gruberjl** [comment]
Did you ever find a work around for this?

**Comment by lfglopes** [comment]
See the commit galetahub/ckeditor@6566a54ef5c720214109ab848433442ac7a11ede which prints the error message generated by paperclip below the input field (or it comes in the form of a javascript alert, not sure - it was a long while ago). 

Given that the commit was merged into master I would consider this issue solved (although a more fashionable solution could arise).
