### ISSUE TITLE
Rails 4.1

### ISSUE THREAD

**Issue by Mike-Petersen** [galetahub/ckeditor#436]
I was updating to rails (4.1.0) and i am using ckeditor (4.0.11). I got the following error:
throw Error("Sprockets::Rails::Helper::AssetFilteredError: Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( ckeditor/filebrowser/javascripts/fileuploader.js )` to `config/initializers/assets.rb` and restart your server\n  (in /home/mike/.rvm/gems/ruby-2.1.1/gems/ckeditor-4.0.11/app/assets/javascripts/ckeditor/override.js.erb)")

If i remove the "ckeditor/override" from the application.js everything is working. But due to the hash i would get errors later in production. The error occurs during the call:
"<%= asset_path(asset) %>"  in the override.js.erb.

**Comment by pierre-pretorius** [comment]
Please push the latest code to rubygems, using: `gem 'ckeditor', :git => `https://github.com/galetahub/ckeditor.git'` fixed this issue for us with Rails 4.1 **without** non-stupid-digest-assets gem.
