### ISSUE TITLE
Deleting attached image CKEDITOR + Paperclip + Rails 4

### ISSUE THREAD

**Issue by ryankc33** [galetahub/ckeditor#447]
I'm facing a problem here, and hours of experimenting and googling have yet to yield any answers.

I have the following model

```
Post.rb

  Paperclip.interpolates :slug do |attachment, style|
     attachment.instance.slug
  end

  #Image attachment
  has_attached_file :image,
    styles: { :content=> "460x460>"},
    url: "/images/:class/:attachment/:slug/:style/:hash.:extension",
    path: ":rails_root/public/images/:class/:attachment/:slug/:style/:hash.:extension
```

which works well when uploading an image directly through a filefield. I needed a wysiwyg editor so I used the galetahub gem, which generates the following model for attaching images:

```
class Ckeditor::Picture < Ckeditor::Asset
  # include Resizable

  has_attached_file :data,
                    styles: { :content=> "460x460>"},
                    url: "/images/:class/:attachment/:id/:style/:hash.:extension",
                    path: ":rails_root/public/images/:class/:attachment/:id/:style/:hash.:extension"

                    validates_attachment_content_type :data, :content_type => /\Aimage/
                    # validates_attachment_size :data, :less_than => 2.megabytes
                    validates_attachment_presence :data
                    # do_not_validate_attachment_file_type :data


  def url_content
    url(:content)
  end

end
```

Uploading works fine. Here's my problem

When I edit the post, and delete the image in the ckeditor field, the image file remains in the file system.

It's a time bomb! So the questions are:
1. How do I associate the image file uploaded with CKeditor with right Post
2. How do I ensure that the image file is deleted from the file system when the image is deleted from the Post on CKeditor?

gems used:

```
gem "ckeditor"
gem "non-stupid-digest-assets", "~> 1.0.2" # dependency of ckeditor
gem "paperclip", "~> 3.5.3" # image upload
gem "rmagick", "~> 2.13.2" # image manipulation
```

**Comment by iqorlobanov** [comment]
in your model
before_destroy :remove_file

def getImagesDir
    @doc = Nokogiri::HTML(self.context)
    if (!@doc.css('img').blank?)
      @file = @doc.css('img')[0]['src']
      @dir = File.expand_path("..", @file)
      return @dir
    end
  end

def remove_file
    if !getImagesDir.blank?
      FileUtils.rm_rf(Rails.root.join('public', getImagesDir[1..-1]))
    end
  end
