### ISSUE TITLE
How can you add plugins to CKEditor for Ruby?

### ISSUE THREAD

**Issue by ryanxdrake** [galetahub/ckeditor#450]
Hi there,

I was just curious which folder to add plugins to for this gem?

Thanks!

**Comment by Anyoks** [comment]
Added plugin, Thank you @jhenkens, @zolzaya and @iamryandrake for the solutions you posted. Helped me a great deal.

I have an issue though, the plugin worked on development mode and would not appear on production. The logs show nothing substantial. Anyone figure out how to get it to work? Been working all day in this!

Thank you!

**Comment by arpit016** [comment]
@Anyoks Did you made it to work in production?, I am facing similar issue.

**Comment by krongk** [comment]
Rails 5.5.1
gem ckeditor 4.2.2

the same issue in production env.

**Comment by Babbz75** [comment]
Anyone having trouble getting the iframe plugin to work?

https://ckeditor.com/addon/iframe

**Comment by williamair1** [comment]
Is there a working solution for this? I cannot get it to work as well.

**Comment by bnymn** [comment]
@williamair1 Did you try the second message on this issue? Written by @renatosuero.

**Comment by williamair1** [comment]
I tried the solutions suggested by both @renatosuero and @jhenkens. I was trying to install the [lite](https://ckeditor.com/cke4/addon/lite) plugin.
As for @renatosuero's solution, I tried with the eqneditor as well.

1. Downloaded the zipped file from the [link](https://ckeditor.com/cke4/addon/eqneditor)
2. Created the` /javascripts/ckeditor/plugins` folder and unzipped the file at this location
3. Created the `config.js` file and added the plugin
4. Restarted server, but see no difference in the toolbox.

**Comment by Tashows** [comment]
Shouldn't:

`%w(openlink sourcedialog).each do |ckeditor_plugin|
    Ckeditor.assets += Dir[ckeditor_plugins_root.join(ckeditor_plugin, '**', '*.js')].map {|x|              x.sub(assets_root.to_path, '').sub(/^\/+/, '')}
  end`

be replaced with this?

`config.assets_plugins.each do |ckeditor_plugin|
    Ckeditor.assets += Dir[ckeditor_plugins_root.join(ckeditor_plugin, '**', '*.js')].map {|x|              x.sub(assets_root.to_path, '').sub(/^\/+/, '')}
  end`

I'm saying this cause I've seen that code being used in other questions and everyone has those two plugins (openlink and sourcedialog), when it seems that there should be a note that they need to be changed. Or did I understand something wrong?
