### ISSUE TITLE
Missing list tools (ordered/unordered lists) in inline editor?

### ISSUE THREAD

**Issue by yosriady** [galetahub/ckeditor#451]
My inline CKEditor toolbar seems to be missing the list tools for bulleted and numbered lists, namely the leftmost two buttons below: 
![screen shot 2014-06-04 at 11 43 21 am](https://cloud.githubusercontent.com/assets/1084226/3169355/82c5575e-eb9a-11e3-9f3a-d3352088c899.png)

My default inline CKEditor toolbar (note missing list buttons):
![screen shot 2014-06-04 at 11 46 54 am](https://cloud.githubusercontent.com/assets/1084226/3169373/f12b71c4-eb9a-11e3-8ab3-f9b2cbeb131b.png)

Investigating further, I tried to explicitly define a toolbar containing only the list tools: 
(Note that "paragraph" tools are included for numbered and bulleted lists, yet does not appear in the rendered toolbar.)

```
CKTOOLBAR = [
  {
    name: "basicstyles"
    groups: [
      "basicstyles"
      "cleanup"
    ]
    items: [
      "Bold"
      "Italic"
      "Underline"
      "Strike"
      "Subscript"
      "Superscript"
      "-"
      "RemoveFormat"
    ]
  }
  {
    name: "paragraph"
    groups: ["list"]
    items: [
      "NumberedList"
      "BulletedList"
    ]
  }
  {
    name: "colors"
    items: [
      "TextColor"
      "BGColor"
    ]
  }
]

@setupCKEditor = ->
  CKEDITOR.disableAutoInline = true
  $("[contenteditable='true']").each (index) ->
    CKEDITOR.inline this,
      toolbar: CKTOOLBAR
```

My resulting CKEditor toolbar:
![screen shot 2014-06-04 at 11 49 11 am](https://cloud.githubusercontent.com/assets/1084226/3169387/543b7386-eb9b-11e3-959e-2be82eb9b022.png)

Is this a bug or am I missing something?

**Comment by arblackman** [comment]
I'm also seeing this - was there ever any solution ??

**Comment by tom-wmg** [comment]
I think I just ended up using the full richtext editor instead of the inline one...
