### ISSUE TITLE
assets/ckeditor/lang/en.js?t=E5OD 404 (Not Found)

### ISSUE THREAD

**Issue by kevin-jj** [galetahub/ckeditor#468]
assets/ckeditor/lang/en.js?t=E5OD 404 (Not Found)
It works in dev but not production.

Production Environment:
Rails 3.2.19
ckeditor 4.1.0

any ideas?

**Comment by rovitulli** [comment]
Thanks :-)

**Comment by jtomaszewski** [comment]
This error appears even if I'm using the ckeditor from CDN. Is there an option to make the ckeditor load the lang files from CDN?

**Comment by kcc0** [comment]
I'm currently facing this issue with Rails 5 even after applying @kevin-jj solution. Any idea how to deal with this in Rails 5 and the whole manifest.js file?

**Comment by kcc0** [comment]
Never mind, I had to do this to get it working -> `Rails.application.config.assets.precompile += %w(ckeditor/* ckeditor/lang/*)`.

I don't know why the first declaration doesn't just include the lang folder in the first place (it works for the adapters, plugins, and skins folders). Bug maybe?
