### ISSUE TITLE
Default locales

### ISSUE THREAD

**Issue by jlerpscher** [galetahub/ckeditor#475]
Hi,

I just find #34 :

I am using copycopter and ckeditor create lot of useless locales. So,

> is it possible to configure the locales to load. let's say i just want the en.yml and de.yml files loaded and not all of them. is it possible? thanks!
> @marcusg

**Comment by diegodurante** [comment]
UP

**Comment by dgilperez** [comment]
Any news?

**Comment by fgranvik** [comment]
I have the same need to specify which locales to load
