### ISSUE TITLE
Carrierwave issue

### ISSUE THREAD

**Issue by dr0p** [galetahub/ckeditor#477]
Hello,
i've got rails 4.02, carrierwave 0.9.0. I cannot upload images, due to __undefined method `has_attached_file'__ in file __app/models/ckeditor/picture.rb__

Can anyone help?

**Comment by kyledecot** [comment]
`has_attached_file` is a Paperclip function. It sounds like you did `rails generate ckeditor:install` w/ the wrong backend param.
