### ISSUE TITLE
Prevent Ckeditor from removing "script" tags

### ISSUE THREAD

**Issue by NomNomCameron** [galetahub/ckeditor#480]
I saw that this can be changed in "allowedContent" for the config but I either don't know or just can't get the syntax for that config for this gem to work? Has anyone else gotten this working?

**Comment by nevergone** [comment]
And now?

**Comment by eveevans** [comment]
now ?

**Comment by dipen10612055** [comment]
I tried the solution that you provided @eveevans, but still might ckeditor seems to delete the script tags on backspacing or deleting a string from the UI.
How can we prevent the script tags form getting deleted? Any help is appreciated.
