### ISSUE TITLE
not working in rails 4.1 production

### ISSUE THREAD

**Issue by ramza1** [galetahub/ckeditor#481]
i have tried ckeditor in development and everything works fine. but when i go to production mode, i get the following javascript error and ckeditor fails to display.

Uncaught TypeError: Cannot set property 'dir' of undefined

**Comment by Mithul** [comment]
The above solution still doesnt work for me.

**Comment by davidrichey** [comment]
@davoclavo your solution worked for me. I had an error in deploying an app with ckeditor to heorku. Adding the precompile line you gave did the trick. Thank you! :+1:

**Comment by Aathi** [comment]
I have added this and worked for me
**#config/application.rb
config.assets.precompile += %w( ckeditor/* )**

**Comment by CV-Gate** [comment]
It should be `config.assets.precompile += %w( ckeditor/* )`
