### ISSUE TITLE
not working with turbolinks

### ISSUE THREAD

**Issue by aravindgd** [galetahub/ckeditor#482]
I am able to do see the Ckeditor if I refresh the page or type the url manually and come. It is not working with turbolinks. Anyone fixed it?

**Comment by kyledecot** [comment]
@aravindgd Did using jQuery Turbolinks solve your issue?

**Comment by RouL** [comment]
At least for me it's not helping. It is only loading the editor one time. If I go back on my list and open a different row for editing it is not loading anymore

**Comment by henriquesacramento** [comment]
After lot of time googling my solution was remove complete turbolinks =(

**Comment by RouL** [comment]
You don’t need to disable it. You only need to make sure, that all links that are leading to a page with a ckeditor don’t use turbolinks till there is a solution. Just add this to those links or the parent tag: ´data-no-turbolink´ (or in link_to: ´data: { ’no-turbolink’: true }´)

**Comment by henriquesacramento** [comment]
@RouL not work on my app

**Comment by RouL** [comment]
@henriquesacramento then you make a mistake somehow. Did you check the links after loading the page (for example with the inspector in firefox)? Do they really have `data-no-turbolink` added to the a-tag (or the parent tag of the links)? Check this: https://github.com/rails/turbolinks#opting-out-of-turbolinks

**Comment by Envek** [comment]
jquery.turbolinks helped me, thanks

**Comment by henriquesacramento** [comment]
data-no-turbolink worked in my app thx @RouL
