### ISSUE TITLE
Dynamic config

### ISSUE THREAD

**Issue by DanielYWoo** [galetahub/ckeditor#483]
I have my own file browser and I can integrate it with CKEditor this way

```
  CKEDITOR.config.filebrowserBrowseUrl = '/files/browse';
```

That's easy and cool. However, I need to pass in a couple of dynamic parameters like 'path=/2014/05&type=image', the two parameters could change so that the user will be automatically navigated to the desired path on my file server. I cannot find a way to change 'filebrowserBrowseUrl' once the editor is initialized. Could you allow dynamic config for this parameter?

**Comment by magicmarkker** [comment]
:+1: please please someone help with this, i have a multi tenant app that needs asset uploads to be filtered by the tenant id
