### ISSUE TITLE
rails 4 Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by alexnofoget** [galetahub/ckeditor#484]
after last update show this error in console of chrome:

```
Uncaught TypeError: Cannot read property 'remove' of undefined 
```

in FF:

```
TypeError: d is undefined
..].ltr?"ltr":"rtl"}});e.language_remove={label:d.remove,group:"language_remove",s...
```

**Comment by chaoming** [comment]
I believe this is related to the configuration since I have two sites using ckeditor and the one with more buttons has this issue while the other one works fine.

**Comment by iremillard** [comment]
Anyone figure out what is going on?

**Comment by TaiwoAyanleye** [comment]
+1

**Comment by martinezcoder** [comment]
+1

**Comment by alexanderadam** [comment]
Hey guys,

[@ivankosdy is right](https://github.com/galetahub/ckeditor/issues/484#issuecomment-59131699) that the reason for this is the language plugin. That means you will either have to change the language stuff as @ivankosdy said (and documented in [the plugin](http://docs.ckeditor.com/#%21/api/CKEDITOR.config-cfg-language_list)) or just deactivate the language plugin by setting
```javascript
config.removePlugins = 'language';
```
as [described in the documentation](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-removePlugins).

I guess deactivating the plugin will be easier in most cases.
