### ISSUE TITLE
Critical bug, fixed in ckeditor 4.4.5, is crippling latest versions of Safari

### ISSUE THREAD

**Issue by mattbrictson** [galetahub/ckeditor#491]
The version of Safari shipping with iOS 8 as well as the latest desktop versions of Safari (e.g. 7.1) all suffer from a bug where the return key doesn't work in ckeditor:

http://dev.ckeditor.com/ticket/12423

This bug was fixed in ckeditor 4.4.5. Can you release a new version of the gem that includes 4.4.5?

I would open a PR but I'm not sure how to incorporate the ckeditor files into the gem. If there is anything I can do to help, let me know.

**Comment by mailtoyogeshpatel** [comment]
I am using ckeditor 4.4.3,

Where i can find patch file for Ticket #12423

There is no file at the said location "​​branch:t/12423".
