### ISSUE TITLE
CKEditor error during precompile task

### ISSUE THREAD

**Issue by onthebeachh** [galetahub/ckeditor#508]
I get this error when I try to push to heroku. At first I thought was heroku but then I tried to precompile on local environment with same result.

Sass::SyntaxError: Invalid CSS after "...e-height:44px;*": expected identifier, was "/"

I've tried to fix this problem overriding the source files, also I tried adding some features to  production.rb

Rails.application.config.assets.precompile += Ckeditor.assets
Rails.application.config.assets.precompile += %w( ckeditor/\* )

but well.. What am I missing?
Regards

**Comment by lesteratsciencebite** [comment]
Hi, not sure if you're still stuck on this, but something similar happened to me on a rails project.  My problem was I had a version of ckeditor in /vendor/assets/ so rails was trying to load those files and the same files from the gem.  I deleted those files and the deploy started working just fine.   If you have config.js in there you'll have to move it out.

**Comment by onthebeachh** [comment]
thanks, I actually was think about that.
I'll try your solution and then let you know about it
best
