### ISSUE TITLE
ckeditor + devise's authenticate_user!

### ISSUE THREAD

**Issue by riggy** [galetahub/ckeditor#518]
Hi guys!

I'm struggling with devise session being cleared out whenever I open ckeditor file manager window. At first I thought it was issue with csrf_token, but I was wrong.

My ApplicationController invokes a global `before_filter` like this:

```
class ApplicationController < ActionController::Base
  ...
  before_filter :authenticate_user!
  ...
end
```

I was able to fix this by overriding (monkey patching ugh...) `Ckeditor::ApplicationController` and changing it's inheritance to make it inherit from my app `ApplicationController` instead of `ActionController::Base`. This allowed the session to be kept intact when accessing ckeditor's controllers.

The question is: is there a better, nicer way of achieving this without resorting to monkey patching (ugh..)?

Thanks

**Comment by bnymn** [comment]
I think this is a huge security issue.

**Comment by riggy** [comment]
Well, after over 2 years it's hardly any issue for me anymore (project long forgotten). But thanks for your answer @bnymn!
