### ISSUE TITLE
Problem and solution: Full asset-pipeline integration

### ISSUE THREAD

**Issue by randoum** [galetahub/ckeditor#519]
Greetings,

I use Rails 4.1.8 with ckeditor 4.1.1, and I got few problems with assets-pipeline integration. I've come with a suggested solution and would like to know your feed back on it. If the solution is considered acceptable I could work on a PR

So I got 3 items that does not play nice all together

**1)** 3 following customization files to customize ckeditor:
app/assets/javascripts/ckeditor/config.js
app/assets/javascripts/ckeditor/styles.js
app/assets/stylesheets/ckeditor/contents.css

**2)** the following initializer in initializers/ckeditor.rb to limit the number of plugins and languages compiled by assets-pipeline

```
Ckeditor.setup do |config|
  config.assets_languages = %w[en fr]
  config.assets_plugins = %w[clipboard dialog div fakeobjects image link liststyle magicline pagebreak pastefromword specialchar table tabletools
  ]
end
```

**3)** The webserver assets "Far-future Expires Header" cache config (as advised in rails guides) to keep in client cache all files under assets directory. As you know this setting relies on fingerprint file name generated by asset pipeline during compilation

---

### Case 1

If I don't follow the README advise and don't add ckeditor path to `config.assets.precompile`, when I precompile assets and deploy to my production server, I got the following result:
- Only the plugins and languages I specified in my initializer are compiled
- But the config.js and styles.js files are not found by ckeditor, and it fail to load

---

### Case 2

If I follow the README advise and add `config.assets.precompile += %w[ckeditor/*]` to application.rb, when I precompile assets and deploy to my production server, I got the following result:
- All plugins and all languages are compiled, ignoring the settings from my initalizer and consuming much more time for compilation
- The config.js and styles.js files are found by the editor, so it succeed to load
- But config.js and styles.js loaded by ckeditor are the files without fingerprint which is not compatible with the webserver "Far-future Expires Header" settings 

---

### Solution

The ideal situation would be to have all the 3 point mentioned in the begining of this ticket to work all together. I succeed to achieve it with the following simple steps, and I'd like your experts feedback on this. Perhaps I can propose a PR for further testing if it looks good:

**A** In application.js manifest do not add `//= require ckeditor/init` as advised by README, but instead add `//= require ckeditor/loader`

**B** Create app/assets/javascripts/ckeditor/loader.js.erb file with the following content

```
//= require ckeditor/init

CKEDITOR.config.customConfig = '<%= javascript_path 'ckeditor/my_config.js' %>';
CKEDITOR.config.stylesSet = 'default:<%= javascript_path 'ckeditor/my_styles.js' %>';
CKEDITOR.config.contentsCss = '<%= stylesheet_path 'ckeditor/my_contents.css' %>';
```

**C** Create the following files with your own content:
- app/assets/javascripts/ckeditor/my_config.js
- app/assets/javascripts/ckeditor/my_styles.js
- app/assets/stylesheets/ckeditor/my_contents.css

**D** in config/application.rb do not add `Rails.application.config.assets.precompile += %w( ckeditor/* )` as advised by README, but instead add `config.assets.precompile += %w( ckeditor/my_config.js ckeditor/my_styles.js ckeditor/my_contents.css )`

**E** Compile and deploy as usual

As a result ckeditor will load the fingerprinted version of the 3 configuration files (taking advantage of "Far-future Expires Header" config), and the assets compilation was done only for the specified plugins and languages. It's all good.

I believe integrating all those steps in the source of ckeditor would be easy, and we could define the 3 files path in the `Ckeditor.setup` block

Tell me what you think

**Comment by jantequera** [comment]
+1

**Comment by randoum** [comment]
>  I'd like your experts feedback on this. Perhaps I can propose a PR for further testing if it looks good

@galetahub kindly have a look. I am willing to work on a PR but only if you will take time to look at it
Thanks

**Comment by tobernguyen** [comment]
perfect :+1:

**Comment by supairish** [comment]
+1 This worked for me also, thanks!

**Comment by tirdadc** [comment]
+1 so glad I found this, was wondering why the custom plugins / languages lists were being ignored. @galetahub please look at this.

**Comment by patricklindsay** [comment]
This workaround (& proposed solution) works great, except - instead of; 

```
config.assets.precompile += %w( ckeditor/my_config.js ckeditor/my_styles.js ckeditor/my_contents.css )
```
I must do;

```
config.assets.precompile += %w( ckeditor/my_config.js ckeditor/my_styles.js ckeditor/my_contents.css ckeditor/filebrowser/* ) 
```

Otherwise when attempting to use the filebrowser I get
```
Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( ckeditor/filebrowser/images/gal_del.png )` to `config/initializers/assets.rb` and restart your server
```

This is because when the [assets are precompiled](https://github.com/galetahub/ckeditor/blob/master/lib/ckeditor/utils.rb#L79-L86), the relative path is `vendor/assets/javascripts/ckeditor/plugins`  however the file browser is in `app/assets/javascripts/ckeditor` so it is not included even if you add it to the `Ckeditor.assets_plugins`

**Comment by scottolsen** [comment]
Is this still working for people? I've tried regular setup from readme and @randoum solution above and my precompile times are ~8 minutes. If I remove ckeditor completely they are ~40 seconds. 

Running:
ruby 2.3.0
rails 4.2.6
ckeditor 4.1.6

**Comment by supairish** [comment]
@scottolsen It still works for me.  This issue really has nothing to do with compile time though.  CKEditor is pretty huge, limit your included plugins and languages to slim it down.  Also compile time is greatly dependent on the machine doing the compiling.  For us, since our dev machines are far more powerful than our servers, we compile locally and rsync the assets to the server via capistrano.  But, 8 minutes does sound high to me, but I'm not 100% sure what would be considered "normal", as I'm working on a 32gb Quad core Mac Pro and our deploys take less than a minute >.>

**Comment by scottolsen** [comment]
@supairish I did limit to just english for the language and image for the plugin, but I think it's still being ignored, as I'm seeing everything still getting copied in the logs. Our qa env was on a t2.small and timeouts we happening on precompile. I'll bump it up and see if we can at least get things to deploy. Less than a minute would give me way more time to have a beer, I'll have to look in to the capistrano solution. Thanks!

**Comment by supairish** [comment]
@scottolsen Example of local compile https://github.com/TalkingQuickly/capistrano-cookbook/blob/master/lib/capistrano/cookbook/tasks/compile_assets_locally.cap

**Comment by scottolsen** [comment]
@supairish where are you deploying too? We're using codeship right now to run the build and auto deploy to elb so guessing we'd have to change up that workflow some.

**Comment by supairish** [comment]
@scottolsen Rackspace and AWS VPSes.  We use Codeship for CI but not for continuous deployments, we keep that manual
