### ISSUE TITLE
Toolbar Mini

### ISSUE THREAD

**Issue by napster3000** [galetahub/ckeditor#520]
<%= f.cktext_area :body, :class => 'form-control', rows: 15, :ckeditor => {
                  language: 'en', 
                  uiColor: '#9AB8F3', 
                  toolbar: 'Basic', 
                  autoGrow_onStartup: true
              }%> 

But I still show the Full Toolbar. I just want to switch from Full Toolbar to Basic/Standard Toolbar (http://ckeditor.com/download)

2) How to set AutoGrow enabled?

**Comment by katafrakt** [comment]
`toolbar: 'mini'` works for me (Rails 4.2.0)

**Comment by kyledecot** [comment]
@napster3000 Were you able to solve using the solution that @katafrakt proposed?
