### ISSUE TITLE
CKEditor with Rails 4.2

### ISSUE THREAD

**Issue by Sega100500** [galetahub/ckeditor#521]
The controller-level `respond_to' feature has been extracted to the`responders` gem. Add it to your Gemfile to continue using this feature:
gem 'responders', '~> 2.0'

May be worth adding dependence in ckeditor gem ? Or write this feature in documentation ?

**Comment by groe** [comment]
+1

**Comment by mscharley** [comment]
Yep, this just caught me as well.

**Comment by oguzbilgic** [comment]
+1

**Comment by JimmySticks2001** [comment]
Same here except it only appeared upon deployment.

**Comment by jaunkst** [comment]
Same here
+1

**Comment by jhubert** [comment]
Same here. :+1: 

It would be great to remove the responders requirement from the gem.

**Comment by jhubert** [comment]
Ok, apparently this is already done here: https://github.com/galetahub/ckeditor/commit/7f8b32b49d6b4b5cd587809bf62aa63c26346f6c and was merged in December.

It should be in the latest version of the gem. If you get this issue, try updating the gem to version 4.1.2:

```
gem 'ckeditor', '~> 4.1.2'
```
