### ISSUE TITLE
Invalid authenticity token for uploading images and files

### ISSUE THREAD

**Issue by xsannyx** [galetahub/ckeditor#525]
I updated the gem and started getting the error:
An ActionController::InvalidAuthenticityToken occurred in pictures#create:
ActionController::InvalidAuthenticityToken.

It threw the same error for uploading attached files. I fixed it by forking this gem and adding skip_before_action :verify_authenticity_token, only: :create to pictures_controller.rb and attachment_files_controller.rb

Is this a new bug in this gem or should I fix something else in my app?

**Comment by gambala** [comment]
Same error

**Comment by ykastelnik** [comment]
Up, same error here, any solution?
Thanks

**Comment by jseitel** [comment]
Repros for me too.
