### ISSUE TITLE
Img on heroku

### ISSUE THREAD

**Issue by alexand3rsc0tt** [galetahub/ckeditor#529]
I deployed my project on heroku and I can successfully create a post and send an image to the server but after a couple of hours the image(s) disappears from the server. Can someone help me with my situation.

**Comment by gingray** [comment]
have the same issue but probably it somehow connected with free plan on heroku itself.

**Comment by gingray** [comment]
@alexand3rsc0tt i figure out what wrong with heroku each time u deploy ur app all assets which not in source control will wipe out. Heroku recommend to store ur assets in other place like amazon s3 and so on.
