### ISSUE TITLE
ArgumentError in Ckeditor::PicturesController#create

### ISSUE THREAD

**Issue by OTSimple** [galetahub/ckeditor#535]
I'm trying to implement CKEditor in my Rails 3 App.

Everything works fine, except the upload with Paperclip.

```
Versions : 
gem ckeditor 4.1.1
Rails 3.1.3
Ruby 1.9.3
```

When I try to upload a picture I get this error : 

```
ArgumentError in Ckeditor::PicturesController#create
wrong number of arguments (1 for 0)

cocaine (0.2.1) lib/cocaine/command_line.rb:25:in `run'
ckeditor (4.1.1) lib/ckeditor/utils/content_type_detector.rb:33:in      
```

   `content_type_from_file_command'
    ckeditor (4.1.1) lib/ckeditor/utils/content_type_detector.rb:21:in`detect'
    ckeditor (4.1.1) lib/ckeditor/backend/paperclip.rb:47:in `extract_content_type'
    activesupport (3.1.3) lib/active_support/callbacks.rb:395:in`_run_validation_callbacks'
    activesupport (3.1.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
    activemodel (3.1.3) lib/active_model/validations/callbacks.rb:53:in`run_validations!'
    activemodel (3.1.3) lib/active_model/validations.rb:179:in `valid?'
    activerecord (3.1.3) lib/active_record/validations.rb:69:in`valid?'
    activerecord (3.1.3) lib/active_record/validations.rb:77:in `perform_validations'
    activerecord (3.1.3) lib/active_record/validations.rb:50:in`save'
    activerecord (3.1.3) lib/active_record/attribute_methods/dirty.rb:22:in `save'
    activerecord (3.1.3) lib/active_record/transactions.rb:241:in`block (2 levels) in save'
    activerecord (3.1.3) lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
    activerecord (3.1.3)    lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
    activerecord (3.1.3) lib/active_record/transactions.rb:208:in `transaction'
    activerecord (3.1.3) lib/active_record/transactions.rb:293:in`with_transaction_returning_status'
    activerecord (3.1.3) lib/active_record/transactions.rb:241:in `block in save'
    activerecord (3.1.3) lib/active_record/transactions.rb:252:in`rollback_active_record_state!'
    activerecord (3.1.3) lib/active_record/transactions.rb:240:in `save'
    ckeditor (4.1.1) app/controllers/ckeditor/application_controller.rb:17:in`respond_with_asset'
    ckeditor (4.1.1) app/controllers/ckeditor/pictures_controller.rb:12:in `create'
    actionpack (3.1.3) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
    actionpack (3.1.3) lib/abstract_controller/base.rb:167:in `process_action'
    actionpack (3.1.3) lib/action_controller/metal/rendering.rb:10:in`process_action'
    actionpack (3.1.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
    activesupport (3.1.3) lib/active_support/callbacks.rb:434:in`_run__915495955__process_action__229240880__callbacks'
    activesupport (3.1.3) lib/active_support/callbacks.rb:386:in `_run_process_action_callbacks'
    activesupport (3.1.3) lib/active_support/callbacks.rb:81:in`run_callbacks'
    actionpack (3.1.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
    actionpack (3.1.3) lib/action_controller/metal/rescue.rb:17:in`process_action'
    actionpack (3.1.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
    activesupport (3.1.3) lib/active_support/notifications.rb:53:in`block in instrument'
    activesupport (3.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'

In the logs : 

```
Started POST "/ckeditor/pictures?   CKEditor=editor&CKEditorFuncNum=1&langCode=fr&authenticity_token=fFb7az8X8TL5T1iEUEFKBpB6mpUdzFkhQ5sc9H0i2iY%3D" for 127.0.0.1 at 2015-02-03 09:59:57 +0100
  Processing by Ckeditor::PicturesController#create as HTML
  Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x43a1600 @original_filename="74H.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"upload\"; filename=\"74H.jpg\"\r\nContent-Type: image/jpeg\r\n", @tempfile=# <File:C:/Users/Greg/AppData/Local/Temp/RackMultipart20150203-6960-14wd49y>>,   "CKEditor"=>"editor", "CKEditorFuncNum"=>"1", "langCode"=>"fr",   "authenticity_token"=>"fFb7az8X8TL5T1iEUEFKBpB6mpUdzFkhQ5sc9H0i2iY="}
 [32mCommand[0m :: identify -format %wx%h  "C:/Users/Greg/AppData/Local/Temp/74H20150203-6960-1ch9gqk.jpg[0]"
 [32mCommand[0m :: convert "C:/Users/Greg/AppData/Local/Temp/74H20150203-6960-1ch9gqk.jpg[0]" -resize "800>" "C:/Users/Greg/AppData/Local/Temp/74H20150203-6960-1ch9gqk20150203-6960-1shdbpf"
   [32mCommand[0m :: identify -format %wx%h   "C:/Users/Greg/AppData/Local/Temp/74H20150203- 6960-1ch9gqk.jpg[0]"
```

        [32mCommand[0m :: convert  "C:/Users/Greg/AppData/Local/Temp/74H20150203-6960-1ch9gqk.jpg[0]" - resize "x100" -crop "118x100+7+0" +repage  "C:/Users/Greg/AppData/Local/Temp/74H20150203-6960-1ch9gqk20150203- 6960-1h2iczo"
        [1m[36mUser Load (0.0ms)[0m  [1mSELECT `users`.\* FROM `users`  WHERE `users`.`id` = 1    LIMIT 1[0m
        [1m[35m (0.0ms)[0m  BEGIN
        [1m[36m (0.0ms)[0m  [1mROLLBACK[0m
        Completed 500 Internal Server Error in 2212ms

```
 ArgumentError (wrong number of arguments (1 for 0)):


Rendered C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.0ms)
Rendered C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.0ms)
Rendered C:/Bitnami/rubystack-1.9.3-27/ruby/lib/ruby/gems/1.9.1/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (4.0ms)
```

Do you have an idea of solution ?
Thanks

**Comment by kyledecot** [comment]
Hi @OTSimple are you still experiencing this issue?
