### ISSUE TITLE
Looking for app/assets/images/ckeditor/config.js?

### ISSUE THREAD

**Issue by Netzone** [galetahub/ckeditor#537]
While trying to load ckeditor I'm getting a whole bunch of 404's saying http://localhost:3000/app/assets/images/CKEditor/config.js?t=EAPE 404 (Not Found)

That looks really odd because ordinarly there shouldn't be any js files there, and there isn't. I'm running Arch Linux and I've seen it work on windows with the same project.

**Comment by battlemidget** [comment]
Seeing this issue come up during production deploy

```
GET http://wakeforestmarket.org/assets/ckeditor/config.js [HTTP/1.1 404 Not Found 36ms]
GET http://wakeforestmarket.org/assets/ckeditor/lang/en.js [HTTP/1.1 404 Not Found 35ms]
TypeError: i[e] is undefined application-fc5e65997c276510a94c52627800f40e.js:7:9736
TypeError: i[e] is undefined
```

I setup a couple of path modifications:

```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  prepend_view_path "app/views/admin"
  prepend_view_path "app/views/#{Rails.application.config.market_theme}"
end
```

Ckeditor works fine during development environment.

**Comment by battlemidget** [comment]
@netzone Add

```
Rails.application.config.assets.precompile += %w( ckeditor/* )
```

To your `config/initializers/assets.rb`
