### ISSUE TITLE
Image upload error message for incorrect file extensions: "Data blank"

### ISSUE THREAD

**Issue by elainefang** [galetahub/ckeditor#540]
Using the latest version of the gem from Github, whenever a file with the wrong extension is uploaded through the image uploader, an error message pops up saying "Data blank," or something similar.

Is this error message not working: "{file} has invalid extension. Only {extensions} are allowed."?

**Comment by kyledecot** [comment]
Hi @ef718 Are you still experiencing this? I'm just coming onto the project and a lot has changed since Feb so I'm just checking.

**Comment by ef718** [comment]
Thanks for checking. Yes, this is still occurring.
