### ISSUE TITLE
unminified sources (if Rails.env.development?)

### ISSUE THREAD

**Issue by smcphill** [galetahub/ckeditor#544]
Debugging using this gem is a disheartening experience. Would it be possible to serve alternative unminified assets, preferably contingent on some environmental indicator?

Looks like [ckbuilder](https://github.com/ckeditor/ckbuilder) provides the ability to build unminified assets...

**Comment by kyledecot** [comment]
I think this could be a good addition. The asset pipeline would minify everything anyways so it would all end up the same in staging/production. Want to take a crack at it and issue a pull request @smcphill ?

**Comment by smcphill** [comment]
Since opening this issue, I've learned that CKEditor's custom [build process](https://github.com/ckeditor/ckbuilder) requires a java (and ant) to generate unminified sources, and no source maps are generated. https://github.com/ckeditor/ckeditor-releases/issues/11 touches on this. 

The best option I can think of is a rake task to retrieve and build unminified sources, possibly making use of git submodules to https://github.com/ckeditor/ckeditor-releases and https://github.com/ckeditor/ckbuilder - does that sound like something you'd be interested in?

**Comment by kyledecot** [comment]
@galetahub Thoughts?
