### ISSUE TITLE
JavaSctipt Function on "Send it to the Server"  button.

### ISSUE THREAD

**Issue by mailtoyogeshpatel** [galetahub/ckeditor#547]
In image Dialogue box on Click of "Send it to the Server" button i weant to call javaScript function wich checks uploaded file if image or not.
How to call javascript function on "Send it to the Server" and in which file i need to change.

**Comment by kyledecot** [comment]
@mailtoyogeshpatel This seems to be a javascript/CKEditor related issue and not specifically related to this rubygem. I'm going to close this but I would suggest you post this on StackOverflow
