### ISSUE TITLE
Maximal Image Dimension

### ISSUE THREAD

**Issue by fbrix** [galetahub/ckeditor#548]
Hello @galetahub ,

is it possible to config the imagesize for `:content` (without touching the model code itself) which is declared here:

```ruby
:styles => { :content => '800>', :thumb => '118x100#' }
```
https://github.com/galetahub/ckeditor/blob/6d8032b87595c3ffa8e9dfd7d86721ecdc53a3e3/lib/generators/ckeditor/templates/mongoid/paperclip/ckeditor/picture.rb#L5

I need the image in 900px but it is being resized to 800px because of this constraint.

Many thanks!

**Comment by kyledecot** [comment]
I suppose this could be added as a configurable setting in the initializer. If you want to take a crack at it and issue a pull request I'll certainly take a look
