### ISSUE TITLE
Bad asset url in production

### ISSUE THREAD

**Issue by Nekromancer** [galetahub/ckeditor#549]
I'm using ckeditor in active admin. In developer mode on my computer everything works fine, but after deploying on server i get an asset url problem. In logs error looks like that:

```
I, [2015-03-29T12:29:01.138857 #38839]  INFO -- : Started GET "/admin/consultations/skins/moono/editor_gecko.css?t=EAPE" for 83.5.116.29 at 2015-03-29 12:29:01 +0200
F, [2015-03-29T12:29:01.140375 #38839] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/admin/consultations/skins/moono/editor_gecko.css"):
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
```

**Comment by Nekromancer** [comment]
Anyone? I really need help asap

**Comment by FelAl** [comment]
I've  find the solution.
You need to add this line to application.html.erb
<script type="text/javascript">var CKEDITOR_BASEPATH = '/assets/ckeditor/';</script>

The ploblem is in url !!!/admin/consultations/!!!skins/moono/editor_gecko.css?t=EAPE
you need to define right direct path for /skins/moono/editor_gecko.css
