### ISSUE TITLE
Image upload fails on Centos 5 with file-4.17

### ISSUE THREAD

**Issue by jeremyclark** [galetahub/ckeditor#552]
Our production server runs on Centos5, which has an older version of the file utility. 

Recently, ckeditor started using this "file" command to detect the uploaded image's content type. However, it uses the argument --mime-type instead of --mime... which is available in newer versions of the file utility, but not the older ones.

We realized that Ckeditor image uploads started failing, but had to add error logging to the content type detection method's exception handler to see what was going wrong. We then realized this was the problem. 

Our workaround is to monkeypatch that content type detection method to use the --mime argument instead of the --mime-type. Maybe this will be useful for someone else in the same boat.

**Comment by kyledecot** [comment]
Hi @jeremyclark As CentOS 5 is quite old I'm afraid there isn't much we can do to address this. It seems like the monkey patch works well in your case so I'm going to go ahead and close this but feel free to reopen it if you need
