### ISSUE TITLE
Content display in weired format

### ISSUE THREAD

**Issue by mailtoyogeshpatel** [galetahub/ckeditor#555]
Add following source in CK Editor:
 "<p> </p> <div class="box" style="color:#ff0000;"><strong>Translations:</strong> Can you help translate this site into a foreign language ? Please email us with details if you can help.</div>"

It display in weired format. See the attached image
![ckeditor_content](https://cloud.githubusercontent.com/assets/11291299/7197761/7732ea02-e502-11e4-8b3c-dcb45787a7e6.jpg)

**Comment by mailtoyogeshpatel** [comment]
I think class="box" is creating problem

**Comment by kyledecot** [comment]
@mailtoyogeshpatel Is this something we need to look into or is this caused by custom styling in your app?
