### ISSUE TITLE
Multiple Editors on the same page

### ISSUE THREAD

**Issue by samcambridge** [galetahub/ckeditor#556]
Hey,

 Sorry if this is obvious but googles failed me and I'm not sure where else to turn.

I have 2 text editors on a page, I need them to have different tool bars, how can I go about doing this using this gem?

Cheers

**Comment by kyledecot** [comment]
Hi @samcambridge I'm going to close this as this isn't an bug/issue related to the gem but rather how to use the gem. I would suggest opening something on stackoverflow.com

**Comment by Lucasosf** [comment]
You can have 2 or more editors in the same page by having different ids for each one.
To have different toolbars, you just need add the config in the declaration method, like this:
```
<%= f.cktext_area :content, id: "first-editor", ckeditor: { toolbar: 'mini' } %>
<%= f.cktext_area :content, id: "second-editor-with-full-toolbar" %>
```
I hope this could help you or someone that has the same doubt.
