### ISSUE TITLE
Sprockets 3 Compatibility Issue

### ISSUE THREAD

**Issue by ayaman** [galetahub/ckeditor#558]
There seems to be a compatibility issue with Sprockets 3 that shows up only in production. After upgrading from Sprockets 2.12.3 to 3.0.1 I started getting these errors when trying to load CKEditor:
```
GET /assets/ckeditor/config.js?t=EAPE 404 (Not Found)
GET /assets/ckeditor/skins/moono/editor.css?t=EAPE
GET /assets/ckeditor/lang/en.js?t=EAPE
Uncaught TypeError: Cannot set property 'dir' of undefined
```
Downgrading to Sprockets 2.12.3 solved the issue.

**Comment by seanski** [comment]
I'm seeing this issue, too.  Besides downgrading Sprockets, any other ideas?

**Comment by seanski** [comment]
Never mind, it looks like it was fixed with https://github.com/galetahub/ckeditor/commit/82cb23e6872a49bf1b731c0cc3d2c8ae445c7506

Upgrading the gem fixed this issue for us.

**Comment by ayaman** [comment]
Yeah I guess that makes sense, I used the gem from RubyGems rather than GitHub so that's probably why I got the error.
