### ISSUE TITLE
rescue_from CanCan::AccessDenied

### ISSUE THREAD

**Issue by jgrannas** [galetahub/ckeditor#559]
When I try to use the Image uploader, and setup CKeditor with cancan following the readme directions, i am hitting AccessDenied

**ActionController::UrlGenerationError in Ckeditor::PicturesController#create**
**No route matches {:action=>"new", :controller=>"my_devise/sessions"}**

```
rescue_from CanCan::AccessDenied do |exception|
    store_location
    redirect_to new_user_session_path, alert: exception.message
  end
```

ckeditor.rb initializer

```
Ckeditor.setup do |config|
  config.authorize_with :cancan
  config.picture_model { Ckeditor::Picture }
  config.attachment_file_model { Ckeditor::AttachmentFile }
```

My AdminAbility.rb

```
class AdminAbility
  include CanCan::Ability

  def initialize(user)

    user ||= User.new #guest user (not logged in)

    cannot :manage, :all

    if user.roles.map(&:downcase).include?('admin')
      can :read, :all
      can :manage, :all
      can :access, :ckeditor 
      can [:read, :create, :destroy], Ckeditor::Picture
      can [:read, :create, :destroy], Ckeditor::AttachmentFile
    end   
  end
end
```

**Update: To fix this, I had to move all logic from AdminAbility.rb to Ability.rb**

**Comment by fran-worley** [comment]
Might also be worth changing `can :access, :ckeditor` to `can :manage, :ckeditor` as `:access` only seems to be used in the 2.0 branch which was never finished...

https://github.com/ryanb/cancan/wiki/Defining-Abilities
https://github.com/ryanb/cancan/wiki/CanCan-2.0

**Comment by philm** [comment]
FYI - if you've defined your abilities in another class, set the class name in config/initializers/ckeditor.rb:

```
config.authorize_with :cancan, AdminAbility
```
