### ISSUE TITLE
Support use of the CKEditor CDN

### ISSUE THREAD

**Issue by rdlugosz** [galetahub/ckeditor#563]
In lieu of adding all of the CKE assets to your application, it would be nice if there was a way to configure this gem such that all of the JS is expected to be found on the official CDN (http://cdn.ckeditor.com/).

**Comment by rdlugosz** [comment]
A few notes on this:

- Mostly works today if you *don't* include the directive to compile the assets in your `assets.rb` file and *don't* add the related require statement in your `application.js` file.
- Need to include a javascript tag for the CKE CDN (obviously)
- On the form where you load CKE, you'll need to specify a couple of the `config.js` options directly since the one from the CDN is being used (e.g., `filebrowserImageBrowseUrl: "/ckeditor/pictures"` and friends). This mostly matters if you want the file management and upload plugins to work correctly. _The "official CDN support" issue resolution would solve this in a more correct way as this method probably doesn't set things like the CSRF header correctly._
- You can prevent most of the assets from being built if you add the following to your `application.rb`:
```ruby
config.after_initialize do
  Rails.application.config.assets.precompile = Rails.application.config.assets.precompile - Ckeditor.assets
end
```
Code above thx to [this comment](https://github.com/galetahub/ckeditor/issues/307#issuecomment-47076464).

**Comment by jhubert** [comment]
Yeah, this would be handy. Thanks for the tips :+1:

**Comment by kartikluke** [comment]
@rdlugosz How would you add the config. I get an error the CKEDITOR is not defined.

**Comment by rdlugosz** [comment]
Sorry, tough to debug that error without seeing more of your app & what you're trying to do. Can you show us more info about what specifically triggers the error? Are you certain that you are loading the ckeditor from the CDN and that you aren't attempting to do anything with it until after it has been loaded?

**Comment by kyledecot** [comment]
@rdlugosz If you want to take a crack at implementing this I'd be interested in seeing it

**Comment by rdlugosz** [comment]
I'll take a look when I get some free time, thx!
