### ISSUE TITLE
not found (error to origin) in Image Upload too

### ISSUE THREAD

**Issue by mailtoyogeshpatel** [galetahub/ckeditor#566]
I am using CkEditor4.4.3.
 In OS X in Chrome browser in image upload tool, On "Send it to the Server"
 button getting error "not found (error to origin)"
 What could be the possible cause?

![not found error to origin](https://cloud.githubusercontent.com/assets/11291299/7467943/f9000396-f31f-11e4-888f-bd5f675689a1.png)

**Comment by kyledecot** [comment]
@mailtoyogeshpatel What does your rails server log say? Any errors?
