### ISSUE TITLE
Load javascript files only in admin pages

### ISSUE THREAD

**Issue by ricardocastaneda** [galetahub/ckeditor#567]
I intend to use CKeditor only for admin pages, ```//= require ckeditor/init``` loads it with all files. Is there a way how to generate those javascript files and include them separately?

**Comment by kyledecot** [comment]
I'm not positive but this should be possible. I'm going to close this as it's not a bug related to the gem itself but I would definitely post this question on StackOverflow (post a link to it for reference if you do).
