### ISSUE TITLE
Keep getting MIME type ('text/html') is not executable error

### ISSUE THREAD

**Issue by mdunbavan** [galetahub/ckeditor#571]
Hi,

When I go to edit a resource I get the above error for config.js and then when I go to view the resource I get it too. Also all my image uploads are broken urls when I go to view them in the actual post and when I go to the backend and edit the resource I click 'browser server' on image upload button and all images that were previously uploaded show as broken image links.

**error when editing a resource in console**
```
Refused to execute script from '/assets/ckeditor/config-65b33bedd052d521bd0b685fa5bb9800.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**when viewing the text area**
![screen shot 2015-05-27 at 14 09 57](https://cloud.githubusercontent.com/assets/671281/7836705/387a9b92-047a-11e5-8eed-24d13d8dac5b.png)

**when viewing file browser**
![screen shot 2015-05-27 at 14 10 48](https://cloud.githubusercontent.com/assets/671281/7836709/3e9f0f9e-047a-11e5-847a-a521eb82a444.png)

Can anyone think of why?

Cheers,
Mark

**Comment by kyledecot** [comment]
Hi @mdunbavan Are you getting this error only in production or in development as well?

**Comment by mdunbavan** [comment]
Hi @kyledecot I installed the most recently updated gem and it seemed to stop this from happening.

**Comment by kyledecot** [comment]
@mdunbavan Okay good to hear. I'm going to go ahead and close this then
