### ISSUE TITLE
ckeditor fails to initialize the second time a page is rendered via Turbolinks

### ISSUE THREAD

**Issue by mattbrictson** [galetahub/ckeditor#575]
When using Turbolinks, navigating away from a page that has a ckeditor textarea and then navigating back to that page results in ckeditor failing to render on the second visit.

Steps to reproduce:
1. Load a page that has a ckeditor textarea. (Works fine.)
2. Navigate to a different page using a Turbolinks link.
3. Navigate back to the original page in step 1 using a Turbolinks link.
4. The textarea renders as a plain textarea; ckeditor is not initialized.

This happens only with ckeditor gem 4.1.2. If I downgrade to 4.1.1, it works fine.

I'm using Rails 3.2.21. OS X Safari 8.0.6.

**Comment by mattbrictson** [comment]
The culprit is commit e9a1064a7451c07612048146ced5b2279448de57. If I revert this commit the bug is fixed.

**Comment by Sega100500** [comment]
@mattbrictson 
I have same problem. With ajax loading page. But in CKEditor 4.4.7 'replace' for already initialized dom-objects is error. Initialized dom-objects not deleted, but load different elements with same id - they not initialized again.
I do:
Before ajax load need delete ALL CKEDITOR.instances

**Comment by mattbrictson** [comment]
@Sega100500 Good point. I am actually using the ckeditor gem with a CDN-hosted version of the ckeditor JS, which is version 4.4.5. So disregard my solution of reverting e9a1064.

**Comment by alpracka** [comment]
+1

**Comment by henriquesacramento** [comment]
+1

**Comment by moeabdol** [comment]
@Sega100500 can you please shed some light on how you deleted all CKEDITOR instances before ajax load. Thanks.

**Comment by kyledecot** [comment]
@Sega100500 Would your solution fix this issue without breaking #471? If so you should do a pull request

**Comment by moeabdol** [comment]
@kyledecot have you been able to use the fix. I'm not sure exactly how to delete CKEditor instances before load. This issue originally is linked to turbolinks, and I don't want to opt-out turbolinks because it speeds up my app. 

In my javascript I tried

delete CKEDITOR;

and

CKEDITOR = null;

but with no use :(
I'd appreciate your help. Thanks.

**Comment by Sega100500** [comment]
Before, for exaple, loaded by ajax content put into some place: some_place.html(data)
Do this:

var _page_ajax_pre_load = function() {

    if (typeof jQuery !== 'undefined') {
      $(document).ready(function () {

        if (typeof CKEDITOR !== 'undefined') {
          for (var instanceName in CKEDITOR.instances) {
            if (typeof CKEDITOR.instances[instanceName] !== 'undefined') {
              CKEDITOR.instances[instanceName].destroy();
            }
          }
        }

      });
    }

 };

_page_ajax_pre_load();
some_place.html(data);

**Comment by moeabdol** [comment]
Thank you @Sega100500 :+1: 
I'm using Turbolinks and JQuery.Turbolinks gems. I inserted you code into my $(document).ready function and it works like a charm :)

$(document).ready(function() {
    if (typeof CKEDITOR !== 'undefined') {
          for (var instanceName in CKEDITOR.instances) {
            if (typeof CKEDITOR.instances[instanceName] !== 'undefined') {
              delete CKEDITOR.instances[instanceName];
            }
          }
        }
});

**Comment by davidgross** [comment]
We had this problem in our app, our solution was to add a CKEDITOR.replace('id_of_text_area') to our config.js
```
$(document).on('page:update', function(){
  CKEDITOR.replace('id_of_text_area')
});
```
Hope that helps.

**Comment by magicmarkker** [comment]
This solution of deleting the instances on ajaxComplete doesn't really work if you have editors in bootstrap modals with a remote form.

**Comment by kelso** [comment]
You can keep turbolinks enabled, just reinitialize ckeditor each time page is changed (turbolinks event):

Create custom app/javascripts/ckeditor/reinit.js:

    $(document).bind('page:change', function() {
      $('.ckeditor').each(function() {
        CKEDITOR.replace($(this).attr('id'));
      });
    });

And add class='ckeditor' to your <textarea>.
That's all.

**Comment by kelso** [comment]
You can keep turbolinks enabled, just reinitialize ckeditor each time page is changed (turbolinks event):

Create custom app/javascripts/ckeditor/reinit.js:

    $(document).bind('page:change', function() {
      $('.ckeditor').each(function() {
        CKEDITOR.replace($(this).attr('id'));
      });
    });

And add class='ckeditor' to your <textarea>.

That's all.

**Comment by Sega100500** [comment]
@kelso 
All fine, but I already wrote: "But in CKEditor 4.4.7 'replace' for already initialized dom-objects is error. Initialized dom-objects not deleted, but load different elements with same id - they not initialized again."

**Comment by samuelgiles** [comment]
This works for me, just destroying all CKEditor instances right before the next script is run:

```javascript
$(document).bind('page:before-unload', function() {
	if (typeof(CKEDITOR) != "undefined"){
		for(name in CKEDITOR.instances){
			CKEDITOR.instances[name].destroy()
		}
	}
});
```

**Comment by kelso** [comment]
@samuelgiles you're right, destroying ckeditor instances before page unload helps me avoid 'already initialized' ckeditor error. Thanks! Now it's complete.

**Comment by unfg** [comment]
I used the following to fix this bug:
```coffeescript
$(document).bind 'page:before-unload', ->
  if typeof(CKEDITOR) != "undefined"
    for name of CKEDITOR.instances
      if name?
        instance = CKEDITOR.instances[name]
        if instance? 
          $('#' + name).addClass('ckeditor-reinit')
          instance.destroy()

$(document).bind 'page:update', ->
  $('.ckeditor-reinit').each ->
    $(this).removeClass('ckeditor-reinit')
    CKEDITOR.replace($(this).attr('id'))
```

**Comment by ssoulless** [comment]
@samuelgiles your solution worked like a charm! Thanks

**Comment by NaiveCAI** [comment]
@magicmarkker Hi, so unlucky, I met the problem too, ckeditor failed to load on second time with bootstrap modal. Have you solved the problem, may i ask? 

THX.

**Comment by CedricLor** [comment]
The fix proposed by @samuelgiles worked for me, but I have to pass a true parameter to the destroy method call with version: "4.5.7", revision: "e98277f".

    $(document).bind('page:before-unload', function() {
        if (typeof(CKEDITOR) != "undefined"){
            for(name in CKEDITOR.instances){
                CKEDITOR.instances[name].destroy(true);
            }
        }
    });

**Comment by rhugo** [comment]
@NaiveCAI Did you find a solution? I have the same problem ...

**Comment by gambala** [comment]
Thanks, guys, this is worked solution fo me (turbolinks 5):

```
$(document).bind 'turbolinks:before-cache', ->
  return unless typeof(CKEDITOR) != 'undefined'
  for name in CKEDITOR.instances
    CKEDITOR.instances[name].destroy() if name?

$(document).bind 'turbolinks:load', ->
  $('.ckeditor').each ->
    CKEDITOR.replace($(this).attr('id'))
```

**Comment by psnfrench** [comment]
If you are using a bootstrap modal, you can destroy the instances on the modal hide event, so they are correctly initialized next time:

`$('#yourbootstrap_modal').on('hide.bs.modal', function (e) {
  if (typeof(CKEDITOR) != "undefined"){
    for(name in CKEDITOR.instances){
      CKEDITOR.instances[name].destroy()
    }
  }
});`

**Comment by connecttosunil** [comment]
dddd
