### ISSUE TITLE
Loading an Image takes 1 minute

### ISSUE THREAD

**Issue by aaronvetter** [galetahub/ckeditor#576]
I'm using ckeditor with ActiveRecords and paperclip and even though uploading an image takes less than a second, loading it again takes exactly one minute for a 140kB image. ![screenshot](http://i.imgur.com/Q3FONNj.png)

Sadly, GET requests to /ckeditor are not logged in the command line, so I have no idea where I should look for the error. If anyone has an idea where it might be, I would be glad to provide logs or files.

**Comment by kyledecot** [comment]
Does this happen both in production mode as well as development? Is it consistently slow?

**Comment by aaronvetter** [comment]
Well, after my computer crashed and I reinstalled everything including windows, everything worked again :)
Still somewhat strange that this happened in the first place, but I hope the error was on my part somehow.
