### ISSUE TITLE
precompile slow

### ISSUE THREAD

**Issue by acesuares** [galetahub/ckeditor#578]
Dear,

Lately, precompiling assets is terribly slow. I can't put my finger on it. I am using rails 3.2.21 and the latest gem. 

Precompiling in development is fast! But in production slow.

When I precompile locally - that is to say, the precompile is local but the RAILS_ENV is production, it is also terribly slow.

Precompiling in production takes more then 20 minutes.
In application.js I have
/= require 'ckeditor/init'

Any ideas?\

**Comment by acesuares** [comment]
```` executing "cd -- /var/www/ror/BooksBackend/releases/20150615172438 && RAILS_ENV=production RAILS_GROUPS=assets bundle exec rake assets:precompile"
    servers: ["ror.suares.com"]
    [ror.suares.com] executing command
    command finished in 685449ms ````

**Comment by kyledecot** [comment]
I'm having the same issue #573

**Comment by kyledecot** [comment]
I looks like this is where the bulk of the time is spent:

https://github.com/galetahub/ckeditor/blob/289251c32cd3db9c908bac75678f58f95258ea97/lib/tasks/ckeditor.rake

**Comment by acesuares** [comment]
with 
config.assets.compress = false
config.assets.compile = false
config.assets.digest = false

->     command finished in 20.084ms

config.assets.compress = true
config.assets.compile = false
config.assets.digest = false

->    command finished in 344.198ms

config.assets.compress = false
config.assets.compile = false
config.assets.digest = true

->    command finished in 37712ms

**Comment by acesuares** [comment]
I switched to https://github.com/tsechingho/ckeditor-rails but had the same slow precompile times in production, and on top of that, ckeditor works in development but not in produdction.

https://github.com/galetahub/ckeditor/issues/573
https://github.com/galetahub/ckeditor/issues/579

**Comment by acesuares** [comment]
https://github.com/galetahub/ckeditor/issues/579 is now solved, but precompile is still extremely slow.

**Comment by MarcusSky** [comment]
@acesuares I think I've found the solution.
_I'm assuming you're using Uglifier in production_

The problem is that the `CKEditor` source code (also `jquery` and others) are __already__ minified. So when you deploy it to Heroku, it tries to minify the already minified files, thus taking a long time.
Referencing issue: https://github.com/mishoo/UglifyJS2/issues/321

My solution:
```ruby
# production.rb 
config.assets.js_compressor = Uglifier.new(compress: { unused: false })
```

References:
- https://github.com/lautis/uglifier/blob/master/lib/uglifier.rb#L58
- https://github.com/mishoo/UglifyJS2/issues/321#issuecomment-26832839

Let me know if that helps!

**Comment by edudepetris** [comment]
@MarcusSky I have the same problem that @acesuares and I tried your solution.
This works for me!. I reduce the precompilation time from `392.86s` to `75.95s`

Thanks!

**Comment by hernanvicente** [comment]
@MarcusSky Your solution works like a charm, thanks for sharing!

**Comment by tkaboris** [comment]
So you mean to move uglifer gem to production group?

**Comment by edudepetris** [comment]
@tkaboris  did you put `require 'uglifier'` in top of `production.rb` ?

**Comment by acesuares** [comment]
This hasn't worked for me, but I need to investigate further.

**Comment by acesuares** [comment]
Can be closed.
