### ISSUE TITLE
SOLVED: TypeError: n[e] is undefined in production but not in development

### ISSUE THREAD

**Issue by acesuares** [galetahub/ckeditor#579]
I am hitting the following error in production:

`TypeError: n[e] is undefined`

... but not in development

**Comment by kyledecot** [comment]
@acesuares Are you able to make a small demo app that illustrates the issue and post it here on github?

**Comment by acesuares** [comment]
kyledecot I thought I had answered this but apparently not.

You can reproduce by installing the inline_forms example app, in one of two ways:


    gem install inline_forms
    inline_forms create MyApp -d sqlite --example
    RAILS_ENV=production RAILS_GROUPS=assets bundle exec rake assets:precompile

Be sure to put 

    config.assets.initialize_on_precompile = false

in config/application.rb

Or this way: 
Download https://github.com/acesuares/inline_forms/raw/master/lib/vagrant/vagrantbox-inline_forms.zip and follow instructions here: https://github.com/acesuares/inline_forms#build-a-vagrant-virtualbox-box-for-easier-development

I swapped galetahub/ckeditor for tsechingho/ckeditor-rails but ran in to the same problems!

**Comment by acesuares** [comment]
This error was caused by missing language files! 

in config/initializers/ckeditor.rb

I changed 

    # By default: nil (no limit)
    # config.assets_languages = ['en', 'uk']

to 

    # By default: nil (no limit)
    config.assets_languages = ['en', 'nl']

I assumed the default was ALL language files. However, I didn't find ANY language file in production! After the change above, the directory 

    assets/ckeditor/lang

suddenly appeared.

@galetahub would you close this thread unless this is a bug?
