### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by TanakaKousuke** [galetahub/ckeditor#581]
any solutions to solve this typeerror?
only googlechrome and not other browsers.

Uncaught TypeError: Cannot read property 'isContextFor' of null

GoogleChrome（43.0.2357.130 (64-bit)）
(1)tyepe some texit 
(2)Select All(CTRL+A)
(3)click anywhere in text
(4)enter
(5)typeerror will come up

not big deal but someone tell me why?

![2015-06-24 14 07 16](https://cloud.githubusercontent.com/assets/11862731/8323059/40b61096-1a7a-11e5-8099-28d71f98a9b9.png)

**Comment by kyledecot** [comment]
This looks like you're using just plain ol' CKEditor and not using this gem so I'm going to go ahead and close this but I encourage you to post this on StackOverflow.
