### ISSUE TITLE
Align text buttons doesn't show up in the toolbar 

### ISSUE THREAD

**Issue by medBouzid** [galetahub/ckeditor#582]
I am using Rails 4.2.2 and  I noticed that some toolbar buttons won't show up like 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock', 'BulletedList' ....

in the following example, all things are fine except (Justify buttons) 

    config.toolbar = [
        ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
        ['Font', 'FontSize','superlink'],
        ['TextColor', 'BGColor'],
        '/',
        [ 'Bold', 'Italic', 'Underline', 'Strike' ],
        [ 'Undo', 'Redo' ],
        ['Link', 'Unlink']
    ];

Is this a bug ?

UPDATE -  I tested the gem with Rails 4.2.0 and the toolbar show all buttons with no problem, so maybe there is a bug with 4.2.2 version

**Comment by SakshiParakh** [comment]
Current setup: 
Rails 4.2.3
ruby version 2.2.2
CKEDITOR version 4.5.5
gem version 4.1.5

```js
CKEDITOR.editorConfig = function (config) {
  config.toolbar = [ 
    ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
    ['Font', 'FontSize','superlink'],
    ['TextColor', 'BGColor'],
      '/',
      [ 'Bold', 'Italic', 'Underline', 'Strike' ],
        [ 'Undo', 'Redo' ],
        ['Link', 'Unlink']
  ];  
}
```
I am unable to reproduce this issue and its perfectly working for me
![ckeditor_issue](https://cloud.githubusercontent.com/assets/13197140/11932328/afd475a2-a81a-11e5-8fe2-5f96e85fd2d6.png)

**Comment by medBouzid** [comment]
@SakshiParakh yeah it was an old issue, the problem is that I was using ckeditor as inline editor and applying it to a <p> tag; it should be applied to div tag, it doesn't work by applying ckeditor to a p tag itself. I forgot to close this, however actually I am using my own home created editor :) thanks

**Comment by andreleoni** [comment]
- 

- [ ] 

- [ ] 

> 

>
