### ISSUE TITLE
CKEditor doesn't work on phones

### ISSUE THREAD

**Issue by moeabdol** [galetahub/ckeditor#585]
I have tested this on my Galaxy S4. It seems that  CKEditor doesn't work on phones. It works fine on tablets and pcs. I wonder if anyone have faced a similar issue, or is this is the expected behaviour for CKEditor on small devices?

**Comment by kyledecot** [comment]
@moeabdol This is more of a question for for CKEditor itself and not this rubygem. I'm going to close this but I suggest you post something on their forum
