### ISSUE TITLE
Unable to prevent assets from precompiling

### ISSUE THREAD

**Issue by kartikluke** [galetahub/ckeditor#586]
I'm storing all the ckeditor assets in the public folder to avoid some of the issues present on the repo. But the assets of the gem are still being compiled. Even though I did:

```
#assets.rb
Rails.application.config.assets.precompile -= Ckeditor.assets

#ckeditor.rb
Ckeditor.setup do |config|
  config.assets_languages = []
  config.assets_plugins = []
end
```

**Comment by wildjcrt** [comment]
+1
same issue…

**Comment by mehanoid** [comment]
Have you added "Rails.application.config.assets.precompile += %w( ckeditor/* )" anywhere to initializers as suggested in readme? Maybe you need to remove it?

**Comment by joker-777** [comment]
Happens to me too.

**Comment by tirdadc** [comment]
See https://github.com/galetahub/ckeditor/issues/519

Basically those initializer config settings are ignored right now when you have the precompile line, this is an unresolved bug.
