### ISSUE TITLE
using AWS s3 for upload files

### ISSUE THREAD

**Issue by ccfiel** [galetahub/ckeditor#591]
I have tried to used s3 in uploading files. The file was successfully uploaded in the s3 bucket but the link that the ckeditor is not correct. 
ckeditor url is this
https://s3.amazonaws.com/tinda/var/app/current/public/ckeditor_assets/pictures/6/content_untitled.png
but it should be 
https://tinda.s3.amazonaws.com/var/app/current/public/ckeditor_assets/pictures/6/content_untitled.png

any ideas?

**Comment by cytomich** [comment]
@ccfiel which gem you use for store files? paperclip, carrierwave or dragonfly?
Maybe problem in asset model options?

**Comment by ccfiel** [comment]
@cytomich Solve the problem. You are right. I just change the attachment_file and picture model options.

**Comment by bo-oz** [comment]
Could you share how you fixed this? I have the same issue with CKEditor & Paperclip.

**Comment by Duleja** [comment]
Try this for Picture model:

has_attached_file :data,
    :url => ":s3_alias_url",
    :path => 'ckeditor/pictures/:id/:style_:basename.:extension',
    :styles => { content: '800>', thumb: '118x100#' },
    :s3_host_alias => "your CloudFront domain"

For AttachmentFile.rb do the same just change your path and remove styles options...
