### ISSUE TITLE
Uncaught TypeError: Cannot set property 'dir' of undefined

### ISSUE THREAD

**Issue by Mithul** [galetahub/ckeditor#593]
Getting the above error in production and development. ckeditor 4.1.2 and rails 4.2.0.

**Comment by wildjcrt** [comment]
Did you upgrade ckeditor gem? If yes, you can try to check out the ckeditor.js your load is 4.1.2 first.
You can see it on Network tab in Chrome Inspector.

**Comment by adrianoresende** [comment]
I have this error in production only but development is fine.
Someone know to solve?
```
GEM Version: 4.5.10
Rails: 4.2.6
Ruby: 2.3
```

**Comment by PragmaticEd** [comment]
This worked for me: https://github.com/galetahub/ckeditor/issues/481#issuecomment-55079833
