### ISSUE TITLE
How to configure absolute urls for images

### ISSUE THREAD

**Issue by adamakhtar** [galetahub/ckeditor#595]
Hello,

By default CKEditor inserts images with relative paths for the urls. I need absolute urls.

The original CKEditor docs state a config option called baseHref. 

I tried to set that via 

``` ruby
# in app/assets/javascripts/ckeditor/config.js

config.baseHref = "http://mydomain.com" 
```

which didn't seem to do anything.

Perhaps the gem version requires a different approach but I coudn't see it mentioned anywhere.

I'm using Carrierwave

**Comment by robodisco** [comment]
I have just realised I have been looking in the wrong direction.

According to the source code the url used ultimately comes from Picture#url_content. It's called in the picture picker which is presented after clicking "browse server". 

https://github.com/galetahub/ckeditor/blob/master/app/views/ckeditor/shared/_asset.html.erb
```html
<%= content_tag(:div, :id => dom_id(asset), :class => "gal-item", :"data-url" => image_path(asset.url_content)) do %>
...
```

So in picture.rb I altered the url_content method like so

```ruby
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    "http://#{ENV['app_domain']}#{url(:content)}"
  end
end
```
And it seems to work. 

*If this sounds ok I can update the Readme*.
