### ISSUE TITLE
Is this only for forms?

### ISSUE THREAD

**Issue by simkessy** [galetahub/ckeditor#601]
The readme seems to only address how to make this work with forms. I'm trying to edit an about us page that's pure html and wondering if ckeditor can be used for that?

**Comment by SakshiParakh** [comment]
I am not sure what your exact requirement is but if you want to use CKEditor with pure html then do the following: 
1) Add a textarea tag on you page and give it an id.
2) ```CKEDITOR.replace("test1")``` assuming 'test1' is your textarea id.

But if your requirement is this small then I suggest please don’t use this gem as it is an overkill. Compile a custom CKEditor build from [here](http://ckeditor.com/download) as per your requirement and add it to the asset pipeline
