### ISSUE TITLE
Could not find generator (Rails 3.2)

### ISSUE THREAD

**Issue by activestylus** [galetahub/ckeditor#602]
I've added ckeditor to my gemfile, bundled and run the following generator

```
bundle exec rails generate ckeditor:install --orm=active_record --backend=carrierwave
```

The console pauses for a moment until spitting out

```
Could not find generator ckeditor:install.
```

Am I missing something?

**Comment by elkhan** [comment]
In case someone comes across this - just stop spring <spring stop> and run rails g ... again. Should work.
