### ISSUE TITLE
Pundit policies not working

### ISSUE THREAD

**Issue by edjarris** [galetahub/ckeditor#609]
Recently I installed ckeditors gem version 4.1.3 and every things works ok. 
Now I add pundit gem version 1.0.1. To ensure all my application are using policies I add to my controller:

``` ruby
class ApplicationController < ActionController::Base
  include Pundit  
  after_action :verify_authorized

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized(exception)
   policy_name = exception.policy.class.to_s.underscore

   flash[:error] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
   redirect_to(request.referrer || root_path)
 end
end
```

After that I followed ckeditor pundit installation section from readme:

``` ruby
#config/initializers/ckeditor.rb
Ckeditor.setup do |config|
  config.authorize_with :pundit
end
```

and generate the policy files for model Picture and AttachmentFile

``` shell
$ rails g ckeditor:pundit_policy
```

When I tray to view images from server using chkeditor, pundit throws:

```
Pundit::AuthorizationNotPerformedError in Ckeditor::PicturesController#index
```

It seems picture_policy is not load. Reading some issues from pundit I thing after version 0.3.0 is not possible to use namespaced policies, so I thing that is what is going on.
In the next issue from pundit (https://github.com/elabs/pundit/issues/178) author mentioned that he doesn't like to incorporate this feature for some reason, so if you want to use you have to install from  branch called "namespaces", but is not maintained from a long time ago.

After read more about pundit documentation I tried to move picture_policy.rb one level up under policies folder and removed namespace from class:

``` ruby
class PicturePolicy 
  attr_reader :user, :picture

  def initialize(user, picture)
    @user = user
    @picture = picture
  end

  def index?
    user.present?
  end

  def create?
    user.present?
  end

  def destroy?
    picture.assetable_id == user.id
  end
end
```

Then I tried manually specifying policy usgin self.policy_class method: 

``` ruby
# app/models/chkeditor/picture.rb:
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def self.policy_class
    PicturePolicy
  end
end
```

After this changes when I test it again ckeditor throw me this exception:

```
Unable to autoload constant Ckeditor::PicturePolicy, expected app/policies/ckeditor/picture_policy.rb to define it
```

At this point I'm lost, so any ideas are welcome :)

Thanks in advance,

**Comment by Systho** [comment]
From the error message it looks like you just forgot to put your policy in the correct namespace.
````
class PicturePolicy 
...
````

should be 
````
module Ckeditor
   class PicturePolicy 
...
```

**Comment by edjarris** [comment]
Ty Systho, I followed your reply but ckeditor throw me same exception:
```
LoadError in Ckeditor::PicturesController#index
Unable to autoload constant PicturePolicy, expected /app/policies/picture_policy.rb to define it
```

**Comment by Systho** [comment]
Actually it is not the same error.

The first error was complaining about the file `app/policies/ckeditor/picture_policy.rb` not defining `Ckeditor::PicturePolicy`, the second error is complaining about the file `app/policies/picture_policy.rb` not defining `PicturePolicy`.

Those two errors seems to demonstrate that you have a mismatch between the folder where you place your policy and the module of your policy. Since your policy is probably only needed by your controller and it looks like you are using a namespace-aware policy finder , I would suggest you to keep your file under the `ckeditor` folder and your class in the `Ckeditor` module

**Comment by edjarris** [comment]
Ok, I moved PicturePolicy inside ckeditor folder but then pundit generate the exception that the policy is not implemented:
```
Pundit::AuthorizationNotPerformedError in Ckeditor::PicturesController#index
```
I think that is because when pundit remove the support to namespaced policies doesn't autload policies inside folders, so inspired from a replay in https://github.com/elabs/pundit/issues/178 from onemanstartup I add next code to ApplicationPolicy.rb to try to force load classes inside ckeditor folder:

```ruby 
class ApplicationPolicy
  extend ActiveSupport::Autoload
  autoload :Ckeditor
...
end
```
but still throw 
```
Pundit::AuthorizationNotPerformedError in Ckeditor::PicturesController#index
```

**Comment by Systho** [comment]
`Pundit::AuthorizationNotPerformedError` is an error you receive from an `after_action` because you did not call pundit's `authorize()` method. 

Nothing related to autoloading.

I don't know how this snippet works

```
Ckeditor.setup do |config|
  config.authorize_with :pundit
end
```

but I would suggest it doesn't call Pundit controllers' `authorize()` helper which is responsible to set the flag telling pundit authorization has been performed and therefore you trigger the `AuthorizationNotPerformedError ` error in the after_action `:verify_authorized` hook

**Comment by Systho** [comment]
As you can see here, the Ckeditor hook calls directly the policy and not the helper method.

https://github.com/galetahub/ckeditor/blob/master/lib/ckeditor/hooks/pundit.rb

Easiest fix is to drop your `after_action` verification step.
Best fix is to propose a PR to this project to allow using Pundit's `authorize()` controller method

**Comment by moeabdol** [comment]
@Systho I followed your instruction and opened the gem then located pundit.rb; however, I'm not really sure where to drop the after_action. Can you please let us know. Thanks.

**Comment by moeabdol** [comment]
I ended up just skipping pundit's authorization for the entire ckeditor gem.

In the gem's application_controller I just:
`skip_before_action :verify_authorized`

**Comment by Systho** [comment]
Dropping the after action has nothing to do with editing the gem code. I meant deleting your after action , which is only a verification step. 

Editing a gem code is always a bad idea, one of the worse you can have.

You might however reopen the clas in an initializer and rewrite parts of the class.
But the best idea would be to make a PR here with a test.

In this case, I think the best idea would be for the pundit adapter to delegate to the controller's authorize method. Only that method setup the instance variable being checked in the after_action hook.

**Comment by moeabdol** [comment]
Thanks @Systho :+1:

**Comment by mgtf** [comment]
This works :
`skip_after_action :verify_authorized, if: lambda { controller_name == :ckeditor }`

**Comment by rpbaptist** [comment]
mgtf's solution did not work for me. `controller_name` was `pictures` or 'attachments'.

I had to resort to this:

```ruby
  skip_after_action :verify_authorized, if: :ckeditor_controller?

  private

  def ckeditor_controller?
    self.class.to_s.starts_with?("Ckeditor::")
  end
```

I submitted a PR, so hopefully we can stop skipping this check for Ckeditor.
