### ISSUE TITLE
Customize /ckeditor route in the intializer for an engine mount

### ISSUE THREAD

**Issue by cdesch** [galetahub/ckeditor#610]
How can I change the ckeditor mounted route in the initializer from `/ckeditor` to something else?

Currently my issue is that I have ckeditor in an engine. Since the engine has the routes isolated, the route to ckeditor becomes `/portfolio/ckeditor` and while ckeditor continues to look for it's route at `/ckeditor`

I posted the [question in stackoverflow](http://stackoverflow.com/questions/32813286/rails-parent-app-route-to-engine-route-and-children) on how to customize these routes through the parent app, although I was still wondering if there was a way to do it through ckeditor which was easier.

**Comment by cdesch** [comment]
I tried changing the `basepath` as shown in the docs, although that does not seem to have an effect


        <%
	  base_path = ''
	  if ENV['PROJECT'] =~ /editor/i
	    base_path << "/#{Rails.root.basename.to_s}/"
	  end
	  base_path << Rails.application.config.assets.prefix
	  base_path << '/ckeditor/'
	%>
	var CKEDITOR_BASEPATH = '<%= base_path %>';


Should I be including that in the engine or the app?

**Comment by patricklindsay** [comment]
To override the default CKEditor routes create a [config.js](https://github.com/galetahub/ckeditor/blob/master/app/assets/javascripts/ckeditor/config.js) file within the host application.

```
# in app/assets/javascripts/ckeditor/config.js

CKEDITOR.editorConfig = function( config )
{
  /* Filebrowser routes */
  // The location of an external file browser, that should be launched when "Browse Server" button is pressed.
  config.filebrowserBrowseUrl = "/some_path/ckeditor/attachment_files";

  // The location of an external file browser, that should be launched when "Browse Server" button is pressed in the Flash dialog.
  config.filebrowserFlashBrowseUrl = "/some_path/ckeditor/attachment_files";

  // The location of a script that handles file uploads in the Flash dialog.
  config.filebrowserFlashUploadUrl = "/some_path/ckeditor/attachment_files";

  // The location of an external file browser, that should be launched when "Browse Server" button is pressed in the Link tab of Image dialog.
  config.filebrowserImageBrowseLinkUrl = "/some_path/ckeditor/pictures";

  // The location of an external file browser, that should be launched when "Browse Server" button is pressed in the Image dialog.
  config.filebrowserImageBrowseUrl = "/some_path/ckeditor/pictures";

  // The location of a script that handles file uploads in the Image dialog.
  config.filebrowserImageUploadUrl = "/some_path/ckeditor/pictures";

  // The location of a script that handles file uploads.
  config.filebrowserUploadUrl = "/some_path/ckeditor/attachment_files";
```
