### ISSUE TITLE
RubyGems 4.1.3 version does not work for refile

### ISSUE THREAD

**Issue by elitwin** [galetahub/ckeditor#611]
Version 4.1.3 on RubyGems doesn't support refile. However, your master branch (still at 4.1.3) does support it.

Do you have a timeframe for pushing the latest version that supports refile up to RubyGems?

**Comment by danieldraper** [comment]
Any update on when the latest will be published to RubyGems?

**Comment by elitwin** [comment]
4.1.4 was just pushed up to RubyGems today.
