### ISSUE TITLE
Pundit scopes

### ISSUE THREAD

**Issue by danieldraper** [galetahub/ckeditor#612]
Please close/correct me if I am wrong.

When using Pundit and generating the policies they specify an index method like below:

```
def index?
  user.present?
end
```

However this does not scope the resources. Pundit offers Scopes https://github.com/elabs/pundit#scopes which don't appear to be supported with CKEditor. Happy to create a PR to resolve this if I am missing something.

If you were to access the model name for example `picture` in the `index?` method it is just a reference to the class `Picture`. I created a less than ideal and dirty hack to get scopes working.

```
class Scope < Struct.new(:user, :scope)
  def resolve
    scope.where(assetable_id: user.id)
  end
end
```

and then in the controller called `policy_scope` in the `index` method.

```
def index
    @pictures = policy_scope(Ckeditor::Picture)
    ...
end
```

Thoughts /  recommendations / better solutions / something I'm missing?

**Comment by sekrett** [comment]
@danieldraper Please tell me what is the controller name, where you added `policy_scope`.

Of course `def index?` does not limit the resources loaded.
