### ISSUE TITLE
Production (Rails 3.2.12, cketidor 4.1.4): undefined method `skip_before_action' for Ckeditor::AttachmentFilesController:Class (NoMethodError)

### ISSUE THREAD

**Issue by Roko131** [galetahub/ckeditor#615]
Rails 3.2.12, ckeditor 4.1.4 (both paperclip 3.5.2 and 4.3.0)
Hello, Yesterday 4.1.4 was just pushed up to RubyGems.
(Had no problem with 4.1.1)

Production (Heroku) envoirment failed to run, In my local it does work (though I use windows)
Here are the production logs:

/app/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.1.4/app/controllers/ckeditor/attachment_files_controller.rb:2:in `<class:AttachmentFilesController>': undefined method`skip_before_action' for Ckeditor::AttachmentFilesController:Class (NoMethodError)
from /app/vendor/bundle/ruby/2.0.0/gems/ckeditor-4.1.4/app/controllers/ckeditor/attachment_files_controller.rb:1:in `<top (required)>'
from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`block in require'
from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in`require'
from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:359:in `require_or_load'
from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:225:in`require_dependency'
from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:313:in `depend_on'
from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in`load_dependency'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/engine.rb:438:in `block in eager_load!'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/engine.rb:436:in`eager_load!'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/engine.rb:436:in `each'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/application/railties.rb:8:in`each'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/application/railties.rb:8:in `all'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/engine.rb:438:in`each'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/engine.rb:434:in `eager_load!'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/engine.rb:439:in`block (2 levels) in eager_load!'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/initializable.rb:30:in `instance_exec'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/initializable.rb:55:in`block in run_initializers'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `each'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/application.rb:136:in`initialize!'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/initializable.rb:54:in `run_initializers'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/application/finisher.rb:53:in`block in module:Finisher'
from /app/config/environment.rb:5:in `<top (required)>'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/initializable.rb:30:in`run'
from /app/vendor/bundle/ruby/2.0.0/gems/railties-3.2.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
from config.ru:3:in`require'
from config.ru:3:in `block in <main>'
from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in`instance_eval'
from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
from config.ru:1:in`new'
from config.ru:1:in `<main>'
from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in`eval'
from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/controllers/controller.rb:72:in`start'
from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/runner.rb:200:in`run_command'
from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.3/bin/thin:6:in`<top (required)>'
from /app/vendor/bundle/ruby/2.0.0/bin/thin:23:in `<main>'
from /app/vendor/bundle/ruby/2.0.0/bin/thin:23:in`load'

**Comment by davidgf** [comment]
I'm facing the same problem with Rails 3.2.16 and ckeditor 4.1.2, also in Heroku.

**Comment by Sega100500** [comment]
Same problem with Rails 3.2.22 + Ckeditor 4.1.4
paperclip 4.3.1

**Comment by sergiogomez** [comment]
I have the same error, but I've seen this PR this solving it. New release? ;)

https://github.com/galetahub/ckeditor/pull/620

**Comment by batamire** [comment]
+1

**Comment by Thranriel** [comment]
Also have this issue with 4.1.4 + Rails 3.2.22.

Using 4.1.1 until it is fixed.

**Comment by leongg** [comment]
+1 rails 3.2.3

**Comment by classtechnologysolutions** [comment]
+1 rails 3.2.22.

Using 4.1.1 until fixed too.

**Comment by kshnurov** [comment]
+1
It is fixed in master, @galetahub are you gonna release a version?

**Comment by durrantm** [comment]
Also facing this with rails 3.2.22 today

**Comment by Sega100500** [comment]
Since 4.1.5 again all work!
Many thanks!
