### ISSUE TITLE
Custom config.js causes issues

### ISSUE THREAD

**Issue by ollpu** [galetahub/ckeditor#622]
When I add the file `config.js` in `app/assets/javascripts/ckeditor`, and populate it, I get an error in the Firefox console:

```
ReferenceError: CKEDITOR is not defined
```

The error is caused by the default config.js file located in `[server]/assets/ckeditor/config.self-[uid].js?body=1`.
With the custom `config.js`, CKEditor is also slower to open. I found out that it only loads up after the `setTimeout` below is executed.

```
<script>
//<![CDATA[
(function() { if (typeof CKEDITOR != 'undefined') { if (CKEDITOR.instances['page_content'] == undefined) { CKEDITOR.replace('page_content'); } } else { setTimeout(arguments.callee, 50); } })();
//]]>
</script>
```

All of the above issues do not occur if I remove my custom `config.js`.

**Comment by vemv** [comment]
Do you have this in your `application.js`?

//= require ckeditor/init

**Comment by ollpu** [comment]
Yes, this is in my `application.js`.

**Comment by quolpr** [comment]
`//= require ckeditor/init` - it must be before `//= require ckeditor/config`
