### ISSUE TITLE
how to add enable WordCount-Plugin

### ISSUE THREAD

**Issue by ducnguyenhuy** [galetahub/ckeditor#623]
I want to enable this plugin https://github.com/w8tcha/CKEditor-WordCount-Plugin. Could you please tell me how to do that. 

Thanks.

**Comment by adityashedge** [comment]
setup CKEditor(refer README on instructions)
add the word count plugin to the plugins directory of CKEditor, in 'app/assets/javascripts' folder (app/assets/javascripts/ckeditor/plugins/wordcount/).

now edit/create ckeditor config file(app/assets/javascripts/ckeditor/config.js) and add the following line.
```config.extraPlugins = 'word count';```

example config file
```js
CKEDITOR.editorConfig = function( config ) {
  // redacted
  ...
  ...
  config.extraPlugins = 'wordcount';
};
```

you can set more options for word count as specified in the README for word count plugin
https://github.com/w8tcha/CKEditor-WordCount-Plugin

**Comment by dsandstrom** [comment]
You also need the notification plugin.

Required Files:

https://github.com/w8tcha/CKEditor-WordCount-Plugin/tree/master/wordcount
**vendor/assets/javascripts/ckeditor/plugins/wordcount/plugin.js**
**vendor/assets/javascripts/ckeditor/plugins/wordcount/lang/en.js**
or whatever languages you are using
**vendor/assets/stylesheets/ckeditor/plugins/wordcount/css/wordcount.css**

https://github.com/ckeditor/ckeditor-dev/tree/master/plugins/notification
**vendor/assets/javascripts/ckeditor/plugins/notification/plugin.js**
**vendor/assets/javascripts/ckeditor/plugins/notification/lang/en.js**
