### ISSUE TITLE
Resize Image Upload

### ISSUE THREAD

**Issue by lucas-wade** [galetahub/ckeditor#625]
Hi,
So refile is pretty neat software but i don't see how you support resizing the image files. It seams like its just a css class that resizes the full image file. So the client has to download the full image instead of resizing it using the refile backend? Am I missing something?

Thanks very much,
Luke

**Comment by adityashedge** [comment]
Can you please elaborate on your question. It does not make much sense but here's my understanding.

Say your image tag is  
```ruby
<%= image_tag attachment_url(@user, :profile_image, :fill, 300, 300, format: "jpg") %>
```
Support for ```refile``` also adds ```refile-mini_magick``` which uses ```mini_magick```
Code extract from ```refile-mini_magick```
```ruby
# Resize the image so that it is at least as large in both dimensions as
# specified, then crops any excess outside the specified dimensions.
#
# The resulting image will always be exactly as large as the specified
# dimensions.
#
# By default, the center part of the image is kept, and the remainder
# cropped off, but this can be changed via the `gravity` option.
#
# @param [MiniMagick::Image] img      the image to convert
# @param [#to_s] width                the width to fill out
# @param [#to_s] height               the height to fill out
# @param [String] gravity             which part of the image to focus on
# @yield [MiniMagick::Tool::Mogrify, MiniMagick::Tool::Convert]
# @return [void]
# @see http://www.imagemagick.org/script/command-line-options.php#gravity
def fill(img, width, height, gravity = "Center")
  # We use `convert` to work around GraphicsMagick's absence of "gravity"
  ::MiniMagick::Tool::Convert.new do |cmd|
    yield cmd if block_given?
    cmd.resize "#{width}x#{height}^"
    cmd.gravity gravity
    cmd.extent "#{width}x#{height}"
    cmd.merge! [img.path, img.path]
  end
end
```
So to answer your question, I don't think so. ```refile``` will actually resize the image for you.

**Comment by donkeydonkey** [comment]
Thanks. I mean that when you insert an image into the html editor you don't have any option to resize it.
The creditor only resizes it with css which results in downloading a large original sized image and then shrinking it with css. this is inefficient and in many cases makes the display super slow.
it would be cool to have creditor generate a refile resize request using the 
<%= image_tag attachment_url(@user, :profile_image, :fill, 300, 300, format: "jpg") %>

thanks
luke

**Comment by adityashedge** [comment]
yes inside the CKEditor you will have the full image but if you can somehow provide the image of the required size using url and passing dimensions as parameter.
Not sure how it can be done; might have to do some experimentation(something like what Cloudinary does).

Also check lib/generators/ckeditor/templates/active_record/refile/ckeditor/picture.rb
