### ISSUE TITLE
Cant upload to the server, hangs on asset compilation

### ISSUE THREAD

**Issue by tkaboris** [galetahub/ckeditor#628]
Hi, i am using rails 4.2 and latest ruby. 
I installed latest gem version it works fine on local host, but when i try to upload it to server, via capistrano, it hangs on asset compilation.  ANd after waiting for a long time, red logs begin to appear.  I searched for stack exchange and tried all possible solutions i can find.  Is there maybe another solution to this? Thank you in advance.

**Comment by zakwanhaj** [comment]
+1

**Comment by galetahub** [comment]
Try to use CKEditor CDN https://cdn.ckeditor.com/
1. Remove "//= require ckeditor/init" from your application.js
2. Set ckeditor source url
``` ruby
# in config/initializers/ckeditor.rb

Ckeditor.setup do |config|
  # //cdn.ckeditor.com/<version.number>/<distribution>/ckeditor.js
  config.cdn_url = "//cdn.ckeditor.com/4.5.6/standard/ckeditor.js"
end
```
3. Include source url in view template
``` slim
= javascript_include_tag Ckeditor.cdn_url
```

**Comment by zakwanhaj** [comment]
@galetahub , CKEditor CDN works well. 
But, sometimes I need to serve some CKEditor plugins on my server. For example, preview plugin is not working on Firefox browser due to security concerns. Firefox fires an error: `Error: Permission denied to access property "_cke_htmlToLoad"`

**Comment by moeabdol** [comment]
I believe this is a problem with ssh tunnel and not with ckeditor. 
Try modifying you /etc/ssh/sshd_config on your remote server and add the following lines:
```
ClientAliveInterval 30
ClientAliveCountMax 10
```
Hope this helps.

**Comment by mikhoul** [comment]
@zakwanhaj 

About  

> Firefox fires an error: Error: Permission denied to access property "_cke_htmlToLoad"

Have you found a fix ? I have the same problem and it happen to on http://ckeditor.com/demo#full  :disappointed:

**Comment by zakwanhaj** [comment]
@mikhoul unfortunately, no I didn't find a solution for this problem

**Comment by fanshuai** [comment]
👍   the same problem :(
