### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier on Heroku

### ISSUE THREAD

**Issue by lucasprag** [galetahub/ckeditor#629]
Hi.

I tried to figure out what's going on, but I couldn't. Sorry.

The editor works fine on my ruby on rails app in the localhost, but when I send it to heroku (production) I get this: `Uncaught SyntaxError: Unexpected identifier`, so I clicked in the error and It shows this line: 

```
CKEDITOR.lang.en={editor:"Rich Text Editor",editorPanel:"Rich Text Editor panel",common:{editorHelp:"Press ALT 0 for help",browseServer:"Browse Server",url:"URL",protocol:"Protocol",upload:"Upload",uploadSubmit:"Send it to the Server",image:"Image",flash:"Flash",form:"Form",checkbox:"Checkbox",radio:"Radio Button",textField:"Text Field",textarea:"Textarea",hiddenField:"Hidden Field",button:"Button",select:"Selection Field",imageButton:"Image Button",notSet:"<not set>",id:"Id",name:"Name",langDir:"Language Direction",langDirLtr:"Left to Right (LTR)",langDirRtl:"Right to Left (RTL)",langCode:"Language Code",longDescr:"Long Description URL",cssClass:"Stylesheet Classes",advisoryTitle:"Advisory Title",cssStyle:"Style",ok:"OK",cancel:"Cancel",close:"Close",preview:"Preview",resize:"Resize",generalTab:"General",advancedTab:"Advanced",validateNumberFailed:"This value is not a number.",confirmNewPage:"Any unsaved changes to this content will be lost. Are you sure you want to load new page?",confirmCancel:"You have changed some options. Are you sure you want to close the dialog window?",options:"Options",target:"Target",targetNew:"New Window (_blank)",targetTop:"Topmost Window (_top)",targetSelf:"Same Window (_self)",targetParent:"Parent Window (_parent)",langDirLTR:"Left to Right (LTR)",langDirRTL:"Right to Left (RTL)",styles:"Style",cssClasse
```

There is a syntax error in the end, but how can I fix it? oO
Thanks =)

**Comment by Lucasosf** [comment]
Just forgot, I'm using the `4.1.5` and that is my form:
```erb
<%= form_for(note) do |f| %>
<!-- [...] -->
    <%= f.cktext_area :content, class: "ckeditor form-control", id: "editor-#{note.kind}", ckeditor: { toolbar: 'mini', language: 'en' } %>
<!-- [...] -->
    <%= f.submit class: "btn btn-primary" %>
<% end %>
```

**Comment by Lucasosf** [comment]
I also tried to add the `<%= javascript_include_tag 'ckeditor/ckeditor' %>` on my layout, but it didn't work.

**Comment by Lucasosf** [comment]
I tried to add `//= require ckeditor/init` on my application.js file.
I solved it by adding the `<script src="//cdn.ckeditor.com/4.5.6/standard/ckeditor.js"></script>` on my layout file, but It's bad.
Is there other way to solve this?
Seems that the gem isn't requiring the ckeditor js files.

**Comment by lucasprag** [comment]
I figured out how to solve this later.

This problem happened because of turbolinks. Basically turbolinks replaces the content of the body tag to speed up the navigation.

In order to solve this I had to move the script tag to the head of my layout.

I'm closing this issue once I figured this out.
