### ISSUE TITLE
How to upload file or image when add config.js file

### ISSUE THREAD

**Issue by hellovietnam93** [galetahub/ckeditor#633]
Before i add config.js file to my project, i can use upload file or image. It is very good.
When i add config.js file to project i can not upload file or image, I tried to use many add on but it can't work. How can i enable upload file or image. Thank

**Comment by tannerj** [comment]
I also had this problem. After reading the README really carefully, I found this line: "When overriding the default config.js file, you must set all configuration options yourself as the bundled config.js will not be loaded." I then found this file in the code base: 

https://github.com/galetahub/ckeditor/blob/master/app/assets/javascripts/ckeditor/config.js

There are a bunch of config paths set in that file. Lines 14-34 seem to do what you are asking for. Hope this helps.

**Comment by hellovietnam93** [comment]
@tannerj thank a lot. :dancer:. I spent a lot of time. Thank for you help
