### ISSUE TITLE
Assets Precompilation taking too much time

### ISSUE THREAD

**Issue by aragorn2308** [galetahub/ckeditor#635]
I'm using the Gem. I've added the initializer as suggested in the wiki, still its taking a lot of time and compiling for all the language packs.
# in config/initializers/ckeditor.rb ---- done

Ckeditor.setup do |config|
  config.assets_languages = ['en', 'fr']
  config.assets_plugins = ['image', 'smiley']
end

**Comment by patricklindsay** [comment]
I'm having the same issue. I'm assuming it's because I've also followed the deployment step where it says:
```
For Rails 4, add the following to config/initializers/assets.rb:

Rails.application.config.assets.precompile += %w( ckeditor/* )
```

Some clear steps on how to resolve this precompile time would be really useful.

**Comment by tirdadc** [comment]
There is a workaround to get this to work here: https://github.com/galetahub/ckeditor/issues/519

but it would be nice if you didn't need to go through those additional steps for it to work.

**Comment by IvanDreamer** [comment]
It would be really cool if someone would take care of it.
