### ISSUE TITLE
rails 5 support

### ISSUE THREAD

**Issue by u007** [galetahub/ckeditor#637]
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from class:ApplicationController at /usr/local/rvm/gems/ruby-2.2.2/bundler/gems/ckeditor-8c95708276dd/app/controllers/ckeditor/application_controller.rb:4)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from class:ApplicationController at /usr/local/rvm/gems/ruby-2.2.2/bundler/gems/ckeditor-8c95708276dd/app/controllers/ckeditor/application_controller.rb:5)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from class:ApplicationController at /usr/local/rvm/gems/ruby-2.2.2/bundler/gems/ckeditor-8c95708276dd/app/controllers/ckeditor/application_controller.rb:6)

**Comment by u007** [comment]
DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead. (called from <class:AttachmentFilesController> at /usr/local/rvm/gems/ruby-2.2.2/bundler/gems/ckeditor-8c95708276dd/app/controllers/ckeditor/attachment_files_controller.rb:2)
DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead. (called from <class:PicturesController> at /usr/local/rvm/gems/ruby-2.2.2/bundler/gems/ckeditor-8c95708276dd/app/controllers/ckeditor/pictures_controller.rb:2)

**Comment by mibamur** [comment]
@galetahub hello
small controller  DEPRECATION  fix

**Comment by galetahub** [comment]
Thanks, but it's brake support for rails 3

**Comment by u007** [comment]
i think we need multiple branches, 1 for rails 3 and another for rails 4 and above

**Comment by heatskr** [comment]
1. When I was creating a carrierwave picture attachment with Rails 5.0.0 I got this:

```
DEPRECATION WARNING: ":nothing" option is deprecated and will be removed in Rails 5.1. Use "head" method to respond with empty response body.
```

2. Also in Ckeditor::AssetResponse#errors I caught this:

```
if json? ...
elseif ckeditor? ...
else asset.errors.full_messages # { "Assetable must exists" }
```

**Comment by mibamur** [comment]
@galetahub have U some about it? plans?

**Comment by dieuit07** [comment]
Hi everyone, I have problem with rails 5, ruby 2.3.1, ckeditor 4.1.6, sprockets 3.5.2, sprockets-rails 3.1.1 , when I click button 'browse server' to upload image. I gave this error: `wrong number of arguments (given 1, expected 2)`

**Comment by mibamur** [comment]
@heatskr Rails 5.1 warring is nothing serious - Rails just talk about future plan

**Comment by mibamur** [comment]
@dieuit07 look at carrierwave + ckeditor

**Comment by dieuit07** [comment]
what do you mean? @mibamur

**Comment by dieuit07** [comment]
I figure it out. The reason is GEM 'postgres_ext' it require arel ver '4.0.1'. I remove that gem and it work like a charm :)

**Comment by hapan** [comment]
Now the rails 5.1 is released.
It is giving the following error now:
`NoMethodError: undefined method `before_filter' for Ckeditor::ApplicationController:Class`

**Comment by marimaf** [comment]
@hapan  what did you do to solve it?

**Comment by hapan** [comment]
@marimaf I was just trying it under Rails 5.1 and did not work on solving it

**Comment by patricklindsay** [comment]
Closing this as the original post is relating to deprecation warnings.

If anyone is still having any problems with Rails 5 please create an issue. Make sure to include details such as gem version, Rails version, full stack trace and ideally a sample app.
