### ISSUE TITLE
How to customize font/size available in ckeditor

### ISSUE THREAD

**Issue by misner** [galetahub/ckeditor#640]
I have installed ckeditor rails gem and it works perfectly (inside Active admin).
1. The only thing is I want to optimize the weight and the performance hit on my server.
   I would like not to have all the possible fonts (georgia, lucida, tahoma, verdana...)which I guess have been installed on server to enable me to use in ckeditor.
   How to remove them from server? 
2. Also I would like to prevent user to be able to choose /customize fonts and sizes : I don't want any button 'font' , 'size' to appear in the ckeditor toolbar.
   how do do this ?

Thanks

**Comment by maysam** [comment]
@misner did you get a solution for the above?

**Comment by misner** [comment]
nope

**Comment by maysam** [comment]
copy https://github.com/galetahub/ckeditor/blob/master/app/assets/javascripts/ckeditor/config.js in app/assets/javascripts/ckeditor/ folder

then you can edit the new config.js file and make changes you want

**Comment by misner** [comment]
I know :) I already have this and i commented out parts such as:

`  //{ name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },`

so the user doe snot have any way to edit the font. But my issue is I still see ckeditor downloads all the .tiff/.toff and all fonts on the server, while I don't need it ever.

Would like to remove them from ckeditor so that it does not pull them on the server.

M.
