### ISSUE TITLE
not work editor in laravel 5.2

### ISSUE THREAD

**Issue by premier213** [galetahub/ckeditor#641]
![2016-02-23_9-14-42](https://cloud.githubusercontent.com/assets/4321174/13242814/ef183198-da0d-11e5-868e-cc29f6b34fa7.jpg)
hi my use this package for laravel 5.2 and when add

`<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script> <script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script> <script> $('textarea').ckeditor(); // $('.textarea').ckeditor(); // if class is prefered. </script>`

to my page not work
![94740fce-d99e-11e5-863f-bd7e18bb4275](https://cloud.githubusercontent.com/assets/4321174/13242770/9591125c-da0d-11e5-8ffc-f8e5e72457ab.jpg)
![61775a44-d8eb-11e5-864d-b9c789a28544](https://cloud.githubusercontent.com/assets/4321174/13242771/95927f66-da0d-11e5-9d22-7e83afc8e13d.jpg)

**Comment by onceatime** [comment]
I think you are in the wrong repo! This here is the ruby implementaion!
