### ISSUE TITLE
Scope not working

### ISSUE THREAD

**Issue by ngelx** [galetahub/ckeditor#650]
Hey, I've got ckeditor + carrierwave + aws working, but even if the assetable_id and type are set ok, the picture index (the one that is shown when click on "explore server" ) is not scoping. As a result, all user can see all pictures uploaded.

this is how the model is stored.

```
irb(main):017:0> Ckeditor::Picture.last
=> #<Ckeditor::Picture id: 8, data_file_name: "header1.jpg", data_content_type: "image/jpeg", data_file_size: 85740, assetable_id: 5, assetable_type: "User", type: "Ckeditor::Picture", width: 1972, height: 488, created_at: "2016-04-04 15:42:02", updated_at: "2016-04-04 15:42:02"> 
```

But if i browse picture with another user from the menu "image" -> "Show server", i can see it (and even delete it).

Any idea what is going on? I'm missing something?

Thanks in advance

**Comment by bnymn** [comment]
[#652](https://github.com/galetahub/ckeditor/issues/652) Similar issue I think.

**Comment by davidray** [comment]
Did you set override the file browser scope? This is what I've done and it works:
Ckeditor::ApplicationController.send :define_method, :ckeditor_filebrowser_scope do |o|
    super(
      o.merge(
        assetable_type: "User",
        assetable_id: current_user.try(:id)
      )
    )
  end
