### ISSUE TITLE
Uploads from "Upload" tab throw an "X-Frame-Options" error in production.

### ISSUE THREAD

**Issue by deevil828** [galetahub/ckeditor#653]
Everything is working properly in development mode locally.

In production:
* uploads sent from the "Browse Server" popup and then selected will properly insert into the editor window after clicking "Ok".
* uploads sent from the "Uploads" tab are uploaded, but when the uploads complete, the "Image Info" tab isn't automatically selected; instead, a "Load denied by X-Frame-Options: https://url does not permit framing." error appears in the JavaScript console.
* Attempting to close the "Image Properties" window after receiving the framing error will result in "Error: Permission denied to access property "document"" appearing in the JavaScript console and the window will not close.

If I reload the page to force the "Image Properties" window to close, I can then select the uploaded image with the "Browse Server" popup and it will inset into the editor and the "Image Properties" window will close properly when the "Ok" button is clicked.

I've researched the framing error, and confirmed that my Nginx config contained "add_header X-Frame-Options SAMEORIGIN;", but it doesn't seem to have any effect.

**Comment by joaoribeirost** [comment]
What was the error you were having and how did you solve it? It would be of great help to have that documented right now.

**Comment by kebling** [comment]
I don't have the error I received handy, but I believe the solution was to add these lines to my nginx config:

add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
