### ISSUE TITLE
Unable to override ckeditor/config.js

### ISSUE THREAD

**Issue by blackbiron** [galetahub/ckeditor#665]
I tried to copy `ckeditor/config.js` to `/app/assets/javascripts/ckeditor/config.js` and edit the toolbar. It's loaded, but the original `ckeditor/config.js` also got loaded and seems it's being used instead of the new one.

Cloned from master branch with rails 4.2.5.1, without using CDN.

**Comment by ThomasConnolly** [comment]
Having same issue. It's loading both my config.js plus the default. I'm using Rails 4.2.6 and Ruby 3.2.1
I also tried the solution presented here

      https://github.com/galetahub/ckeditor/issues/415

to no avail
