### ISSUE TITLE
4.2.0 Breaking Change - Extract dimensions

### ISSUE THREAD

**Issue by patricklindsay** [galetahub/ckeditor#670]
For those who are getting the following message:

```
NoMethodError (undefined method `read_dimensions' for #<CkeditorPictureUploader:0x007fc9b4c717f0>
Did you mean?  extract_dimensions):
  carrierwave (0.11.2) lib/carrierwave/uploader/processing.rb:84:in `block in process!'
```

Your [generated uploader](https://github.com/galetahub/ckeditor/blob/master/lib/generators/ckeditor/templates/base/carrierwave/uploaders/ckeditor_picture_uploader.rb) needs to be updated;

Change [line 31](https://github.com/galetahub/ckeditor/blob/master/lib/generators/ckeditor/templates/base/carrierwave/uploaders/ckeditor_picture_uploader.rb#L31) from `read_dimensions` to `extract_dimensions`

[For reference this is the breaking change](https://github.com/galetahub/ckeditor/commit/4e6d8413cc71f40d2d58ab3d0cb8dad19dd96894#diff-8592890eb68c81ec579de27d83e1c932R31)

**Comment by galetahub** [comment]
Hm, I'm already did it.

**Comment by vemv** [comment]
Please note that this was a breaking API change which didn't follow semver.

I suggest aliasing the method and bumping the version as a bugfix release.

Cheers - Victor

**Comment by trandaison** [comment]
Awesome, I have been running into a problem with config `CkeditorPictureUploader` and `Cloudinary` and this save the day.

Here is my uploader. The verison of CKeditor is 4.2.2

```rb
class CkeditorPictureUploader < CarrierWave::Uploader::Base
  include Ckeditor::Backend::CarrierWave
  include Cloudinary::CarrierWave
  include CarrierWave::MiniMagick

  process :extract_dimensions     # use this instead of :read_dimensions

  [:extract_content_type, :extract_size, :extract_dimensions].each do |method|
    define_method :"#{method}_with_cloudinary" do
      send(:"#{method}_without_cloudinary") if self.file.is_a?  (CarrierWave::SanitizedFile)
      {}
    end
    alias_method_chain method, :cloudinary
  end

  version :thumb do
    process :resize_to_fill => [118, 100]
  end

  version :content do
    process :resize_to_limit => [800, 800]
  end

  def extension_white_list
    Ckeditor.image_file_types
  end
end
```
