### ISSUE TITLE
after rebuild app, ckeditor not show in rails_admin 

### ISSUE THREAD

**Issue by wicky-info** [galetahub/ckeditor#677]
I have app its work, ckeditor show in rails admin , but when I rebuild (rake:create, migrate etc) ckeditor not show .. can someone help me, thanks
#### here is my example rails admin

![screenshot from 2016-08-15 06 29 20](https://cloud.githubusercontent.com/assets/8560064/17652828/abc58792-62b1-11e6-929b-8d87bb1bc9ad.png)

**Comment by RoRElessar** [comment]
Have the same issue in ActiveAdmin. Did you find the solution?

**Comment by wicky-info** [comment]
Helo @RoRElessar  if u use active admin here is my example, it two years ago but its works, 
![screenshot from 2017-03-31 09 49 10](https://cloud.githubusercontent.com/assets/8560064/24534330/7af0a832-15f7-11e7-906e-606e18b27e4f.png)
