### ISSUE TITLE
List of attachment files is not shown anymore

### ISSUE THREAD

**Issue by cyrilpic** [galetahub/ckeditor#678]
Hi !
I've had some troubles lately with the attachment file browser (picture browser is still OK). Previously uploaded files are not shown although they are in the DB.

It looks like commit 8b5d21d1a8727e2b9e1dba505f04b485ba840d37 is responsible for that. If I revert line 9 to `<%= render :partial => 'ckeditor/shared/asset', :collection => @attachments.scoped %>` the bug is resolved. Was there a reason why the `scoped` was removed ?

**Comment by dhairyagabha** [comment]
I am pretty new to Rails and have added the ckeditor to one of my rails application, but I am also not able to see the uploaded file. @cyrilpic can you tell me how you generated views for ckeditor, is it possible directly using terminal or is that supposed to be done manually?

**Comment by cyrilpic** [comment]
@dhairyagabha: I downloaded the source from github and copied ckeditor's views to my app.

**Comment by Pogoss** [comment]
Is there any progress?

**Comment by dhairyagabha** [comment]
@Pogoss Yes, I made some changes to my code found out my files were not actually being uploaded, I made necessary changes and my issue is resolved

**Comment by Pogoss** [comment]
@dhairyagabha i'm sorry, what changes did you make? Because as i see there a lot of uploaded files on web server in correct directory(

**Comment by dhairyagabha** [comment]
In the hurry to get everything working, I forgot to set up paperclip correctly for uploading images and files and hence ended up having issues, once I made sure everything was set up correctly for uploading with paperclip my issue was automatically resolved
