### ISSUE TITLE
JS lang file not loading in production

### ISSUE THREAD

**Issue by waghanza** [galetahub/ckeditor#681]
Hello,

I'm dealing with **ckeditor** `4.2` on **rails** `5.0`.

I have read the `README` file, but I have a 404.

The file **assets/ckeditor/lang/en-gb.js** could not be loaded.

I have checked this file in `$GEM_HOME/vendor/assets/javascripts/ckeditor/lang/en-gb.js`.

How can I load it ?

Regads,

**Comment by Shwetakale** [comment]
@waghanza Did you check when you do inspect element what path it is building to refer this file? Is it referring to correct path? I have tried this and it works but tried with ```rails 4``` and not with ```rails 5```. There might be something with asset path building or precompilation.

**Comment by waghanza** [comment]
@Shwetakale effectively not.

I have add `Rails.application.config.assets.precompile += %w( ckeditor/lang/fr.js )` to my **config/initializer/ckeditor.rb** and it seems to work.

I have to find a way to add dynamically all lang files when I want to use internationalize my app

Regards,
