### ISSUE TITLE
Rails 5 CKEditor+Carrierwave+Cloudinary Browse server error

### ISSUE THREAD

**Issue by june26** [galetahub/ckeditor#684]
can someone help me?
I've problem in browse server when I want to upload a picture or more

for the first time after I integrate carrierwave+cloudinary to CKEditor, I can open the browse server and upload picture to cloudinary and it works well, but when I try again to click on browse server in image upload button, I get an error like this

![screenshot from 2016-09-05 23 56 29](https://cloud.githubusercontent.com/assets/22035315/18285825/496884a0-749a-11e6-8c0a-6cd7ebd586be.png)

there seems to be wrong when the browse server wants to show images that have been uploaded already uploaded
anyone can help me ? I'm stuck here
oh here for detail my code
[http://stackoverflow.com/questions/39335359/rails-5-browse-server-ckeditor-error-undefined-method-path-after-upload-a-p](url)

thanks

**Comment by mccard** [comment]
@june26 same problem here. did you solve it?

**Comment by mccard** [comment]
```
  [:extract_content_type, :set_size, :read_dimensions].each do |method|
   define_method :"#{method}_with_cloudinary" do
    send(:"#{method}_without_cloudinary") if self.file.is_a?(CarrierWave::SanitizedFile)
    {}
   end
  alias_method_chain method, :cloudinary
  end
```

check https://stackoverflow.com/questions/17225138/ckeditor-carrierwave-cloudinary

**Comment by tiagocassio** [comment]
Seems the @mccard solution does not work...

**Comment by mccard** [comment]
It's not actually mine.. See the alternative answers on the link I Posted, it may be helpful..
