### ISSUE TITLE
ckeditor miss something for minification from rails production environment [resolved]

### ISSUE THREAD

**Issue by jerome-diver** [galetahub/ckeditor#685]
Hi,
i have many problem with ckeditor on production environment only. From development environment, it works, but not on production.
Then someone on the IRC channel of RUbyOnRials explain me that is should may be come from minification problem.
These kind of problem would exist because of the content code in javascript miss some semicolons or curly braces by simplification of codes (like write an inline function without curly braces).
So... i'm going to look at this but the code is big and it is not sure 100%.
Could you check that this ckeditor should really works on production environment please ?
I use it inside a dialog-ui windows at edit time... i edit through AJAX call, and the ckeditor miss to appear on production mode only.
thank you

**Comment by jerome-diver** [comment]
resolved... i had to write in config/initializer/asset.rb
Rails.application.config.assets.precompile += %w( ckeditor/* )

like indicate in the README file of ckeditor here.

**Comment by PirunSeng** [comment]
@jerome-diver may you raise some of your problems please? and what are your previous config before the config that solved your problem?
