### ISSUE TITLE
ckeditor work... but only on first shot call and on development mode

### ISSUE THREAD

**Issue by jerome-diver** [galetahub/ckeditor#686]
Rails-4.2.6
ckeditor is working on my development wweb site, but only the first call shot.
my application do use AJAX edition view call, these views are inside a dialog-ui from jqurey-ui.
but actually, if i call the edition, dialog-ui open, show inputs entries tags, then show ckeditor (need 2 seconds of wait for see it) and ok...
now i do cancel from ther
and i try again..; no more ckeditor, finish... i need to re-load the page.
so... i think that something who souldn't be in the cache memory somewhere (on my nginx-passenger cache ? on my rails-4 cache ?.... where ?) has to be call again each time with the ajax call... but... how ? and does it will works better this way ?
also, in production mode, ckeditor doesn't works at all... but still have his own assets directory and contain things... things who are not used.
is there a hope for see ckeditor running more than one time and maybe one time in production mode ?

**Comment by Shwetakale** [comment]
@jerome-diver Can you add your ```application.js``` file, application layout file and javascript you are using to load ckeditor here. I don't think this issue is with ckeditor. I think this is because of you have enabled turbolink and javascript is not getting bind on link click.

**Comment by jerome-diver** [comment]
Hi @Shwetakale, thank you for your answer.
here is my application.js file:
https://gist.github.com/jerome-diver/af4ef678f38ddd945c1631b8d819291d

I don't think it is a special issue from ckeditor too... but i think that this is a special problem many people should have to with ckeditor or other editor (this problem occurs with other editors the same). Then i'm searching for a solution (an help) for resolve this problem.
normally, it has to be bind at link click... because i call a coffeescript file (AJAX call) then this one do a
call a dialog box (jquery-ui dialog box) and put a partial inside...
$(#my_dialog_page").html '<%= j render "articles/nested/photos", photos: photos %>'
then this partial file _photo.haml has a "simple_form_for" form and call ckeditor container (same way the README doc from ckeditor suggest to do).
it works at first call, but not on second call (i need to reload the page).
so... which could be the solution in this situation ?

**Comment by Shwetakale** [comment]
@jerome-diver Hi I had reproduced this issue. I am still finding out solution but as a quick fix if you are stuck you can disable turbolink for that link. I know this is not correct solution but still we find solution you can do this

    %li= link_to "New Recipe", new_recipe_path, data: { "no-turbolink" => 'true'}

Anyone looking at this issue can refer to [this](https://github.com/Shwetakale/recipe_guru/blob/master/app/views/recipes/_form.html.haml)

**Comment by Shwetakale** [comment]
@jerome-diver check [this](https://dev.ckeditor.com/ticket/9878) out essentially in my case reinitializaing editor solved problem.

For ex.

```ruby
     $(document).on('ready page:load', function () {
        CKEDITOR.replace('recipe_steps');
     });
```

Hope this helps.

**Comment by jerome-diver** [comment]
@Shwetakale I also try these two way to do i already read in an other post around this problem, but actually, for me, it doesn't works.
no-rurbolink failed and CKEDITOR.replace failed. 
If i stop turbolink mecanism (not use it at all), same problem occur (so definitly, it is not from turbolink, if it was a problem from turbolink, then not use turbolink at all should resolve the problem, but it doesn't.
I also remove use of cache from my web server and try also from puma server instead of my nginx/passenger one... same problem occur again.
May it related with jquery and/or jquery-ui ?
By the time i think i should make an open code on bitbucket for reproduce my problem in a little simple same situation of code.
thank you for try to help me, i will be back...

**Comment by Shwetakale** [comment]
@jerome-diver This is weird because by disabling turbolink it worked fine for me. Yes it will be helpful if you can push some app which will reproduce this issue so anyone can look into it easily.

**Comment by jerome-diver** [comment]
@Shwetakale I also try these two way to do i already read in an other post around this problem, but actually, for me, it doesn't works.
no-rurbolink failed and CKEDITOR.replace failed. 
If i stop turbolink mecanism (not use it at all), same problem occur (so definitly, it is not from turbolink, if it was a problem from turbolink, then not use turbolink at all should resolve the problem, but it doesn't.
I also remove use of cache from my web server and try also from puma server instead of my nginx/passenger one... same problem occur again.
May it related with jquery and/or jquery-ui ?
By the time i think i should make an open code on bitbucket for reproduce my problem in a little simple same situation of code.
thank you for try to help me, i will be back...
