### ISSUE TITLE
bundle update ckeditor

### ISSUE THREAD

**Issue by jerome-diver** [galetahub/ckeditor#687]
gem 'ckeditor', github: 'galetahub/ckeditor' 
rails-4.2.6

but allways version 4.2.0 is installed.
why ?
how to fix that ?

i have a problem when i call for the second time ckeditor in a view from AJAX call inserted inside a dialog-jquery-ui window (in second call, ckeditor is no more present on the view and i need to refresh the page... i post an issue on that, but no answer), and maybe last version fix it... with or without turbolinks change nothing, same result, so it is NOT turbolinks mecanism.
And this happen also with other editor like tinyMCE. So it is something to learn about rails-4 jobs maybe...

**Comment by Shwetakale** [comment]
@jerome-diver Does your ```bundle install``` succeeds because I think here you might get syntax error as while specifying git path you need to use following syntax

    gem 'ckeditor', :git => 'https://github.com/galetahub/ckeditor'

I didn't try syntax you have given though.

Hope this helps.

**Comment by jerome-diver** [comment]
@Shwetakale i had no error on that, but i change for your syntax for try it (maybe more luck), but still the same.
Let me find any time for create a simple app open access who can reproduce my problem, i think we will have more luck to find a solution around this. It may have a problem with an other gem or an other javascript... 
I will be back at this time for tell you if i find by this way or for share this little application.
thank you for your help.
