### ISSUE TITLE
Problem With Toolbar Mini

### ISSUE THREAD

**Issue by LizBayardelle** [galetahub/ckeditor#688]
I just installed the CKEditor Gem in my app and it works well, but I'm trying to remove some of the superfluous buttons and am having issues.

I have the following in my `config.js` file:

```
CKEDITOR.config.toolbar_mini = [
      ["Bold","Italic","Underline","Strike"],
      ["Link", "Unlink"],
      ["Image", "HorizontalRule"],
      ["NumberedList","BulletedList","-","Outdent","Indent"],
  ];
```

I put `//= require ckeditor/init` in my application.js file (but not `//= require ckeditor/config`, which when present gets rid of the CKEditor from the view entirely).

I am calling it with this line in my `erb`:

`<%= f.cktext_area :body, class: "form-control", rows: 10, ckdeditor: { language: 'us', toolbar: 'mini'} %>`
Can you help figure out why I am still getting the full selection of buttons?

**Comment by TJWilson92** [comment]
You can check out [the docs](http://docs.ckeditor.com/#!/guide/dev_toolbar) - you may need to put the config inside the `editorConfig` function:

~~~
CKEDITOR.editorConfig = function ( config ) {
  config.toolbar_mini = [
    ["whatever", "goes", "here"],
    [etc],
    [etc]
  ]
};
~~~
