### ISSUE TITLE
Installed ckeditor 4.5.1 in my rails 3.2.14 app giving undefined method before_action error in production

### ISSUE THREAD

**Issue by sahil290791** [galetahub/ckeditor#691]
I have recently installed the latest version of ckeditor, I had 4.0.7 previously. In my local after bundle install it did not show any error. But once I did bundle install in production environment its showing undefined `before_action` error. 

Now I know that this version of gem supports Rails 5.1, but its breaking Rails 3.2.x version. Is there a fix for that. Does it even support Rails 3.2.x now?

Can there be a mention of Rails versions supported with the current version of CKEditor.

**Comment by richardrails** [comment]
any progress??

**Comment by sahil290791** [comment]
No, I think latest CKEditor will not work in Rails 3.x, 4.1.x or 4.0.x as `before_action` filter will not work. Someone should update the documentation clearly mentioning the Rails versions it supports.

**Comment by richardrails** [comment]
I have found solution. This fork works https://github.com/martincabrera/ckeditor
That guy has changed before_action to before_filter :-)

**Comment by sahil290791** [comment]
Thanks a lot @richardrails for sharing this link.

**Comment by gbenedict** [comment]
The last version I found that works with Rails 3.2.x is 4.1.3.

```
gem 'ckeditor', '4.1.3'
```

**Comment by sahil290791** [comment]
@gbenedict , I had to manually go through all the previous releases if it had `before_filter. Can some add a line in Readme that the current gem supports only Rails 4.0.x till 5?
