### ISSUE TITLE
Turbolink 5 + SimpleForm + ckeditor

### ISSUE THREAD

**Issue by jakephot** [galetahub/ckeditor#697]
We were having difficulties assuring ckeditor textboxes being re-initialized on our application running with Turbolink 5 (Rails 5) and SimpleForm. When we navigated away from the from that contained a ckeditor textbox and then went back to the form, the textbox occasionally did not get initialized. I believe the issue is related to #638 but here is the walkaround we found for document purposes. 

```
# form.html.haml
= f.input :body_html, as: :text, input_html: { class: 'myckeditor' }

# init_ckeditor.coffee
ready = ->
  $('.myckeditor').each ->
    CKEDITOR.replace $(this).attr('id')

$(document).on('turbolinks:load', ready)
```

**Comment by 1989medium** [comment]
# init_ckeditor.coffee
$(document).on 'turbolinks:before-cache', ->
  return unless typeof(CKEDITOR) != 'undefined'
  for name of CKEDITOR.instances
    CKEDITOR.instances[name].destroy() if name?

$(document).on 'turbolinks:load', ->
  return unless typeof(CKEDITOR) != 'undefined'
  $('.js-ckeditor').each ->
    CKEDITOR.replace($(this).attr('id'))

# form.html.haml
= f.input :body_html, as: :text, input_html: { class: 'js-ckeditor' }

**Comment by 1989medium** [comment]
and /config/initializers/assets.rb
``` 
Rails.application.config.assets.precompile += %w( ckeditor/* )
```

**Comment by galetahub** [comment]
Fixed at 4.2.1 gem version

**Comment by Radaga5t** [comment]
Got this issue with 4.3.0 gem version
It works fine if I leave page and return to it later
But if I'm on the page contains CKEditor, leaving this page and press "Go Back" in browser, I got the same issue described before.
Integration code and proof screen
`= f.input :body, as: :ckeditor, required: true, ckeditor: { toolbar: 'minimalize' } }`
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/20140551/99666698-60023200-2a7c-11eb-9cb5-7953c4105651.png">

**Comment by Radaga5t** [comment]
> Got this issue with 4.3.0 gem version
> It works fine if I leave page and return to it later
> But if I'm on the page contains CKEditor, leaving this page and press "Go Back" in browser, I got the same issue described before.
> Integration code and proof screen
> `= f.input :body, as: :ckeditor, required: true, ckeditor: { toolbar: 'minimalize' } }`
> <img alt="image" width="1037" src="https://user-images.githubusercontent.com/20140551/99666698-60023200-2a7c-11eb-9cb5-7953c4105651.png">

It can be fixed by adding
`meta name='turbolinks-cache-control' content='no-cache'`
To the application layout

But be careful, it will disable turbolinks' page caching, than may slow down your application
