### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by afuno** [galetahub/ckeditor#701]
Why is this happening?

Assets are compiled by default in Rails. Especially in production. How do I get use of existing ckeditor  assets in Rails?

[Config](http://pastebin.com/nJM1DZj4)

[Screenshot 1](https://habrastorage.org/files/dad/f9e/ec5/dadf9eec5fc047d48e5d538c17975bf2.png)

[Screenshot 2](https://habrastorage.org/files/2bc/6dc/487/2bc6dc487ef942789416f95acf284dc0.png)

[Screenshot 3](https://habrastorage.org/files/2e1/ad3/307/2e1ad3307f0543f6b1056c091a0934e5.png)

**Comment by geo767** [comment]
Такая же петрушка. Поставил  4-1-stable. На этой версии все работает в production нормально.

**Comment by zinkkrysty** [comment]
I have the same issue. The assets fail in production. It makes a request for:

`https://XXXX/assets/ckeditor/lang/en-gb.js?t=G6DE`which is not found

**Comment by swedishpotato** [comment]
Moved our site to serve over HTTPS instead, now ckeditor assets generating 404's all the time. Any clues as to why it can't find it's assets? I know assets in rails are a massive pain in the proverbial, but  ckeditor has suddenly stopped working altogether and I can't see what changed. Using latest version of ckeditor (4.2.2) and followed instructions to the letter, but no joy. 

assets/ckeditor/plugins/copyformatting/lang/en.js?t=GB8C is an example of a 404 file

**Comment by ischuyt** [comment]
Can confirm same issue on 4.2. Switched back to 4.1-stable, recompiled assets and it went away.

**Comment by ACPK** [comment]
Also hitting this issue.

**Comment by hilarysk** [comment]
Same here.

**Comment by bragovo** [comment]
Try to use a latest github version, it fixed here https://github.com/galetahub/ckeditor/pull/716.

**Comment by NicholasLYang** [comment]
Still have same issue with latest github version

**Comment by rhulse** [comment]
I had the same issue (404s), however the commit fixing #716 seems to have fixed it for me.

**Comment by footnoise** [comment]
Hi all,
I faced with the same issue today. I can confirm that https://github.com/galetahub/ckeditor/pull/716 helps only with `config.js` & `editor.css` loading. But loading language files still the issue, for example, default request for `en-gb.js` gets 404.

Using  gem directly from repo:
```(ruby)
gem 'ckeditor', git: 'https://github.com/galetahub/ckeditor.git'
```

**Comment by phoenixweiss** [comment]
I have the same issue, but still nothing helps

**Comment by juani0824** [comment]
Hello, i have this problem, CkEditor dont work

[
![image](https://user-images.githubusercontent.com/56587915/110954254-93790d00-8348-11eb-87e1-2f984e8a9a14.png)
]
