### ISSUE TITLE
ArgumentError (Version content doesn't exist!)

### ISSUE THREAD

**Issue by afuno** [galetahub/ckeditor#702]
I tried to upload a picture. As a result, I got the error. Log:

> I, [2016-11-01T21:22:10.321562 #30303]  INFO -- : [c5c9779d-86bd-4423-915d-00aa3c2c552d] Completed 500 Internal Server Error in 1011ms (ActiveRecord: 39.4ms)
> F, [2016-11-01T21:22:10.322661 #30303] FATAL -- : [c5c9779d-86bd-4423-915d-00aa3c2c552d]   
> F, [2016-11-01T21:22:10.322726 #30303] FATAL -- : [c5c9779d-86bd-4423-915d-00aa3c2c552d] ArgumentError (Version content doesn't exist!):
> F, [2016-11-01T21:22:10.322759 #30303] FATAL -- : [c5c9779d-86bd-4423-915d-00aa3c2c552d]   
> F, [2016-11-01T21:22:10.322785 #30303] FATAL -- : [c5c9779d-86bd-4423-915d-00aa3c2c552d] app/models/ckeditor/asset.rb:4:in `url'
> F, [2016-11-01T21:22:10.322807 #30303] FATAL -- : [c5c9779d-86bd-4423-915d-00aa3c2c552d] app/models/ckeditor/picture.rb:5:in `url_content'

What is the problem?

**Comment by galetahub** [comment]
What uploader are you using for file uploads?

**Comment by afuno** [comment]
@galetahub https://github.com/carrierwaveuploader/carrierwave

**Comment by callmedw** [comment]
Did this ever get answered? I'm in exactly the same spot! carrierwave as well!
