### ISSUE TITLE
CKEditor 4.6 please!

### ISSUE THREAD

**Issue by sadiqmmm** [galetahub/ckeditor#703]
CKEditor 4.6 is packed with new features such as a new default skin and updated UI, completely rewritten Paste from Word, new Copy Formatting, Upload File and Balloon Panel plugins, Occitan localization as well as some widget and accessibility improvements.

**Comment by galetahub** [comment]
Wow, I will update Ckeditor at this weekend

**Comment by sadiqmmm** [comment]
:thumbsup: Thanks bro! :simple_smile:

**Comment by galetahub** [comment]
Just released new gem version 4.2.1 with new CKEditor on board
