### ISSUE TITLE
Using custom skin

### ISSUE THREAD

**Issue by dikey94** [galetahub/ckeditor#705]
Is it possible to install custom ckeditor skin? If yes - how can I do it?

**Comment by wcmolina** [comment]
Did you try the instructions on the Wiki page?

https://github.com/galetahub/ckeditor/wiki/Add-New-Skin-to-Ckeditor

**Comment by dikey94** [comment]
I did. There is something wrong with the skin. It's called "minimalist" and it's not working with current version of ckeditor. I've checked "office2013" and it works perfect. Thanks!
