### ISSUE TITLE
Cannot set property 'dir' of undefined

### ISSUE THREAD

**Issue by NickyHeuperman** [galetahub/ckeditor#706]
I've been trying to squish a bug that apparently only happens in production, because of this I think it has something to do with asset compilation.

Relevant info: rails 5
latest ckeditor gem
ruby 2.4

I've tried setting windows.CKEDITOR_BASEPATH and also CKEDITOR.basepath, to no avail.
I also added ckeditor to precompile list by adding 
Rails.application.config.assets.precompile += %w( ckeditor/* )

Any insight in the matter would be appreciated

**Comment by NickyHeuperman** [comment]
Sorry apparently assets werent being precompiled, i followed the tutorial and recompiled my assets, make sure to follow every point peeps. Closing this issue

**Comment by nmoore2** [comment]
What did you do to precompile? I've tried `rake assets:clean` ` rake: assets:precompile` and ` rake assets:precompile RAILS_ENV=production`

**Comment by morteza-gho** [comment]
I encountered this error when I concat ckeditor.js file with other js libraries!
When attach ckeditor.js separately, everything is OK!

**Comment by sontd-0882** [comment]
@morteza-gho How did you attach `ckeditor.js` separately? 🤔
