### ISSUE TITLE
can't select text with mouse

### ISSUE THREAD

**Issue by liuxsen** [galetahub/ckeditor#710]
![gif](https://cloud.githubusercontent.com/assets/12598696/21174149/686fb3d6-c216-11e6-9466-95b3c8d39aff.gif)

**Comment by TJWilson92** [comment]
Can we get some more information, a js fiddle or something with this, or otherwise close the issue?

**Comment by bansalnitish** [comment]
Hi @TJWilson92 
I'm facing similar issue. I am unable to select the text with mouse in CKEditor. Is this a issue with CKEditor ?
Thanks.

**Comment by TJWilson92** [comment]
@bansalnitish  As before - if you can replicate this in a jsfiddle / codepen, or provide more specifics.
