### ISSUE TITLE
ckeditor won't work in Heroku 

### ISSUE THREAD

**Issue by jaybatalla** [galetahub/ckeditor#714]
Hi guys,

Ckeditor didn't appear when i deploy it to Heroku but it is working at local. How can i fix it guys? 
Thanks in advance.

**Comment by farojos** [comment]
http://stackoverflow.com/questions/19777316/problems-with-ckeditor-running-on-production-rails-application-with-heroku

**Comment by jeffblake** [comment]
I had to do a bunch of stuff: used the heroku repo-plugin to clear the gem cache (removes precompiled assets), invalidated caches on CloudFront, and use `CKEDITOR.timestamp = '76SDJ77D';` in my config.js file.
I think it was the last one that actually fixed it.

**Comment by bragovo** [comment]
Same thing. I think this is the problem https://github.com/galetahub/ckeditor/pull/716
Task don't copy nondigest files.

**Comment by cweilemann** [comment]
Just curious, as I haven't read anywhere... Is the plan to fix the gem to work with digested assets?  And no, I'm not (necessarily) volunteering...

**Comment by simplyluke** [comment]
Abandoning precompilation is not an option for many (most?) production environments with a lot of traffic. Would also like to hear a response to @cweilemann's question.

**Comment by simplyluke** [comment]
See also #307

**Comment by leofrozenyogurt** [comment]
+1 ; rails 5 with ckeditor 4.1.6 works on heroku but 4.2 upwords has label issues

**Comment by Codacad** [comment]
j

> I had to do a bunch of stuff: used the heroku repo-plugin to clear the gem cache (removes precompiled assets), invalidated caches on CloudFront, and use `CKEDITOR.timestamp = '76SDJ77D';` in my config.js file.
> I think it was the last one that actually fixed it.

Thanks, it worked.

**Comment by Codacad** [comment]
@jeffblake 
Thanks, it worked.
