### ISSUE TITLE
Rails 5 issue with ckeditor, error: Sprockets::FileNotFound. Need help!!

### ISSUE THREAD

**Issue by dbgobar** [galetahub/ckeditor#715]
Hi everyone,
I'm trying to use ckeditor for a simple rails app but i keep getting this error. Here it is in more detail:
```
Sprockets::FileNotFound in Welcome#homepage
Showing /Users/Diana/Desktop/wdi/projects/organization/app/views/layouts/application.html.erb where line #8 raised:
couldn't find file 'ckeditor' with type 'application/javascript'
```
in my Gemfile i installed ckeditor this way:
```
gem 'ckeditor', :git => 'git://github.com/galetahub/ckeditor.git'
```
in my application.js file I added all three of these seperately to test, and none worked:
```
//= require ckeditor/override
//= require ckeditor/init
//= require ckeditor/config
```
The instructions I used were from this site and the github page:
https://richonrails.com/articles/getting-started-with-ckeditor.

Could it be that the ckeditor files I downloaded are located in the wrong place? 
New to plugins/gems so I'm not sure where exactly I should be putting the package I downloaded as well.
Please help if you can!

**Comment by TJWilson92** [comment]
Can you post your application.html.erb, ideally lines 1-10.
