### ISSUE TITLE
undefined method `cdn_url=' for Ckeditor:Module

### ISSUE THREAD

**Issue by jmurphy45** [galetahub/ckeditor#718]
I ran the generators and added config.cdn_url = "//cdn.ckeditor.com/4.6.1/basic/ckeditor.js" to the initializer and I got the error "undefined method `cdn_url=' for Ckeditor:Module" Could not find anything about the issue if it is one. I am using rails 4.2.6

**Comment by TJWilson92** [comment]
Looks like you might have forgotten the `http:` - https://cdn.ckeditor.com/4.6.1/basic/ckeditor.js

**Comment by lenart** [comment]
The `https` won't help. It looks like the gem version of `ckeditor` is off and doesn't support `cdn_url` config. Check your versions or post them here for reference.

This config should work so if it doesn't it's likely because of incorrect gem version:

```ruby
# config/initializers/ckeditor.rb
Ckeditor.setup do |config|
  # //cdn.ckeditor.com/<version.number>/<distribution>/ckeditor.js
  config.cdn_url = "//cdn.ckeditor.com/4.6.1/basic/ckeditor.js"
end
```

**Comment by nbsamar** [comment]
Upgrade your ckeditor to `gem 'ckeditor', '~> 4.2', '>= 4.2.4'`.
