### ISSUE TITLE
"path" in ckeditor.rake may be wrong

### ISSUE THREAD

**Issue by mythhsy** [galetahub/ckeditor#720]
the rake task ckeditor:nondigest in ckeditor.rake.
the Ckeditor.base_path is "/assets/ckeditor/",notice there's a '/', then the path = Rails.root.join('public', Ckeditor.base_path, '**/*') 
gets "#<Pathname:/assets/ckeditor/**/*>",not "#<Pathname: <project root>/public/assets/ckeditor/**/*>" as expected,and Dir[path] gets [],is it a careless bug?
ps: I'm using rails 4.2.7 and ruby 2.3.1.

**Comment by patricklindsay** [comment]
This has been fixed in #716. It just hasn't been released yet.
