### ISSUE TITLE
Custom handler is not a constructor

### ISSUE THREAD

**Issue by NicholasLYang** [galetahub/ckeditor#725]
Getting the following issue in production only:
`Uncaught TypeError: CKEDITOR.style.customHandlers[e.type] is not a constructor`
My assets are precompiled
assets.rb
```

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
Rails.application.config.assets.precompile += %w(ckeditor/*)
Rails.application.config.assets.precompile += %w( *.js ^[^_]*.css *.css.erb )

```

**Comment by rbatllet** [comment]
The SAME problem. 

I'm using` ckeditor 4.1.2` and Rails `4.2.8`

**Comment by vadimstroganov** [comment]
The SAME problem. ckeditor 4.2.0

**Comment by rbatllet** [comment]
If you install the latest stable version of ckeditor, the problem will be solved on Heroku. Add this to the Gemfile:

```
gem 'ckeditor', '~> 4.2.2'
gem 'non-stupid-digest-assets', '~> 1.0.4'
```

And create a file for example `config/initializers/non_digest_assets.rb` and add this:

```
NonStupidDigestAssets.whitelist += [/ckeditor\/.*/]
```

**Comment by jhadeepakkumar14** [comment]
Facing the same problem with rails 4.0.2. Tried every solution. Nothing seems working. Any help highly appreciated.
