### ISSUE TITLE
ActionView::Template::Error (ckeditor.js isn't precompiled):

### ISSUE THREAD

**Issue by jakarmy** [galetahub/ckeditor#729]
In a production environment, I'm getting this error message when trying to load CKEditor:
`ActionView::Template::Error (ckeditor.js isn't precompiled):`

I have added to my `config/environments/production.rb` the following:
```
config.assets.precompile += Ckeditor.assets
config.assets.precompile += %w(ckeditor/config.js)
config.assets.precompile += %w(ckeditor/ckeditor.js)
config.assets.precompile += ['ckeditor/*']
```

I have also noticed that the sample app on the repo does not include the ckeditor.js file... which puzzles me a bit.
I am using:

- Rails 3.2.3
- ruby 1.9.3p551
- CKEditor Gem 4.1

I would appreciate your feedback on how to get over this problem.

**Comment by patricklindsay** [comment]
Closing this, if you're still having the issue with the latest version of Ckeditor and Rails feel free to reopen with more information and/or a test case/example app reproducing the issue.
