### ISSUE TITLE
Ckeditor Image Upload Rails 5 not working

### ISSUE THREAD

**Issue by leofrozenyogurt** [galetahub/ckeditor#730]
When i try and upload a picture and send it to the server I get a response that the data can't be blank. After looking into the code it seems that @picture in create is not sending any of the params.

 @picture = Ckeditor.picture_model.new
 respond_with_asset(@picture)

^^^ @picture returns nil

**Comment by leofrozenyogurt** [comment]
after digging a bit it seems there is some issue with the data being saved

**Comment by leofrozenyogurt** [comment]
[1] pry(#<Ckeditor::PicturesController>)> asset
=> #<Ckeditor::Picture:0x007f84ae106938
 id: nil,
 data_file_name: nil,
 data_content_type: "image/jpeg",
 data_file_size: 179954,
 assetable_id: nil,
 assetable_type: nil,
 type: "Ckeditor::Picture",
 width: 595,
 height: 609,
 created_at: nil,
 updated_at: nil>
[2] pry(#<Ckeditor::PicturesController>)> asset.save
   (50.2ms)  BEGIN
   (9.6ms)  ROLLBACK
=> false
[3] pry(#<Ckeditor::PicturesController>)> asset.errors
=> #<ActiveModel::Errors:0x007f84ae5192a0
 @base=
  #<Ckeditor::Picture:0x007f84ae106938
   id: nil,
   data_file_name: nil,
   data_content_type: "image/jpeg",
   data_file_size: 179954,
   assetable_id: nil,
   assetable_type: nil,
   type: "Ckeditor::Picture",
   width: 595,
   height: 609,
   created_at: nil,
   updated_at: nil>,
 @details={:data=>[{:error=>:blank}]},
 @messages={:data=>["can't be blank"]}>

**Comment by jaswinder97** [comment]
It seem to be invalid file or file not present issue. Make sure that the file exists at path /uploads/ckeditor/pictures before referencing it.

**Comment by NickTseng** [comment]
i have some issue , plz help  :cry:

**Comment by jaswinder97** [comment]
I have resolved the issue. could you please share your skypeID?.

**Comment by NickTseng** [comment]
`def create
    @picture = Ckeditor.picture_model.new

    @picture.assetable_type =  '123'

    respond_with_asset(@picture)

  end
`
but assetable_type still nil

**Comment by galetahub** [comment]
Please, use the last gem version

**Comment by tonycchung** [comment]
@jaswinder97 @leofrozenyogurt did you guys ever resolve this? i'm on ckeditor 4.2.0 and upgrading carrierwave to 1.1.0 for Rails 5.1 and running into this issue now

**Comment by liyunqiang** [comment]
Maybe not install imagemagick

`brew install imagemagick`

Ckeditor version 5.1.0

rails version 6.0

Data can't be blank at the beginning

I found that imagemagick is not installed. I try to install it. After the installation is successful, the picture can be uploaded successfully
