### ISSUE TITLE
Custom contents CSS when loading from the CDN

### ISSUE THREAD

**Issue by isundaylee** [galetahub/ckeditor#733]
When I use the ckeditor CDN to load the JavaScript file, I notice that the editor is using the default contents stylesheet from the CDN. The custom `config.js` file, however, is used. Is this the current expected behavior? Thanks! 

Relevant browser console output: 

```
> CKEDITOR.config.customConfig
< "config.js"
> CKEDITOR.config.contentsCss
< "http://cdn.ckeditor.com/4.6.1/standard/contents.css?t=GB8C"
```

**Comment by arthurnobrega** [comment]
+1

**Comment by arthurnobrega** [comment]
@isundaylee Did you solve this problem?

**Comment by mattgilbertnet** [comment]
+1, experiencing the same issue here.
