### ISSUE TITLE
How add plugin to project?

### ISSUE THREAD

**Issue by Radzhab** [galetahub/ckeditor#741]
I download plugin audio from ckeditor site, unpack it to path `../public/assets/ckeditor/plugins/Audio`

In `config.js` in `EXTRA_PLUGINS` params i add audio.

In `TOOLBAR` i append audio button name: 'document',

`items: ['Source', 'Audio']`
When i start project i dont find audio button. What i make wrong?

**Comment by richpeck** [comment]
```
# app/assets/config/manifest.js
//= link_tree ../javascripts/ckeditor
```

**Comment by richpeck** [comment]
# app/assets/javascripts/ckeditor/config.js
config.extraPlugins   = "Autdio"

**Comment by fifiteen82726** [comment]
I do the same thing whit `youtube` plugin, but it fails.

**Comment by dengzhichao** [comment]
@Radzhab i have same,Can you tell me how you solve it.thanks
