### ISSUE TITLE
NoMethodError (undefined method `read_dimensions'....

### ISSUE THREAD

**Issue by nevick** [galetahub/ckeditor#742]
Rails 5.0.2
ruby 2.4.0p0 (2016-12-24 revision 57164) [i686-linux]
gem 'carrierwave'
gem 'mini_magick'

 When I try upload a picture and send it to the server I get the next:
NoMethodError (undefined method `read_dimensions' for #<CkeditorPictureUploader:0xbf89b88>
Did you mean?  readlines)
What can I do to resolve it???

**Comment by grammakov** [comment]
Try using process ```:extract_dimensions``` instead.

**Comment by ParinVachhani** [comment]
@grammakov I have the same issue. 
Can you give details into where exactly should I make that change?

**Comment by grammakov** [comment]
@ParinVachhani in `CkeditorPictureUploader` class, line 31

**Comment by nevick** [comment]
thank you very much!!! it's working for me !!! I have had try it in local server and in production. It's cool!!! You are tough guy!!!

**Comment by nevick** [comment]
thank you very much!!! it's working for me !!! I have had try it in local server and in production. It's cool!!! You are tough guy!!!
