### ISSUE TITLE
On invoking Second Time ckEditor Doesn't Work

### ISSUE THREAD

**Issue by Hemanthkumar16** [galetahub/ckeditor#747]
I am new to using ckEditor (but not FCKEditor) and on invoking ckEditor for first time (on a button click) it works exactly the way I want it to; but after that, on invoking for second time the ckeditor open but it is not allow us to edit or enter content. and it is not showing data that i passed via setData() in ckeditor.

i find that first instance need to be destroyed, for that when i call CKEDITOR.instance.editorname.destory(); or like this CKEDITOR.instance.editorname.destory(true); not working but throwing an error,
it says destory() is not defined in ckeditor. does anyone have solution for this problem ?? i am using ckeditor 4.6.2 (full). Thanks in advance

**Comment by hkakumanu-ttc** [comment]
@Hemanthkumar16 did you find a solution? I am facing this as well.
