### ISSUE TITLE
'lang' folder is missing from assets after the production deploy

### ISSUE THREAD

**Issue by thezed** [galetahub/ckeditor#751]
I've updated to Rails 5.1.0 (and 5.1.1). When I do the deploy for the first time (or any other time) the asset files being copied, but not the 'lang' folder. This causes error and ckeditor does not start on a page:
- Failed to load resource: the server responded with a status of 404 (Not Found) http://example.com/assets/ckeditor/lang/fr.js?t=H0CG
- TypeError: undefined is not an object (evaluating 'i[e].dir=i.rtl[e]?"rtl":"ltr"')

With Rails > 5.1.0 there is no such error, all files copies correctly to assets folder on deploy.

**Comment by gapnav** [comment]
I have same issue.
It made me to edit `initializers/assets.rb`:
```
Rails.application.config.assets.precompile += Ckeditor.assets
Rails.application.config.assets.precompile += %w( ckeditor/* ckeditor/lang/* )
```
Once I've added `lang` folder to assets, everything works properly.
I guess it should be added to `Ckeditor.assets`
