### ISSUE TITLE
plugins/copyformatting/lang/en.js?t=XXXX 404 (Not Found)

### ISSUE THREAD

**Issue by teddyswu** [galetahub/ckeditor#757]
Hi,
I have one problem, in console
GET https://XXXXX/assets/ckeditor/plugins/copyformatting/lang/en.js?t=XXXX 404 (Not Found)
and
Uncaught TypeError: Cannot read property 'label' of undefined
I use AWS EC2, and use Cloudfront
In Gemfile 
gem "ckeditor", "4.2.3"
gem "paperclip", '4.3.0'

If need more information, please tell me

Thanks

**Comment by teddyswu** [comment]
i download copyformatting and install, can solve it
but now i get new problem~

Cannot read property '224' of undefined
at Object.keystrokeToString (ckeditor_initialization-ff160d9….js:47)

**Comment by ccastillop** [comment]
The same
I notice there is no copyformat/langs inside /vendor/assets/javascripts/ckeditor/plugins/copyformatting 

Al also added copyformat/langs to my local version at /app/assets/javascript/ckeditor and got 
Cannot read property '224' of undefined
at Object.keystrokeToString (ckeditor_initialization-ff160d9….js:47)

It is possible to remove copyformat dependency or add these files?

**Comment by ccastillop** [comment]
Hi,
Just don't use vendor, use ckeditor by CDN
Now it works.

**Comment by theleemon** [comment]
Same here. It seems that the CKEditor package download generator is not including all necessary files in the Full Package.

**Comment by ibnuh** [comment]
Same here. I found a solution: 
just download manually from https://ckeditor.com/cke4/addon/copyformatting

**Comment by keerthivasan-d** [comment]
same issue when I try to deploy on production, someone find a solution ?

**Comment by patricklindsay** [comment]
I'll reopen this incase  anyone still experiencing this issue in `v4.3.0`? If so, then please provide a public working example application and I'll look into it.
