### ISSUE TITLE
I18n::MissingTranslationData in Ckeditor::Pictures#index

### ISSUE THREAD

**Issue by maurosbu** [galetahub/ckeditor#760]
Hi,
I'm working on a Rails 5.1 app and I got the following error:

    Showing CKEDITOR_PATH/app/views/ckeditor/shared/_asset.html.erb where line #14 raised:
    translation missing: it.time.formats.short

I solved this issue adding the following in Gemfile:

    gem 'rails-i18n', '~> 5.0', '>= 5.0.1'

What about adding this gem as ckeditor dependence?

Mauro

**Comment by teddyswu** [comment]
You can see this [Enter](https://stackoverflow.com/questions/17461766/rails-i18n-translations-seem-to-be-not-loaded)
Add this lines to your it.yml:
it:
  time:
     formats:
       default: "%Y/%m/%d"
       short: "%b %d"
       long: "%B %d, %Y"

**Comment by maurosbu** [comment]
@teddyswu I'm successfully using rails-18n! I think that either should rails-i18n be added as ckeditor runtime dependency or the I18n section in readme be updated.
