### ISSUE TITLE
Problem with long render time in files manager

### ISSUE THREAD

**Issue by luckyluk92** [galetahub/ckeditor#761]
I have application on heroku which uses Mongoid, Carrierwave and keeps files on S3. When I configured Ckeditor to use S3 as well, I noticed that files manager is not showing up because request lasts more than 30s and heroku returns 503.

After hours of searching for solution I noticed that size method is causing this problem because it makes a request to S3 for file's size...

`Ckeditor::Orm::Base` implements size method (https://github.com/galetahub/ckeditor/blob/master/lib/ckeditor/orm/base.rb) which uses data_file_size field saved in a database, however `Ckeditor::Asset` (https://github.com/galetahub/ckeditor/blob/master/lib/generators/ckeditor/templates/mongoid/carrierwave/ckeditor/asset.rb) delegates size method to carrierwave's uploader which makes a request for file's size.

I'm not sure why that delegation is taking place here.

As a fix, I overrode method size within `Ckeditor::Picture` and `Ckeditor::AttachmentFile`
```ruby
def size
  data_file_size
end
```
which looks exactly the same as implementation provided by `Ckeditor::Orm::Base`

**Comment by galetahub** [comment]
Fixed https://github.com/galetahub/ckeditor/commit/1cca2775e603cfe7805bfbfed00b1ce78ced5e44
