### ISSUE TITLE
Inline editor and simpleform issues

### ISSUE THREAD

**Issue by hassanc** [galetahub/ckeditor#762]
I am trying to use simple_form_for with the inline editor.

How do I pass the   

> `<div id="editor1" contenteditable="true">`

 into simple form?

for example:

>     <%= simple_form_for @resume do |f| %>
>       <%= f.input :formattedname, wrapper_html: { id: '"editor1" contenteditable="true"' } %>
>       <%= f.button :submit %>
>     <% end %>  

But the inline editor doesn't work this way...

**Comment by galetahub** [comment]
If you want to use ckeditor with simple_form try this:
```
<%= simple_form_for @resume do |f| %>
  <%= f.input :formattedname, as: :ckeditor %>
  <%= f.button :submit %>
<% end %>  
```

**Comment by hassanc** [comment]
Thanks. I've already been able to get it to work as you suggested, but I want to utilize the inline editor instead like shown here:

http://docs.ckeditor.com/#!/guide/dev_inline

**Comment by mikewagz** [comment]
I am also hoping to use inline editing - any advice on getting that to work?
