### ISSUE TITLE
Drag & drop: uploadimage plugin gives no route error (/ckeditor/pictures&responseType=json)

### ISSUE THREAD

**Issue by johan--** [galetahub/ckeditor#763]
We want to integrate the uploadimage plugin (for drag & drop functionality), but get the following message:

ActionController::RoutingError (No route matches [POST] "/ckeditor/pictures&responseType=json"):

Is this supported in the gem library?

http://ckeditor.com/addon/uploadimage
http://sdk.ckeditor.com/samples/fileupload.html#uploading-dropped-and-pasted-images

**Comment by galetahub** [comment]
Hi,
Did you mount Ckeditor::Engine at config/routes.rb?
``` ruby
# config/routes.rb
mount Ckeditor::Engine => '/ckeditor'
```

**Comment by johan--** [comment]
Hi - thanks for the reply.  Yes, it is mounted, but it appears as if the engine not always loaded or recognized (issue #758 is related).  

For example, I had to include the helper method 'assets_pipeline_enabled?' in our application helper.  And the symptoms on development is different from that on production.

**Comment by johan--** [comment]
Hi - we've tried the uploadimage plugin in a very simple application, and although image uploading works just fine when using the file browser, it still fails when using drag & drop due to this error:

POST http://localhost:3000/ckeditor/pictures&responseType=json 404 (Not Found)

Could you perhaps suggest a workaround to fix this?

**Comment by galetahub** [comment]
Can you give me the project code for testing?
Are you using drag & drop at standart image upload dialog?

**Comment by johan--** [comment]
Hi - here it is (use the sandbox branch):

https://github.com/johan--/notes

config.extraPlugins = 'uploadfile';

(ignore the Dopler plugin)

rgrds,

Johan
[image: --]
johan pretorius
[image: http://]about.me/johanpretorius
<http://about.me/johanpretorius?promo=email_sig>



<http://about.me/johanpretorius>

**Comment by johan--** [comment]
Hi - here it is (use the sandbox branch):

https://github.com/johan--/notes

--> config.extraPlugins = 'uploadfile';

(ignore the Dopler plugin)

**Comment by JakeKaad** [comment]
If anyone ever has this issue with rails. The code is adding a query parameter, but the default route isn't delimiting query paramters. 

You can add a placeholder query parameter to get drag and drop to work:

ex:
`config.filebrowserImageUploadUrl = "/ckeditor/pictures?test=true"`

**Comment by johan--** [comment]
Thank you for this, I've tried the following, and it is working:

`filebrowserImageBrowseUrl:       "/ckeditor/pictures?",
 filebrowserImageUploadUrl:       "/ckeditor/pictures?",`

cc: @JakeKaad :+1:
