### ISSUE TITLE
Rails 5.1 support?

### ISSUE THREAD

**Issue by tannerj** [galetahub/ckeditor#764]
First off, thanks for the great work on this editor it has been very successful in our app. Just wanted to know if there is a road map yet for Rails 5.1 support? I upgraded our app a little while ago and noticed that file uploads started failing with 500 errors. After downgrading back to 5.0.4 things work again. After doing a little digging through the logs, it appears to be an error in ActionController::Parameters. Specifically converting unpermitted parameters to a hash:

ActionView::Template::Error (unable to convert unpermitted parameters to hash):

[Applicable changelog](https://github.com/rails/rails/blob/v5.1.1/actionpack/CHANGELOG.md#rails-510-april-27-2017)

Looking at the PicturesController, where this error originates. I noticed that strong parameters is not being used. Is there an underlying for this? If not I'd be happy to help with a pull request though I'm admittedly not very familiar with the CKEditor's code base. At any rate, here's the log entry for the error I encountered for future reference:

I, [2017-06-27T12:52:16.694448 #32547]  INFO -- : Started GET "/ckeditor/pictures?CKEditor=[REDACTED]&CKEditorFuncNum=1&langCode=en" for [REDACTED] at 2017-06-27 12:52:16 +0000
I, [2017-06-27T12:52:16.711230 #32547]  INFO -- : Processing by Ckeditor::PicturesController#index as HTML
I, [2017-06-27T12:52:16.711615 #32547]  INFO -- :   Parameters: {"CKEditor"=>”[REDACTED]”, "CKEditorFuncNum"=>"1", "langCode"=>"en"}
I, [2017-06-27T12:52:16.730383 #32547]  INFO -- :   Rendering[REDACTED]/shared/bundle/ruby/2.3.0/gems/ckeditor-4.2.2/app/views/ckeditor/pictures/index.html.erb within layouts/ckeditor/application
D, [2017-06-27T12:52:16.742412 #32547] DEBUG -- :   ^[[1m^[[36mCkeditor::Picture Load (2.1ms)^[[0m  ^[[1m^[[34mSELECT  "ckeditor_assets".* FROM "ckeditor_assets" WHERE "ckeditor_assets"."type" IN ('Ckeditor::Picture') ORDER BY id desc LIMIT $1 OFFSET $2^[[0m  [["LIMIT", 24], ["OFFSET", 0]]
I, [2017-06-27T12:52:16.979294 #32547]  INFO -- :   Rendered collection of [REDACTED]/shared/bundle/ruby/2.3.0/gems/ckeditor-4.2.2/app/views/ckeditor/shared/_asset.html.erb [24 times] (222.5ms)
D, [2017-06-27T12:52:16.991439 #32547] DEBUG -- :   ^[[1m^[[35m (3.0ms)^[[0m  ^[[1m^[[34mSELECT COUNT(*) FROM "ckeditor_assets" WHERE "ckeditor_assets"."type" IN ('Ckeditor::Picture')^[[0m
I, [2017-06-27T12:52:17.011483 #32547]  INFO -- :   Rendered [REDACTED]/shared/bundle/ruby/2.3.0/gems/ckeditor-4.2.2/app/views/ckeditor/pictures/index.html.erb within layouts/ckeditor/application (280.6ms)
I, [2017-06-27T12:52:17.013638 #32547]  INFO -- : Completed 500 Internal Server Error in 301ms (ActiveRecord: 5.2ms)
F, [2017-06-27T12:52:17.027301 #32547] FATAL -- :
F, [2017-06-27T12:52:17.027949 #32547] FATAL -- : ActionView::Template::Error (unable to convert unpermitted parameters to hash):
F, [2017-06-27T12:52:17.030154 #32547] FATAL -- :     11:
    12:   <% unless @pictures.last_page? %>
    13:     <div class="pagination">
    14:       <%= link_to I18n.t("ckeditor.buttons.next"), ckeditor.pictures_path(params.merge(page: @pictures.next_page)), class: "next", rel: "next" %>
    15:     </div>
    16:   <% end -%>
    17:
F, [2017-06-27T12:52:17.030259 #32547] FATAL -- :
F, [2017-06-27T12:52:17.030705 #32547] FATAL -- : actionpack (5.1.1) lib/action_controller/metal/strong_parameters.rb:258:in `to_h'
actionpack (5.1.1) lib/action_controller/metal/strong_parameters.rb:302:in `to_query'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:646:in `block in <class:Generator>'
actionpack (5.1.1) lib/action_dispatch/journey/formatter.rb:77:in `block in extract_parameterized_parts'
actionpack (5.1.1) lib/action_dispatch/journey/formatter.rb:76:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/formatter.rb:76:in `extract_parameterized_parts'
actionpack (5.1.1) lib/action_dispatch/journey/formatter.rb:21:in `block in generate'
actionpack (5.1.1) lib/action_dispatch/journey/formatter.rb:91:in `match_route'
actionpack (5.1.1) lib/action_dispatch/journey/formatter.rb:20:in `generate'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:736:in `generate'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:767:in `generate'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:814:in `url_for'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:267:in `call'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:208:in `call'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:323:in `block (2 levels) in define_url_helper'
actionpack (5.1.1) lib/action_dispatch/routing/routes_proxy.rb:32:in `pictures_path'
ckeditor (4.2.2) app/views/ckeditor/pictures/index.html.erb:14:in `__[REDACTED]_shared_bundle_ruby_______gems_ckeditor_______app_views_ckeditor_pictures_index_html_erb__4215528239819023351_46953715295080'
actionview (5.1.1) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.1) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.1) lib/action_view/template.rb:155:in `render'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
actionview (5.1.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.1) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.1) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
[REDACTED]/.rbenv/versions/2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (5.1.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.1) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
ckeditor (4.2.2) app/controllers/ckeditor/pictures_controller.rb:9:in `block (2 levels) in index'
actionpack (5.1.1) lib/action_controller/metal/mime_responds.rb:201:in `respond_to'
ckeditor (4.2.2) app/controllers/ckeditor/pictures_controller.rb:8:in `index'
actionpack (5.1.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.1) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.1) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.1) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.1) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.1) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.1) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
railties (5.1.1) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.1) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.1.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.1) lib/action_dispatch/routing/route_set.rb:832:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.1) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.1) lib/rails/engine.rb:522:in `call'
unicorn (5.3.0) lib/unicorn/http_server.rb:606:in `process_client'
unicorn (5.3.0) lib/unicorn/http_server.rb:702:in `worker_loop'
unicorn (5.3.0) lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
unicorn (5.3.0) lib/unicorn/http_server.rb:142:in `start'
unicorn (5.3.0) bin/unicorn:126:in `<top (required)>'
[REDACTED]/shared/bundle/ruby/2.3.0/bin/unicorn:23:in `load'
[REDACTED]/shared/bundle/ruby/2.3.0/bin/unicorn:23:in `<top (required)>'
bundler (1.13.6) lib/bundler/cli/exec.rb:74:in `load'
bundler (1.13.6) lib/bundler/cli/exec.rb:74:in `kernel_load'
bundler (1.13.6) lib/bundler/cli/exec.rb:27:in `run'
bundler (1.13.6) lib/bundler/cli.rb:332:in `exec'
bundler (1.13.6) lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
bundler (1.13.6) lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
bundler (1.13.6) lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
bundler (1.13.6) lib/bundler/cli.rb:20:in `dispatch'
bundler (1.13.6) lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
bundler (1.13.6) lib/bundler/cli.rb:11:in `start'
bundler (1.13.6) exe/bundle:34:in `block in <top (required)>'
bundler (1.13.6) lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
bundler (1.13.6) exe/bundle:26:in `<top (required)>'
[REDACTED]/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
[REDACTED]/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'

**Comment by maurosbu** [comment]
Did you try the edge version (master branch)? I'm using it and I don't have such kind of problems.
I had problems with Rails 5.1 + ckeditor v. 4.2.3.
@galetahub Many thanks for the great work!!! When is a release compatible with Rails 5.1 expected?

**Comment by galetahub** [comment]
Hi, 
Just released new gem version 4.2.4

Thanks
