### ISSUE TITLE
Accessing Uploaded Assets for easier Associations

### ISSUE THREAD

**Issue by MrAaronOlsen** [galetahub/ckeditor#779]
I'd like to start out by saying how much I appreciate that this Gem exists. I love that I can use it, and setting it up with Carrierwave, Fog, SimpleForm, and AWS was fairly smooth. However, I'm running into a problem, that I can solve, but I feel like there has got to be a better way. A right way. A Rails way...

The puzzle is how to associate the assets I loaded with Ckeditor to the Active Record model I'm sending my form params to. In this case it's a Post. With Carrierwave alone I could set up a many to many through or polymorphic relationship and load an array of images into my Post on creation. Ideally this would be the same with Ckeditor. I can inject myself into the asset creation flow of Ckeditor, but then what? Save ids to the session and find them again on Post create? Nope. Since my Post doesn't exist yet I can't attach a Post id to an asset, and anyway I'm not always creating a new asset.

My hacky solution was to add some identifier to the upload dir in the CkeditorPictureUploader (!picture!-#{model.id}) and parse the body string with some regex to find the ids of the pictures that ended up in the post. My other idea was to do this in the JavaScript side and build an array of id's to send in a hidden field on submit (gross!). I have a many to many through relationship with my Post model and Ckeditor::Asset. When I create a post I use the ids I parsed to build the relationship. Cool. Now I can get thumbs and such for other views. It works, but it feels like I'm walking a smelly old rickety fence.

It my perfect world I'd be able to create a ckeditor field alongside the other SimpleForm (or vanilla or whatever) fields that I would populate only with asset ids. Or better yet, just send the ids as an additional params option. Then on the backend I could create a Post (or whatever) in one nice simple Post.create(post_params). Maybe something like:
```ruby
= form.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } }, options: {ckeditor_assets_ids: ckeditor: { :assets }
```

I'm adding this in the issues because I'm a fan and it seems like something people would want to do and could be more intuitive. The solution isn't entirely clear or easy to find (for me at least) in the docs. If I'm missing the ball completely then at least this could act as a doc, or maybe I'd find time to extend this sort of feature myself.

Anyway, thanks for all the work that's been done to get Ckeditor in Rails. I don't know where people find the time...

**Comment by 1989medium** [comment]
@MrAaronOlsen , Возможно вам стоит попробовать создать отдельную модель для содержания post_id после создания поста:
class Body (only body:text & post_id:integer) and class Post (only title:string & has_many :bodies)
Таким образом у вас будет ID Post .
Как вы думайте?

**Comment by NARKOZ** [comment]
You can do it like this: https://stackoverflow.com/a/51740021/159721 

Just replace Article with Post in your case.

**Comment by NARKOZ** [comment]
ॣ

**Comment by NARKOZ** [comment]
‌‌
