### ISSUE TITLE
Update to CK Editor 5 release :)

### ISSUE THREAD

**Issue by sadiqmmm** [galetahub/ckeditor#782]
Update to CK Editor 5 release.

https://ckeditor.com

https://ckeditor.com/ckeditor-5-builds/

All new CK Editor 5 released :)

**Comment by DanAndreasson** [comment]
Is it supported, out of the box? :)

**Comment by ryush00** [comment]
Any updates?

**Comment by patricklindsay** [comment]
No plans to support Ckeditor 5 as of yet. Given that CK4 is still active we could possibly include both 4 & 5, having a config option to choose between them.

**Comment by feliperaul** [comment]
@patricklindsay I would strongly favor the option, since a lot of people won't upgrade to 5.
