### ISSUE TITLE
Browse Server for image error with ckeditor and paperclip using Rails 5 API

### ISSUE THREAD

**Issue by B-strappin** [galetahub/ckeditor#784]
Stack:
Rails 5.1.4
ckeditor 4.2.4
paperclip 5.1.0

Error:
Started GET "/ckeditor/pictures?CKEditor=js-ckeditor&CKEditorFuncNum=1&langCode=en" for 172.23.0.1 at 2017-10-23 22:40:22 +0000
ActionController::RoutingError (undefined method `layout' for Ckeditor::ApplicationController:Class):
ckeditor (4.2.4) app/controllers/ckeditor/application_controller.rb:2:in `<class:ApplicationController>'
ckeditor (4.2.4) app/controllers/ckeditor/application_controller.rb:1:in `<top (required)>'

I used the ckeditor installation instructions from the github readme page: https://github.com/galetahub/ckeditor

When running the generator "rails generate ckeditor:install --orm=active_record --backend=paperclip" no controllers were created or views and I am assuming they are part of the gem and have generated needed source code elsewhere? Any help would be greatly appreciated.

**Comment by bosunolanrewaju** [comment]
I have a similar issue using same stack. But the error on only happens on Heroku. It works fine locally in development environment but gives error on Heroku with the same message:

/app/vendor/bundle/ruby/2.3.0/gems/ckeditor-4.2.4/app/controllers/ckeditor/application_controller.rb:2:in 
`<class:ApplicationController>': 
undefined method `layout' for Ckeditor::ApplicationController:Class (NoMethodError)

@B-strappin Were you able to get a solution?

**Comment by MishaGubsky** [comment]
Hey
I had the same issue. So I cloned the [Ckeditor::ApplicationController](https://github.com/galetahub/ckeditor/blob/master/app/controllers/ckeditor/application_controller.rb) and added `include ::ActionView::Layouts`. It solved the problem. Maybe it'll help for someone.

**Comment by pmontrasio** [comment]
Adding to a closed issue: I had the same problem right now with Rails 5.2.3, Ckeditor 4.1.1, Paperclip 6.1.0. I had the problem only in production mode, development and test were fine. Maybe I never really exercised the code in the ckeditor controller and production mode loads it. 

I solved it by upgrading Ckeditor to 4.2.4 which currently is the last one of the 4.2 versions. No need to add the initializer.
