### ISSUE TITLE
Source - Does not work in Development

### ISSUE THREAD

**Issue by kaewdev** [galetahub/ckeditor#786]
Hi, 

I have found that going into source format does not work in development mode. It works fine in production.
Development:
It keeps blinking in and out when hovering and selecting the textarea after going into source view. 
At first glance, it looks like the assets need to be precompiled for it to work properly.

Is there a fix for this?

Thanks,
Kae

**Comment by patricklindsay** [comment]
Closing this, if you're still having the issue feel free to reopen with more information and/or a test case/example app reproducing the issue.
