### ISSUE TITLE
Unable to send picture uploaded to the server

### ISSUE THREAD

**Issue by vanegomez** [galetahub/ckeditor#787]
Hi there, 
I'm getting this error in production. 

ActiveRecord::StatementInvalid in Ckeditor::PicturesController#create

<img width="1186" alt="screen shot 2017-11-10 at 4 47 26 pm" src="https://user-images.githubusercontent.com/10290117/32683236-0e7f163e-c637-11e7-995f-4e6d2ec0036a.png">

**Comment by patricklindsay** [comment]
Closing this, if you're still having the issue feel free to reopen with more information and/or a test case/example app reproducing the issue.
