### ISSUE TITLE
I cannot override the default configs while using the gem

### ISSUE THREAD

**Issue by suthanbala** [galetahub/ckeditor#789]
I created the config files at `/app/assets/javascripts/ckeditor/config.js`. The app wasn't loading that config. However, when I went into the `public/assets/ckeditor/` and removed the `config.js` there, it loaded the custom `config.js` fine.

My Environment:
- Docker, and mounting the volume on my dev environment
- Rails 5.0.0.1
- Ruby 2.3.3
- Using the CKEditor along with Active Admin

**Comment by patricklindsay** [comment]
Closing this, if you're still having the issue feel free to reopen with more information and/or a test case/example app reproducing the issue.
