### ISSUE TITLE
Upgrade to 4.8

### ISSUE THREAD

**Issue by Nittarab** [galetahub/ckeditor#791]
Hi, is possible to upgrade ckeditor to 4.8? There are a lot of new features

**Comment by JakeKaad** [comment]
Can somebody help me understand the necessary files for upgrading CKEditor to 4.8? The site I am working on requires some of the features available in 4.8 and I wanted to fork this gem and update the version.

**Comment by patricklindsay** [comment]
Will soon be updating to `4.11`
