### ISSUE TITLE
Release fix for Migration version error

### ISSUE THREAD

**Issue by asecondwill** [galetahub/ckeditor#793]
Can we get a release of this fix:

https://github.com/galetahub/ckeditor/pull/776

 so we can use it with rails 5, eg 

https://github.com/solidusio-contrib/solidus_editor/issues/17

Thanks

**Comment by patricklindsay** [comment]
Will be released soon

**Comment by feliperaul** [comment]
@patricklindsay thanks

**Comment by patricklindsay** [comment]
Closed by release of `v4.3.0`
