### ISSUE TITLE
Please, add ActiveStorage!

### ISSUE THREAD

**Issue by nikolaokonesh** [galetahub/ckeditor#795]
Please, add ActiveStorage!
How integrate ActiveStorage ?

**Comment by galetahub** [comment]
Hi,

I will integrate ActiveStorage in next gem release

Thanks

**Comment by nikolaokonesh** [comment]
@galetahub Спасибо!

**Comment by ahmetabdi** [comment]
@galetahub Any update on this you can share?

**Comment by kelso** [comment]
Please, it would be awesome to have support for ActiveStorage in ckeditor! 🙏 

Some official docs:

* https://github.com/rails/rails/tree/5-2-stable/activestorage#active-storage
* http://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-files-to-records
* http://edgeguides.rubyonrails.org/active_storage_overview.html

**Comment by ahmetabdi** [comment]
I've made my own implementation for the adapter, happy to help @galetahub if needed

**Comment by MojoJosh** [comment]
@ahmetabdi Is this implementation available anywhere?

**Comment by ahmetabdi** [comment]
@MojoJosh 

Create `models/ckeditor/active_storage.rb`
```
module Ckeditor
  module ActiveStorage
    def self.included(base)
      base.send(:include, InstanceMethods)
      base.send(:extend, ClassMethods)
    end

    module ClassMethods
      def self.extended(base)
        base.class_eval do
          before_validation :apply_data
        end
      end
    end

    module InstanceMethods
      protected

      def file
        @file ||= data
      end

      def blob
        @blob ||= ::ActiveStorage::Blob.find(file.attachment.blob_id)
      end

      def apply_data
        self.data_file_name = blob.filename
        self.data_content_type = blob.content_type
        self.data_file_size = blob.byte_size
      end
    end
  end
end
```

Then inside `models/ckeditor/asset.rb` add `include Ckeditor::ActiveStorage`

```
require 'active_storage'

module Ckeditor
  class Asset < ActiveRecord::Base
    include Ckeditor::Orm::ActiveRecord::AssetBase
    include Ckeditor::ActiveStorage
  end
end
```

then in `models/ckedtor/picture.rb`

```
module Ckeditor
  class Picture < Asset
    include Rails.application.routes.url_helpers

    has_one_attached :data

    def url_content
      rails_blob_url(blob)
    end

    class << self
      def default_url_options
        Rails.application.config.action_mailer.default_url_options
      end
    end
  end
end
```

**Comment by m-andreas** [comment]
Thanks @ahmetabdi  !
But sadly the file browser is not working. No images are displayed and the upload there is also not working.

Did anybody find a solution for that already?

**Comment by m-andreas** [comment]
To see the images in the file browser you have to add the url_tumb method as well to the picture class:

    def url_thumb
      rails_representation_url(data.variant(resize: "118x100"))
    end

The upload part will get harder ...

**Comment by Obversity** [comment]
Has any progress been made on this?

**Comment by MrBlazOn** [comment]
Any progress officially?

**Comment by richpeck** [comment]
The main issue with this is that it has to attach to the object/model that's currently being managed. Since ActiveStorage has its own tables, for what would you use the `ckeditor_assets` table once you switch?

**Comment by patricklindsay** [comment]
We currently have no plans to support ActiveStorage however PRs are welcome!

**Comment by mayordwells** [comment]
For anyone who cares [ActionText ](https://github.com/rails/actiontext)on Rails 6 is already supporting ActiveStorage out the box.

**Comment by EnziinSystem** [comment]
@nguyenkhuyen 
Great solution!
Can you customize for attachment document files? (pdf, docx...)
Thanks.

**Comment by m-andreas** [comment]
Be careful with the recommended changes, as they dont seem to work with version 2.3
My changes are running in production with ckeditor 2.2.4

**Comment by bilal14079** [comment]
@nguyenkhuyen thanks for your solution but in my case its showing data and attachment as nil in "apply_data" method when I send attachment on server after uploading.
My ckeditor version is 4.0 , I know you told early on that your solution worked on 2.2.4.
If you can help me to solve it than it would be a great help.

Thanks

**Comment by nguyenkhuyen** [comment]
hi @EnziinSystem, @bilal14079, since CKEditor is not planned to support ActiveStorage and some deadlines in my projects then I cannot follow up with this issue, but I still love CKEditor as it is my favorite editor, I will try my best to get back with this soon :)

**Comment by bilal14079** [comment]
@nguyenkhuyen  okay thanks for your time and quick response :)

**Comment by vishaltps** [comment]
I am getting below when I try to upload the image with above solution

`PG::UndefinedTable: ERROR: relation "ckeditor_assets" does not exist`

**Comment by wnm** [comment]
for anyone who comes here from google (as I did), trying to figure out how to make ckeditor 5 work with an activestorage backend, here is a gist for you: https://gist.github.com/wnm/db58502da38bb8514a5a4b1d16fda173
