### ISSUE TITLE
Problems in production

### ISSUE THREAD

**Issue by francisneedham** [galetahub/ckeditor#797]
Hi,
using the gem in local enviroment works perfectly  - when i upload in prodocution on heroku the toolbar ignores my config.js file.

any hints ?

**Comment by nikolaokonesh** [comment]
@francisneedham app/assets/config/manifest.js edit. add directory ckeditor...

**Comment by martinchenu** [comment]
@nikolaokonesh can you give more details please ?  Thank you mate

**Comment by nikolaokonesh** [comment]
@francisneedham @martinchenu 

> /app/assets/config/manifest.js
//= link_tree ../images
//= link_tree ../javascripts/ckeditor
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
//= link ckeditor/application.css
//= link ckeditor/application.js

вот и всё. Work fine!
