### ISSUE TITLE
Editor not working in bootstrap modal

### ISSUE THREAD

**Issue by TranqTech** [galetahub/ckeditor#800]
I'm using forms within bootstrap modals. Problem is that as soon as the modal is hidden and reopened, or replaced via ajax, the editor ceases to function correctly. I know some people have had issue in the past with the toolbar not functioning within the modal, but my issue is that the text window stays blank and cannot be interacted with. It almost seems like the editor needs to be reinit whenever the modal is opened, but I'm unsure how to achieve this.

Viewing the console, attempting to interact with the editor throws the error:

Uncaught TypeError: Cannot read property 'getSelection' of ckeditor.self.etc.... undefined

**Comment by patricklindsay** [comment]
Closing this, if you're still having the issue feel free to reopen with more information and/or a test case/example app reproducing the issue.
