### ISSUE TITLE
Paperclip “Data content type is not valid” after trying upload image in rails 

### ISSUE THREAD

**Issue by elisbresciani** [galetahub/ckeditor#801]
This is what appear in my log:

```
Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x7e20e68
@tempfile=#<Tempfile:C:/Users/bi/AppData/Local/Temp/2/RackMultipart20180116-3004-iw0tdo.jpg>,
@original_filename="Inkedmdb atualizado_LI.jpg", @content_type="image/jpeg", 
@headers="Content-Disposition: form-data; name=\"upload\"; 
filename=\"Inkedmdb atualizado_LI.jpg\"\r\nContent-Type: image/jpeg\r\n">,
"ckCsrfToken"=>"AR65EsJdr219Nu21oN1Vlw8fc8XAJTc5ZTIQ1lg9", "CKEditor"=>"pop_objective", 
"CKEditorFuncNum"=>"1", "langCode"=>"pt-br"}

Command :: file -b --mime "C:/Users/bi/AppData/Local/Temp/2/43a60d0ece9425495f704619dc133c4f20180116-3004-bkzljx.jpg"

Command :: identify -format '%wx%h,%[exif:orientation]' "C:/Users/bi/AppData/Local/Temp/2/242e48571825b96df1752e5c3933b2fd20180116-3004-1n87xt.jpg[0]" 2>NUL
```
I searched on internet end they suggested me to create a new file in the initializer to overwrite the method spoof or something like that, I created, and now the error changed, but still there.

> Data content type is not valid

this is my validation in model:

```
has_attached_file :image,
    :styles => {
      :thumb => '32x32#',
      :medium => '64x64#',
      :large => '256x256#'
    },
    :default_url => "/images/default.png",
    :content_type => { :content_type => [
                                            'image/jpg',
                                            'image/png',
                                            'image/jpeg',
                                            'image/gif',
                                            'image/tiff',
                                            'image/PNG'
                                        ]
                     }
```
the paperclip is integrated with ckeditor. i opened a issue in paperclip but i don't have any answers. 

Does someone have any ideas, why that happening?

**Comment by mikos** [comment]
I was getting a similar error with the Dragonfly backend. It ended up I didn't have Imagemagick installed.

**Comment by elisbresciani** [comment]
But I have, and until about two weeks ago it was working, I did not make any changes to the project. I checked if the imagemagick was installed, if it was pointing to the right place, that's all right.

**Comment by elisbresciani** [comment]
@mikos What did you do to solve it?

**Comment by mikos** [comment]
@elisbresciani I installed ImageMagick

**Comment by elisbresciani** [comment]
Oh okay, this solution does not solve my problem because I already have it installed, but thanks for the tip.

**Comment by Marc5690** [comment]
My (working) setup is similar to this:

`has_attached_file :data,
                    url: 'C:/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: 'C:/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }
  
  def url_content
    url(:content)
  end

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  validates_attachment_content_type :data, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]
`

Try to fiddle around with the syntax and it'll work, I promise.

**Comment by elisbresciani** [comment]
I solved it, it was a compilation problem of assets, my .bat to raise the rails server was not compiling, I uploaded the server at hand, compiling the assets, and ran. But thanks for the tip, I'll take a look at this too if the problem happens again.

**Comment by Marc5690** [comment]
No problem Elis, good luck!
