### ISSUE TITLE
Update README to show that gem 'ckeditor' doesn't work in Rails 5

### ISSUE THREAD

**Issue by chaseTfreeman** [galetahub/ckeditor#802]
Can you update the README to show that gem 'ckeditor' doesn't work in Rails 5 because of the migration issue. I wasted unnecessary time trying to debug that when the issue is already documented in your issues., with the fix being to  pull from the master branch (gem 'ckeditor', github: 'galetahub/ckeditor').

Original Error: 
rake db:migrate
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
  class CreateCkeditorAssets < ActiveRecord::Migration[4.2]

**Comment by patricklindsay** [comment]
Hmm not sure exactly what version you're using but `4.2.4` is compatible up to Rails `5.1.4`.

New release is coming soon though.
