### ISSUE TITLE
Security issue in default behaviour

### ISSUE THREAD

**Issue by Nitrino** [galetahub/ckeditor#803]
In the default behavior, the `/ckeditor/pictures` and `/ckeditor//attachment_files` requests are always available. And for them, any users can view all images uploaded to the server.

Is there any way to disable the `index` action without override controllers or monkey patches?

**Comment by patricklindsay** [comment]
You can use Pundit or CanCan to handle authorization.

https://github.com/galetahub/ckeditor#cancan-integration
