### ISSUE TITLE
Release version 2.4.5

### ISSUE THREAD

**Issue by Nitrino** [galetahub/ckeditor#804]
Gem `cocaine` was renamed to `terrapin` and now last released version print warning:
```
===========================================
 DEPRECATION: The cocaine gem is deprecated. Please upgrade to terrapin. See https://github.com/thoughtbot/terrapin/ for further instructions.
===========================================
```

In the master branch it is already fixed. 
Also in the master version now fixed bug with migrations #802

Please release new version.

**Comment by patricklindsay** [comment]
Closed by release of `v4.3.0`
