### ISSUE TITLE
Automatically Dropped Some tables and recreated with empty tables in Mysql

### ISSUE THREAD

**Issue by khalidh12** [galetahub/ckeditor#808]
Automatically Dropped Some tables and recreated with empty tables in Mysql

Here My log:

****
`Started GET "/assets/ckeditor/plugins/tableselection//styles/tableselection.css" for 83.82.104.10 at 2018-05-18 06:27:48 +0000
Cannot render console from 183.82.104.102! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255  

  ^[[1m^[[36m (11.5ms)^[[0m  ^[[1m**DROP TABLE `assignapps`** CASCADE^[[0m
  ^[[1m^[[35m (13.7ms)^[[0m  **CREATE TABLE `assignapps`** (`id` int(11) auto_increment PRIMARY KEY, `adminid` int(11), `userid` int(11), `created_at` dat$
  ^[[1m^[[36m (5.2ms)^[[0m  ^[[1m**DROP TABLE `comments` CASCADE**^[[0m
  ^[[1m^[[35m (12.7ms)^[[0m  CREATE TABLE `comments` (`id` int(11) auto_increment PRIMARY KEY, `roadblock_id` int(11), `user_id` int(11), `body` text,$
  ^[[1m^[[36m (5.8ms)^[[0m  ^[[1m**DROP TABLE `extratestedfors` CASCADE**^[[0m
  ^[[1m^[[35m (14.9ms)^[[0m  CREATE TABLE `extratestedfors` (`id` int(11) auto_increment PRIMARY KEY, `extra1` varchar(255), `extra2` varchar(255), `e$
  ^[[1m^[[36m (6.0ms)^[[0m  ^[[1mDROP TABLE `issues` CASCADE^[[0m
  ^[[1m^[[35m (13.4ms)^[[0m  CREATE TABLE `issues` (`id` int(11) auto_increment PRIMARY KEY, `issuesname` varchar(255), `location` mediumtext, `severi$
  ^[[1m^[[36m (3.1ms)^[[0m  ^[[1mDROP TABLE `kpis` CASCADE^[[0m
  ^[[1m^[[36mActiveRecord::SchemaMigration Load (0.2ms)^[[0m  ^[[1mSELECT `schema_migrations`.* FROM `schema_migrations`^[[0m
  ^[[1m^[[35mActiveRecord::SchemaMigration Load (0.2ms)^[[0m  SELECT `schema_migrations`.* FROM `schema_migrations`
  ^[[1m^[[36m (0.4ms)^[[0m  ^[[1mSELECT fk.referenced_table_name as 'to_table'
      ,fk.referenced_column_name as 'primary_key'
      ,fk.column_name as 'column'
      ,fk.constraint_name as 'name'
FROM information_schema.key_column_usage fk
WHERE fk.referenced_column_name is not null
  AND fk.table_schema = 'Local_db'
  AND fk.table_name = 'assignapps'
^[[0m
`

Same Issue for other user also:
[https://www.experts-exchange.com/questions/27935283/CKEDITOR-on-PHP-mySQL-Wipes-out-record-in-database-on-save.html](url)

**Comment by patricklindsay** [comment]
Closing this, if you're still having the issue feel free to reopen with more information and/or a test case/example app reproducing the issue.

(This is a Rails gem, not the official Ckeditor product)
