### ISSUE TITLE
Upgrading to CKEditor 4.10.0?

### ISSUE THREAD

**Issue by mullermp** [galetahub/ckeditor#812]
What would be the work required to upgrade this gem to CKEditor 4.10.0 and publishing a new version to rubygems.org?

There are some bug fixes around pasting text into the editor that have been released and are needed in this gem.

**Comment by patricklindsay** [comment]
Yep will be releasing to 4.11.0 soon

**Comment by gingerlime** [comment]
Thanks @patrickdavey. Any ETA on soon ? ;-) or was it already released?
