### ISSUE TITLE
Problems uploading images

### ISSUE THREAD

**Issue by ljonny18** [galetahub/ckeditor#815]
I have created an Engine including CKEditor.

Within my dummy application the form.cktext_area is working and rendering fine, however when I try to upload images I get the following exception: 

ActionController::InvalidAuthenticityToken in Ckeditor::PicturesController#create

Is this because I'm using CKEditor within an engine, in turn, causing some authentication/protection problem? 

Thanks,
Jon.

**Comment by patricklindsay** [comment]
Need more information than this to help you out. What Ckeditor version are you using, what Rails version, have you followed the README and set your `parent_controller`?

Closing this, if you're still having the issue feel free to reopen with more information and/or a test case/example app reproducing the issue.
