### ISSUE TITLE
can't generate models to store uploaded files

### ISSUE THREAD

**Issue by ljonny18** [galetahub/ckeditor#816]
When running the coomand: 

rails generate ckeditor:install --orm=active_record --backend=carrierwave

I get the following error: 

/.../.rvm/gems/ruby-2.3.0/gems/ckeditor-4.2.4/lib/generators/ckeditor/templates/ckeditor.rb:52:in `template': uninitialized constant Ckeditor::Version (NameError)

I have tried with both: 

gem 'ckeditor'
and 
gem 'ckeditor', github: 'galetahub/ckeditor'

Any help/support would be greatly appreciated.

Thanks,
Jon.

**Comment by nikolaokonesh** [comment]
@ljonny18 add gem 'carrierwave'.

**Comment by ljonny18** [comment]
its already added ... thanks :)

**Comment by patricklindsay** [comment]
Closing this, if you're still having the issue feel free to reopen with a test case/example app reproducing the issue.
