### ISSUE TITLE
Browser server button outside editor

### ISSUE THREAD

**Issue by ThatsARapp** [galetahub/ckeditor#817]
Is there a way to access the server browser outside the editor? I would like to have a button where I can upload or select an image from the server and potentially return the url of the image to be saved in a separate field (i.e. "Featured Image"). Im working on a blog app and this would be very helpful.

**Comment by patricklindsay** [comment]
This would be possible however it's up to you to work out how to implement it. Good luck!

**Comment by Tectract** [comment]
Can we get any advice or help making this happen? This is a highly desired feature.
