### ISSUE TITLE
NoMethodError (undefined method `gsub' for nil:NilClass) with CarrierWave and Cloudinary after successful upload.

### ISSUE THREAD

**Issue by chrisgaraffa** [galetahub/ckeditor#818]
Rails version 5.2.1, ruby version 2.5.1p57

I have CKEditor, CarrierWave and Cloudinary set up and working for the most part. Files are being uploaded to Cloudinary - I see them in the Dashboard - and rows are being added to the ckeditor_assets table. If I refresh after uploading a file, I can click Browse and select/insert the file into the CKEditor instance.

However, uploading files returns the following error in the rails console instead of showing the uploaded image in the Image Properties dialog:

```
NoMethodError (undefined method `gsub' for nil:NilClass):

/Users/chris/.rvm/gems/ruby-2.5.1/bundler/gems/ckeditor-dc2cef2c2c33/lib/ckeditor/utils.rb:12:in `escape_single_quotes'
/Users/chris/.rvm/gems/ruby-2.5.1/bundler/gems/ckeditor-dc2cef2c2c33/lib/ckeditor/asset_response.rb:89:in `asset_url'
/Users/chris/.rvm/gems/ruby-2.5.1/bundler/gems/ckeditor-dc2cef2c2c33/lib/ckeditor/asset_response.rb:56:in `success_ckeditor'
/Users/chris/.rvm/gems/ruby-2.5.1/bundler/gems/ckeditor-dc2cef2c2c33/lib/ckeditor/asset_response.rb:39:in `success'
/Users/chris/.rvm/gems/ruby-2.5.1/bundler/gems/ckeditor-dc2cef2c2c33/app/controllers/ckeditor/application_controller.rb:14:in `respond_with_asset'
/Users/chris/.rvm/gems/ruby-2.5.1/bundler/gems/ckeditor-dc2cef2c2c33/app/controllers/ckeditor/pictures_controller.rb:15:in `create'
```
...
Here is my `ckeditor_picture_uploader.rb` file. I haven't modified `asset.rb` or `picture.rb`.

```
class CkeditorPictureUploader < CarrierWave::Uploader::Base
  include Ckeditor::Backend::CarrierWave
  include Cloudinary::CarrierWave

  process :convert => 'png'
  process :tags => ['page_image']

  version :thumb do
    process :resize_to_fill => [100, 150, :north]
  end

  version :standard do
    process :resize_to_fill => [100, 150, :north]
  end

  version :content do
    process resize_to_limit: [2500, 9999]
  end

  version :thumbnail do
    resize_to_fit(50, 50)
  end

end

```

**Comment by nguyenductoan** [comment]
@patrickdavey 
If you did not touch the `picture.rb`, i think it would look like: 
```
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end
```
It raises error because the `picture` object does not reloaded to get new `data_file_name`
I think the following code would solve your problem:
```
```
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    self.reload.url(:content)
  end
end
```
```
