### ISSUE TITLE
MiniMagick needed for attachments?

### ISSUE THREAD

**Issue by acesuares** [galetahub/ckeditor#820]
Something strange.

In PictureUploader, I replace all underscores with hyphens. Thus:

````
def filename
  original_filename.gsub('_','-') if original_filename
end
````

Works fine!
But in AttachmentFileUploader, it doesn't work. It results in Invalid Parameter: invalid filename in Carrierwave cache.rb line 198.

But after I enabled MiniMagcik (which was of course enabled in PictureUploader, but should not be enabled in AttachmentFileUploader, and wasn't), it started working.

Is this something that can be reproduced???

````class CkeditorAttachmentFileUploader < CarrierWave::Uploader::Base
  include Ckeditor::Backend::CarrierWave

  # Include RMagick or ImageScience support:
  # include CarrierWave::RMagick
  include CarrierWave::MiniMagick
  # include CarrierWave::ImageScience

  # Choose what kind of storage to use for this uploader:
  storage :file

  # rip the underscore from allowed filenames
  # this was NOT the way to do it, it turns out
  # CarrierWave::SanitizedFile.sanitize_regexp = /(_|[^[:word:]\.\-\+])/

  # this is the way to rip out the underscores. Carrierwave already rips out everything bad,
  # but is replaces it hardcoded with '_'

  def filename
    original_filename.gsub('_','-') if original_filename
  end
````

**Comment by patricklindsay** [comment]
If you can provide an app which reproduces this behaviour I'd be happy to take a look.
