### ISSUE TITLE
Gallery option not available in image uploads on android.

### ISSUE THREAD

**Issue by Luey-Ny0ike** [galetahub/ckeditor#821]
Hi, I set up image uploads on ckeditor with paperclip and everything seems to be working fine on all devices apart from android devices. When I click on choose file, I only see camera option but no gallery option. My users can't upload images from their phone. Tell me if you need a little more information. Thanks
![whatsapp image 2018-10-11 at 08 42 49 1](https://user-images.githubusercontent.com/27731551/46784667-b0542500-cd37-11e8-9acf-f39547c6437b.jpeg)

**Comment by patricklindsay** [comment]
What android version are you testing on? Can they not access pictures within documents? Just tried on my Android and I have access to files through which I can find the images from my camera. Although I agree it would be nicer to have a gallery shortcut.
