### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.lang.justify.left')

### ISSUE THREAD

**Issue by afuno** [galetahub/ckeditor#827]
Today I updated your gem. Rails 5.1.6.1. The update was from version 4.2.4 to version 4.3.0.

As a result, one of the editors with the custom toolbar stopped working. Its configuration is:
```js
CKEDITOR.editorConfig = function (config) {
  config.toolbar_private_message = [
    [
      'Bold', 'Italic', 'Underline', 'Strike',
      '-',
      'NumberedList', 'BulletedList'
    ]
  ];

  config.toolbar = 'private_message';
}
```

As slim (in view):
```slim
= f.cktext_area :content, class: 'form-control', ckeditor: { toolbar: 'private_message' }
```

I didn't change the configuration. I just updated the gem.

As a result, I get this error in the browser console:
> TypeError: undefined is not an object (evaluating 'e.lang.justify.left')

In compiled JS, this is the line:
```js
label: e.lang.justify.left,
```

And almost the complete code of this place:
```js
}, CKEDITOR.plugins.add("justify", {
    init: function(e) {
        if (!e.blockless) {
            var t = new a(e, "justifyleft", "left"),
                n = new a(e, "justifycenter", "center"),
                i = new a(e, "justifyright", "right"),
                o = new a(e, "justifyblock", "justify");
            e.addCommand("justifyleft", t), e.addCommand("justifycenter", n), e.addCommand("justifyright", i), e.addCommand("justifyblock", o), e.ui.addButton && (e.ui.addButton("JustifyLeft", {
                label: e.lang.justify.left, // here
                command: "justifyleft",
                toolbar: "align,10"
            }), e.ui.addButton("JustifyCenter", {
                label: e.lang.justify.center,
                command: "justifycenter",
                toolbar: "align,20"
            }), e.ui.addButton("JustifyRight", {
                label: e.lang.justify.right,
                command: "justifyright",
                toolbar: "align,30"
            }), e.ui.addButton("JustifyBlock", {
                label: e.lang.justify.block,
                command: "justifyblock",
                toolbar: "align,40"
            })), e.on("dirChanged", r)
        }
    }
})
```

**What is the problem?**

**Comment by patricklindsay** [comment]
This gem doesn't come bundled with the `justify` plugin so I'm assuming you have previously downloaded it from [here](https://ckeditor.com/cke4/addon/justify)

If thats correct then you'll want to download the latest plugin version from the link above. You should do this for any extra plugins you have installed.

If that doesn't work if you can provide me with a sample app of the issue I'll look into this further.

**Comment by afuno** [comment]
I would agree with you, but...

Elsewhere I use this toolbar:
```slim
= f.cktext_area :content, class: 'form-control', ckeditor: { toolbar: 'mini' }
```

It looks like this:
<img width="1380" alt="2019-01-04 17 08 54" src="https://user-images.githubusercontent.com/2853419/50692015-8dd65d00-1043-11e9-9613-c4aca315f4d1.png">

And it contains justify plugin. Is not it? Not a single mistake.

That's just for this gem, I did not download anything extra. This Rails application has this gem without installing any additional plug-ins for this editor.

**Comment by patricklindsay** [comment]
I'm struggling to understand what exactly is going on. Please provide a sample Rails app reproducing the issue and I'll take a look.
