### ISSUE TITLE
v4.3.0   rails 5.2.1  (No route matches [GET] "/assets/ckeditor/plugins/copyformatting/lang/en.js"

### ISSUE THREAD

**Issue by pvin** [galetahub/ckeditor#828]
Facing similar issue  mentioned in [issues/757](https://github.com/galetahub/ckeditor/issues/757)  

**ActionController::RoutingError (No route matches [GET] "/assets/ckeditor/plugins/copyformatting/lang/en.js"**

Tried again and faced issue  said by @teddyswu @ccastillop  download copyformatting and install, can solve it but now i get new problem

 **Uncaught TypeError: Cannot read property '17' of undefined**

A solution said by  @ccastillop

Just don't use vendor, use ckeditor by CDN

**This works.**   

there is any way to use through vendor ??

**Comment by tatyana12** [comment]
I have the same error as below on ruby on rails. How to fix it?
ActionController::RoutingError (No route matches [GET] "/assets/ckeditor/plugins/copyformatting/lang/en.js"):

**Comment by chrisnebgen** [comment]
Running into a similar issue when pushing to heroku... but only on one server.

**Comment by chandragj** [comment]
Same error? Any solutions please post
