### ISSUE TITLE
Cannot Upload Image to Cloudinary

### ISSUE THREAD

**Issue by Davigl** [galetahub/ckeditor#832]
Can someone help me? I'm using carrierwave and cloudinary as cloud storage and i'm getting terrapin error when i try to upload an image.

ckeditor gem version: 4.3.0
code detail: https://gist.github.com/Davigl/5a159ccc8fab3d4ade44b5abe0749536

the old and existing solutions seems to be no longer working.

### console
```
Terrapin::CommandNotFoundError (No such file or directory - file -b --mime-type
"C:/arrr/public/uploads/tmp/1549379380-1920-0001-6884/CEFAS.png"):

app/uploaders/ckeditor_picture_uploader.rb:15:in `block (2 levels) in <class:Ck
ditorPictureUploader>'
```

**Comment by galetahub** [comment]
Hi,
I have removed auto-detect content-type, so now this error is fixed
