### ISSUE TITLE
Integrating this gem into Rails 6

### ISSUE THREAD

**Issue by Derek52** [galetahub/ckeditor#835]
Does this Gem support ruby on rails 6? I am trying to set this up in a new rails 6 test project I created, and am stumped by the new javascript directory.
Instead of having app/assets/javascripts/, there is a new director at app/javascript, and I can't figure out what the equivalent of `//= require ckeditor/init` would be, with the new javascript setup.

**Comment by galetahub** [comment]
Please, try gem version 5.0.0, but it has only CDN support
