### ISSUE TITLE
attachment_files#create (NoMethodError) "undefined method `data=' for #<Ckeditor::AttachmentFile:0x00...

### ISSUE THREAD

**Issue by developerRohan** [galetahub/ckeditor#843]
I am getting an above error while uploading files using send it to server option through link tag in ckeditor.

Also, if I use browse server option, then files take infinite uploading time.
![upload_file](https://user-images.githubusercontent.com/23002337/55461679-a6d6b600-5612-11e9-8245-57c0b0186faa.png)

**Comment by developerRohan** [comment]
resuelto.

**Comment by sekrett** [comment]
How did you solve this?
