### ISSUE TITLE
Using ckeditor with expiring aws s3 presigned image urls

### ISSUE THREAD

**Issue by vmalvaro** [galetahub/ckeditor#844]
I'm using this gem and it works great, but now I need to use images uploaded to a private bucket on S3. In order to do this I'm using Carrierwave + fog, the image uploads well and generates a presigned url.

The problem is that this url expires after certain time, this is a requirement for private files on s3. So the next time I load the editor after that time the image in the url is not longer available.

I thought on parsing with Nokigiri the ckeditor html string before it loads and replacing each img src url with a new one generated, but I don't like this solution very much.

Anyone solve this before or have an idea how this could be best implemented?

Thanks!!

**Comment by chandragj** [comment]
Searching for the answer on how to address the above question

**Comment by ashshakya** [comment]
Still waiting for the answer. I face a similar problem.

**Comment by chandragj** [comment]
You need to make fog_public true in your uploader, so it will update granular permission for fog_public, pre signed urls are by default expire after 10 minutes, the above will overwrite those granular permissions and make them available.
