### ISSUE TITLE
app/views/ckeditor/attachment_files/index.html.erb broken

### ISSUE THREAD

**Issue by 1v** [galetahub/ckeditor#845]
> This change breaks the view. @attachments is not an AR model or enumerable class and as such causes an empty file list to be rendered. It is a paginator, which is why the .scoped method worked, as it returns an AR model. Please correct. ../pictures/index.html.erb is still correct and functioning.

See comments: https://github.com/galetahub/ckeditor/commit/8b5d21d1a8727e2b9e1dba505f04b485ba840d37

**Comment by 1v** [comment]
Same.

**Comment by 1v** [comment]
Same.

**Comment by 1v** [comment]
Same

**Comment by 1v** [comment]
Same

**Comment by 1v** [comment]
Hello?

**Comment by patricklindsay** [comment]
Can you provide more information? If you can create a app which reproduces this issue I'll take a look

**Comment by 1v** [comment]
Just create default rails app. Upload attachment (not picture) and open window with attachment index. There will be no files.

**Comment by yourtallness** [comment]
The `app/views/ckeditor/attachment_files/index.html.erb` used to pass `@attachments.scoped` as the collection, not `@attachments`.

This is a bug.
