### ISSUE TITLE
Ckeditor v5.0.0 dont show 'insert' toolbar

### ISSUE THREAD

**Issue by baodoan97** [galetahub/ckeditor#863]
Yesterday anything did well. The ckeditor i added to my app show full toolbar
But then i merge and push code, ckeditor dont show 'insert' and some toolbar anymore
I tried install CK with Active Storage follow instruction many time but it still not show.
I tried to configured 'config.js' too but nothing happen.

**Comment by m-andreas** [comment]
There seems to be some issue when the custom config.js gets loaded. I am running into the same issue.

The error in the console is:
"ReferenceError: CKEDITOR is not defined"

Maybe I can do some research on this tomorrow.

**Comment by h3xed** [comment]
Change
`config.cdn_url = "//cdn.ckeditor.com/4.6.1/basic/ckeditor.js"`
to
`config.cdn_url = "//cdn.ckeditor.com/4.6.1/standard/ckeditor.js"`

in `config/initializers/ckeditor.rb`
