### ISSUE TITLE
including a plugin generates an error

### ISSUE THREAD

**Issue by offwhite** [galetahub/ckeditor#868]
I've added ckeditor to a rails application:

`gem 'ckeditor', github: 'galetahub/ckeditor'`

and the integration went as expected. However, the baffling lack of Justify methods means I have to include the justify plugin.

```
// app/assets/javascripts/ckeditor/config.js

if (typeof(CKEDITOR) != 'undefined') {
  CKEDITOR.editorConfig = function( config )
  {
    config.extraPlugins = "justify";
  }
}
```

(I added the is undefined check to stop the `CKEDITOR is undefined error`, but that's not relevant)

adding the extraPlugins line generates a JS error

```
GET http://cdn.ckeditor.com/4.11.3/standard/plugins/justify/plugin.js?t=J1QB net::ERR_ABORTED 404 (Not Found)
```
at ckeditor.js:101

**Comment by evanthegrayt** [comment]
Was anyone able to solve this issue? Having the same problem...

**Comment by Pyo25** [comment]
Same issue here!
