### ISSUE TITLE
Upload image show loading forever

### ISSUE THREAD

**Issue by donguyenipk** [galetahub/ckeditor#869]
Dear Community,

I'm using Rails 5.2.3 (Ruby 2.6) with "rails_admin" 2.0, and using the latest update of rails_ckeditor.
When I try to upload an image it shows "Loading..." forever as attached image: http://prntscr.com/pkv90n . There's no errors in browser console or so.

Anyone get this issue?

Thanks

**Comment by sekrett** [comment]
You should check rails log for more info. It would be a guess otherwise.
