### ISSUE TITLE
No "Upload" and "Advanced" tab in insert image dialog

### ISSUE THREAD

**Issue by goofansu** [galetahub/ckeditor#870]
I'm using ckeditor in rails_admin.

ckeditor version: 5.0.0
rails_admin version: 2.0.0

My ckeditor config:
```ruby
Ckeditor.setup do |config|
  require 'ckeditor/orm/active_record'
end
```

**Insert image button**
<img width="670" alt="Screenshot of Google Chrome (2019-10-27, 12-27-12 PM)" src="https://user-images.githubusercontent.com/1143191/67629719-254bbb80-f8b5-11e9-9ff5-57676749329f.png">

**In the image dialog, no "Upload" and "Advanced" tab, also missing "Browse Server" button**
<img width="522" alt="Screenshot of Google Chrome (2019-10-27, 12-17-56 PM)" src="https://user-images.githubusercontent.com/1143191/67629691-afdfeb00-f8b4-11e9-8acd-64a28301283d.png">

**Original version**
ckeditor version: 4.2.7
<img width="528" alt="Screenshot of Google Chrome (2019-10-27, 12-19-02 PM)" src="https://user-images.githubusercontent.com/1143191/67629741-78257300-f8b5-11e9-9430-9fd26554ffe2.png">

Does it need additional configuration? Thanks

**Comment by goofansu** [comment]
Sorry, it's not ckeditor gem's problem, the rails_admin loads config from CDN by default.

For anyone having this problem, configure the ckeditor field in rails_admin like following:

```
field :description, :ck_editor do
  config_js ActionController::Base.helpers.asset_path('ckeditor/config.js')
end
```

See https://github.com/sferik/rails_admin/issues/3126 and https://github.com/sferik/rails_admin/issues/3162

Closed.

**Comment by kevinhq** [comment]
> Sorry, it's not ckeditor gem's problem, the rails_admin changes to load ckeditor config from CDN by default in See https://github.com/railsadminteam/rails_admin/issues/3126.

Why does loading config from CDN cause those missing tabs? I don't understand. it doesn't make sense to me.
