### ISSUE TITLE
How to use my own controller to browse server?

### ISSUE THREAD

**Issue by petervandeput** [galetahub/ckeditor#876]
Because of some very specific handling of images in my system, I need CKEditor when clicking on image and browsing the server to use my own controller to handle our custom logic.
setting a config.parent_controller in initializer didn't work.
please advice

**Comment by patricklindsay** [comment]
Setting `parent_controller` should do the trick.

What version of Rails & Ckeditor are you using? If you can provide a sample application of the issue I can take a look.
