### ISSUE TITLE
inline editor?

### ISSUE THREAD

**Issue by benl96** [galetahub/ckeditor#880]
does this provide the following functionality?

https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html

best regards

**Comment by patricklindsay** [comment]
Yes inline editing works. All editor features should work as the editor functionality is loaded directly from the official CDN (by default).

All this gem really does is help to integrate a Rails application with Ckeditor by providing some basic configuration, form wrappers and a file manager.
