### ISSUE TITLE
ckeditor/init.js

### ISSUE THREAD

**Issue by danielweil** [galetahub/ckeditor#892]
Hey, 

Can someone help me with an issue? I have updated ckeditor to  4.2.4 at master@752bca9, and when a page loads it gives me three error messages.

DEPRECATION WARNING: The asset "ckeditor/init.js" is not present in the asset pipeline.Falling back to an asset that may be in the public folder.
Started GET "/javascripts/ckeditor/init.js" for 127.0.0.1 at 2020-06-24 19:55:52 -0300
ActionController::RoutingError (No route matches [GET] "/javascripts/ckeditor/init.js"):

Is there anything I can do?

Thank You

**Comment by yourtallness** [comment]
Are you loading ckeditor from a cdn?

In the latest gem version `ckeditor/init.js` is not necessary any more.
