### ISSUE TITLE
Couldn't add plugin issue

### ISSUE THREAD

**Issue by baodoan97** [galetahub/ckeditor#897]
Hi.
I see that our `config.js` file have included "font size and family", "justify" setting but these icon not show in the toolbar
So I try to research and understand that our gem using standard package which not have these plugin
Then I try to install two above plugin by following exactly document (download and put plugin and all depedencies to `ckeditor/plugins`)
Unfortunately, I got the error `resource name 'font' was not found`
I also searching to fix this problem but nothing can help me
Does anyone know how to fix this issue?

**Comment by baodoan97** [comment]
Change `config.cdn_url` in `ckeditor` to load full package ver help me no need to adding 'font' plugin. But When try to add image2 plugin I get this issue again. 
Can anyone help?

**Comment by babalooi** [comment]
Had the same issue here. Couldn't add extra plugins as described [here](https://github.com/galetahub/ckeditor#install-additional-plugins).

Found out [here](https://cdn.ckeditor.com) under **Enabling Local Plugins** that you can define external plugin path.

For example loading YouTube plugin, config.js can be written like this:
```javascript
CKEDITOR.plugins.addExternal(
  "youtube",
  "/assets/ckeditor/plugins/youtube/",
  "plugin.js"
);

CKEDITOR.editorConfig = function (config) {
  config.extraPlugins = "youtube";
};
```

**Comment by truongduyng** [comment]
> Had the same issue here. Couldn't add extra plugins as described [here](https://github.com/galetahub/ckeditor#install-additional-plugins).
> 
> Found out [here](https://cdn.ckeditor.com) under **Enabling Local Plugins** that you can define external plugin path.
> 
> e.g.
> Loading YouTube plugin, config.js can be written like this:
> 
> ```js
> CKEDITOR.plugins.addExternal(
>   "youtube",
>   "/assets/ckeditor/plugins/youtube/",
>   "plugin.js"
> );
> 
> CKEDITOR.editorConfig = function (config) {
>   config.extraPlugins = "youtube";
> };
> ```

This will not work on production env as the path will be changed after assets precompile :(

**Comment by MicahBrown** [comment]
Nobody has a solution to this? Seems like plugin support is pretty essential and I can't get it working with CKE 4 and rails 6. I tried the solution posted [here](https://krazedkrish.com/blog/2016/11/20/how-to-add-plugins-to-ckeditor-in-rails/) to no avail.

**Comment by mattgilbertnet** [comment]
> > Had the same issue here. Couldn't add extra plugins as described [here](https://github.com/galetahub/ckeditor#install-additional-plugins).
> > Found out [here](https://cdn.ckeditor.com) under **Enabling Local Plugins** that you can define external plugin path.
> > e.g.
> > Loading YouTube plugin, config.js can be written like this:
> > ```js
> > CKEDITOR.plugins.addExternal(
> >   "youtube",
> >   "/assets/ckeditor/plugins/youtube/",
> >   "plugin.js"
> > );
> > 
> > CKEDITOR.editorConfig = function (config) {
> >   config.extraPlugins = "youtube";
> > };
> > ```
> 
> This will not work on production env as the path will be changed after assets precompile :(

I was able to get this to work by using the `/public` folder instead of the the `/app/assets` folder, avoiding the assets pipeline.

**Comment by thanhtoan1196** [comment]
any updates?
