### ISSUE TITLE
Ckeditor not getting custom config

### ISSUE THREAD

**Issue by jesupadial** [galetahub/ckeditor#909]
Hi, im trying to use a custom config using the config.js file but its not working. I have cleared the cache and I have tried a bunch of different configurations in order to try another stuff but its not working. Here is my `config.js`:

![Captura](https://user-images.githubusercontent.com/17835172/115581806-a2000000-a2c8-11eb-985c-c284ba10b6f9.PNG)

**Comment by demo360o2** [comment]
Hi have you solved your issue? I have the exact same problem... I'm interessted by you'r solution if you have any.

**Comment by PatrickKing** [comment]
I've been unable to solve this on 5.x. Reverting to 4.3 lets us use the bundled CKEditor with a config file.

**Comment by asecondwill** [comment]
This is still a problem for me,  I'm trying to include my custom config.js in my app/javascript/active_admin.js  file, but then the gem includes config.js which seems to override my config so i cant use my custom toolbars.

any tips?

**Comment by asecondwill** [comment]
Solved, and now i feel silly.  I dont think I realised that I can still use the asset pipeline for javascript, if needed. 

so i moved my config to /app/assets/ckeditor/config.js and now that is used instead of the default.
