### ISSUE TITLE
ckeditor not rendering in heroku

### ISSUE THREAD

**Issue by sankha90** [galetahub/ckeditor#916]
ckeditor is not rendering in heroku with django and its returning a default form but when I am running it locally its working fine.

installed modules : 

asgiref==3.4.1
bleach==4.1.0
dj-database-url==0.5.0
Django==3.2.6
django-aloha-edit==0.3.3
django-ckeditor==6.1.0
django-editorjs==0.2.1
django-heroku==0.3.1
django-js-asset==1.2.2
django-tinymce==3.3.0
gunicorn==20.1.0
lxml==4.6.3
packaging==21.0
psycopg2==2.9.1
pyparsing==2.4.7
python-decouple==3.4
pytz==2021.1
six==1.16.0
sqlparse==0.4.1
webencodings==0.5.1
whitenoise==5.3.0

Am I missing something?

**Comment by jansgreen** [comment]
be sure tha you hava installed whitenoise

setting.py
```
MIDDLEWARE = [
...
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```
requirements.txt
whitenoise==xxxxx
