### ISSUE TITLE
CKEditor4 reached its End-of-Life in June 2023

### ISSUE THREAD

**Issue by rvalladares77** [galetahub/ckeditor#933]
I'd like to know if there is a plan to upgrade Ckeditor from version 4 to version 5.

It seems that this gem is using an old version of Ckeditor 4 ([4.11.3](https://github.com/galetahub/ckeditor/blob/master/lib/ckeditor/version.rb#L6)) that has security vulnerabilities.

There is also the possibility to upgrade ckeditor 4 to CKEditor 4.23.0-lts.

**Comment by galetahub** [comment]
It seems, CKEditor 4.23.0 LTS available only under a commercial licence

**Comment by Uaitt** [comment]
Yeah unfortunately @galetahub you are right. CKEditor versions 4.23.0 LTS and above require a commercial license. 😢 

Are there any plan to upgrade to version 5?

**Comment by galetahub** [comment]
Yes, I will try to upgrade to version 5 in next couple of days

**Comment by schmijos** [comment]
I like the business model. Switch to paid-mode and mark old versions as insecure. 🤦 

![CleanShot 2024-07-03 at 15 38 27](https://github.com/galetahub/ckeditor/assets/245443/ad442a9e-a270-429b-aacf-517ec9cf2482)

**Comment by chrisedington** [comment]
Thanks @galetahub appreciate the confirmation of the update!

**Comment by amclelland** [comment]
In the meantime:

```css
.cke_notifications_area {
  display: none;
}
```

**Comment by johndoe12336** [comment]
@amclelland Where does that code go?

**Comment by johndoe12336** [comment]
`config.versionCheck = false;` worked for me

**Comment by galetahub** [comment]
Just released new gem version 5.1.3, with `config.versionCheck = false;` by default

**Comment by dil-atiwari** [comment]
@galetahub  I wanted to ask if there are any plans or timelines in place for upgrading to CKEditor 5. Given the improvements in usability, accessibility, and new features that [CKEditor 5](https://ckeditor.com/docs/ckeditor5/latest/getting-started/index.html) offers, an upgrade could provide significant benefits to our application. Is there any other way to use [CKEditor 5](https://ckeditor.com/docs/ckeditor5/latest/getting-started/index.html)?

**Comment by Mati365** [comment]
@dil-atiwari Consider using https://github.com/Mati365/ckeditor5-rails, as it supports the newest version of CKEditor.
