### ISSUE TITLE
In gem ckeditor v5.1.2: app/assets/config/manifest.js overrides main manifest.js application configuration (Rails 7.1.3.4)

### ISSUE THREAD

**Issue by Sega100500** [galetahub/ckeditor#938]
In gem ckeditor v5.1.2: app/assets/config/manifest.js overrides main manifest.js application configuration - all directives of main application are losed after mount ckeditor gem (Rails 7.1.3.4).
According to the unspoken rules, the manifest file for a gem should be called: <gem_name>_manifest.js, i.e. in your case ckeditor_manifest.js (I don’t remember exactly where, but this topic was discussed earlier, and it was never reflected in the official Rails documentation).

**Comment by galetahub** [comment]
I just renamed app/assets/config/manifest.js to app/assets/config/ckeditor_manifest.js and it's worked.
All tests passed.

**Comment by galetahub** [comment]
This will be fixed in the upcomming release 5.1.3

**Comment by galetahub** [comment]
Fixed in 5.1.3 release
