### ISSUE TITLE
Getting warning this CKEditor 4.11.3 version is not secure

### ISSUE THREAD

**Issue by rohit-gilbile** [galetahub/ckeditor#939]
![Screenshot 2024-07-23 153652](https://github.com/user-attachments/assets/c9c93130-5ede-487d-b816-685af450c037)

**Comment by rohit-gilbile** [comment]
Resolved

**Comment by elbzero** [comment]
@rohit-gilbile how did you resolve?

**Comment by galetahub** [comment]
@elbzero you have two options to resolve:
1. Turn off this warning in your CKEditor config: `config.versionCheck = false;`
2. Upgrade ckeditor gem to the latest version
