### ISSUE TITLE
Ckeditor upgrade 

### ISSUE THREAD

**Issue by dil-atiwari** [galetahub/ckeditor#941]
I would like to inquire if there are any plans to upgrade to [CKEditor 5](https://ckeditor.com/docs/ckeditor5/latest/getting-started/index.html)?

**Comment by rvalladares77** [comment]
I guess your question is related to this one.: https://github.com/galetahub/ckeditor/issues/933

**Comment by dil-atiwari** [comment]
@rvalladares77  I have already seen the post which you shared which is related to the end of life for a specific version of CKEditor, but I'm specifically interested in whether there are any plans for upgrading CKEditor 5.

**Comment by dil-atiwari** [comment]
@rvalladares77  I wanted to ask if there are any plans or timelines in place for upgrading to CKEditor 5. Given the improvements in usability, accessibility, and new features that CKEditor 5 offers, an upgrade could provide significant benefits to our application. Is there any other way to use Ckeditor 5 ?

**Comment by Mati365** [comment]
@dil-atiwari Consider using newer gem: https://github.com/Mati365/ckeditor5-rails. Few things need to be done, like image upload but overall it should work.

**Comment by dil-atiwari** [comment]
@Mati365  Thank you for the new gem. Are there any plans to implement image upload functionality? This feature will be crucial.

**Comment by Mati365** [comment]
@dil-atiwari Yep, check comment: https://github.com/Mati365/ckeditor5-rails/issues/6#issuecomment-2482061678
